### ISSUE TITLE
Relays without power continue to work as relays until the vessel was loaded once

### ISSUE THREAD

**Issue by MartinDomig** [Kerbalism/Kerbalism#133]
If, and only if a vessel is LOADED and out of power, KSP will update its communication network to exclude that vessel. If the vessel runs out of power while it is UNLOADED, KSP won't do that. Which makes perfect sense, since stock KSP won't deplete batteries of unloaded vessels, that's a feature added by Kerbalism. So, if your relay is dead in space, it will still relay for you until you loaded it once.

![how2disable](https://user-images.githubusercontent.com/4105874/42626646-26a856f4-85cb-11e8-9557-baa5e9568ade.gif)

Possible solution: similar to what is done for RemoteTech, Kerbalism could try to set `canComm = False` on all `ModuleDataTransmitter` modules. Or maybe there is some other KSP `CommNet` API that can do that...

**Comment by MartinDomig** [comment]
I tried to disable the communication of a uloaded vessel when power is out, but so far no luck:

- `vessel.connection.enabled = false` doesn't work
- `Lib.ReflectionValue(ModuleDataTransmitter, "canComm", false)`doesn't work
- I was looking for a _proper_ way to disable a vessel in the communication network using the available API, but so far I couldn't find a proper way to disable a vessel or remove it from the communication network. The methods and fields that look promising are all read only, or cannot set values.

I'm out of ideas. Anyone?

**Comment by PiezPiedPy** [comment]
Did this get solved ?
