### ISSUE TITLE
Magnetosphere support for Sentar expansion

### ISSUE THREAD

**Issue by lajoswinkler** [Kerbalism/Kerbalism#169]
There's one planetary body I'd like to have a "tail" and that's Ablate. Sentar is a gas giant so it could get a typical Joolean radiation belts, but Ablate is the most interesting one because it's a metal core.

I've described the issue [here](https://forum.kerbalspaceprogram.com/index.php?/topic/172400-131145-kerbalism-v171/&do=findComment&comment=3434819), and details of the shape have been discussed on the science subforum [here](https://forum.kerbalspaceprogram.com/index.php?/topic/177581-metal-rich-planetoid-thought-experiment/). Basically the same stuff Eve has, but longer and not above the surface turned towards Kerbol.

PiezPiedPy advised to open a Github issue for this.
![ablate-magnetosphere3-lw](https://user-images.githubusercontent.com/9791430/44293413-1b7b0100-a28b-11e8-8fba-2578dd7898b4.png)

**Comment by gotmachine** [comment]
I believe planet pack support are to done by the author of the planet pack (maybe you can propose a PR)
I don't think we want to maintain patches for all the planet packs lying around.
