### ISSUE TITLE
Weird behaviour with FASA Launch Tower

### ISSUE THREAD

**Issue by syscryp** [Kerbalism/Kerbalism#170]
Kerbalism doesn't play nicely with the Launch Tower in FASA Launch Clamps Continued. When Kerbalism is on, the launch tower has a negative cost of 4934.9 (meaning launches are significantly cheaper than they should be), and the tower gains loads of additional mass which appears to being added to the parent part in the VAB, messing up TWR and delta-V calculations. 

The part has a crew capacity of 16, so I'm guessing Kerbalism is calculating it as a big crew compartment, and putting ECLSS modules on the tower. It would probably be better if Kerbalism ignored it entirely.

As a short-term work-around, editing the tower's part config to remove the crew capacity makes the problem go away, but that somewhat defeats the point of the tower! Maybe an MM patch for Kerbalism to ignore the tower would be a better solution?

Thanks!

**Comment by theJesuit** [comment]
The delta vee issue is KER related I think. Possible as the tower attaches not to bottom stage in the stack.

 The volume could be set as near to zero.  That may help with mass issues.

**Comment by Gordon-Dry** [comment]
I just recognized that the FASA Launch Tower (from Bluedog DB) is calculated in the EC/s for climatization, no matter if "simulate in planner" is on or off.

**Comment by Gordon-Dry** [comment]
The absolute minimum of change would be to set the habitat to be disabled by default and turn off the life support modules by default when the part got MODULE[LaunchClamp].
I'll try to manage that by MM and push it then.
