### ISSUE TITLE
 When extended solar panels break, after fixing them they stay retracted

### ISSUE THREAD

**Issue by the-emerald** [Kerbalism/Kerbalism#171]
Title. An extendable solar panel just broke, and after sending an engineer to fix it, the solar panel stayed retracted. However, it still generates electricity. Manually retracting the panel via EVA does nothing.

![desktop screenshot 2018 08 19 - 20 50 02 56](https://user-images.githubusercontent.com/12746683/44309058-251f7880-a3f3-11e8-91ef-47cd560233e2.png)

**Comment by SirMortimer** [comment]
Probably one of the KSP quirks.
