### ISSUE TITLE
Dehydration in desert biomes

### ISSUE THREAD

**Issue by JebEddun** [Kerbalism/Kerbalism#20]
Hi buddy. I love Kerbalism! Good job continuing it.
I am creating a mod that's mostly desert based.
I'm wondering if it would be possible for Kerbalism to make the Kerbals water consumption higher when located in desert biome, when exposed to direct sunlight.

This is a huge request, i'm hoping you'll consider it.

Thanks!

**Comment by SirMortimer** [comment]
Should be done in Profile/configuration.
