### ISSUE TITLE
Bug: Asteroid Sample not working

### ISSUE THREAD

**Issue by SidMarcus** [Kerbalism/Kerbalism#201]
Hello,

I have started using this mod recently, and I just encoutered a bug : when I try to take an asteroid sample (during EVA), nothing happens.
An error is thrown in the logs about a NullReference to a ModuleScienceContainer (see .txt attachment
[KSP_kerbalism_error_asteroid_sample.txt](https://github.com/steamp0rt/Kerbalism/files/2385888/KSP_kerbalism_error_asteroid_sample.txt) ).
Apparently the game tries to store the data through a ModuleScienceContainer module, but this module is not present on kerbals with the Kerbalism mod (it is present in stock).
Has somebody else already encountered this problem ?

Thanks in advance.

KSP Version: 1.4.3
Kerbalism Version: 1.7.1.1
Other mods installed: CommunityResourcePack, KerbalEngineer

**Comment by SidMarcus** [comment]
No reason, 1.7.1.1 was the version I used until now. I just updated to 1.9, and I encounter the same issue.

**Comment by PiezPiedPy** [comment]
looks like you have found a bug then, I'll look into it

**Comment by SidMarcus** [comment]
Thank you :). As a workaround, I temporarily deleted the block "Remove stock science data containers" in Kerbalism/System/Science.cfg and restarted the game. This enabled me to take the asteroid sample. The experiment is stored correctly in a Kerbalism hard drive.

**Comment by gotmachine** [comment]
Duplicate of #458
