### ISSUE TITLE
Part upgrades: Planner should check if a module has moduleIsEnabled = false

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#215]
Planner should check if a module has 
moduleIsEnabled = False
and also a 
```
        UPGRADES
        {
            UPGRADE
            {
                name__ = whatever_blahblah
                description__ = blah blah blah
                moduleIsEnabled = True
            } 
        }

```
to only be taken into account when the module REALLY is enabled.

This also avoids that the planner shows modules as unlocked when they're not, because mods like KCT are used to unlock nodes (with a waiting time).

**Comment by Gordon-Dry** [comment]
Actually I still struggle in implementing my part upgrades with my patch.

Issue 1:
The planner already shows the reliability info/button when the module is/should not be available.

This points to issue 2; I'm not sure if the culprit is elsewhere or if even Kerbalism is the culprit:
In my special case the modules are already available before the tech tree node even is unlocked.

Using KCT it could happen that a part upgrade shows as unlocked before the time passed by that KCT needs to research the tech tree node. But a tech tree node that is even not scheduled to be unlocked by KCT could also trigger a part upgrade that should not be available.
But this means then it has nothing to do with KCT - it's something else.

Perhaps the simple check if the module is still disabled and then not showing the reliability could solve some issues.

**Comment by gotmachine** [comment]
Upgrades that enable/disable modules trough moduleIsEnabled manipulation are barely working in stock, it's (unfortunately) not a reliable way of doing it.
Plus there are many conflicts possible with our own handling of disabled partmodules (configure module, reliability...)
