### ISSUE TITLE
UI issue with icon scaling

### ISSUE THREAD

**Issue by LogicalEnigma** [Kerbalism/Kerbalism#217]
I'm having an issue with the UI in the game. 

The picture below is how the UI looks in the Space Center.

![kerbalism issues](https://user-images.githubusercontent.com/13333949/46384426-d9175300-c683-11e8-8cb0-315f3af1f146.png)

The VAB

![kerbalism issues2](https://user-images.githubusercontent.com/13333949/46384516-78d4e100-c684-11e8-89ce-9a275a834b4e.png)

And In-flight

![kerbalism issues3](https://user-images.githubusercontent.com/13333949/46384521-7ffbef00-c684-11e8-91ee-6cbec2636181.png)

![kerbalism issues4](https://user-images.githubusercontent.com/13333949/46384523-825e4900-c684-11e8-8152-10647948159e.png)

My Game is pretty heavily modded, but I've been removing mods to see if any of them are interacting with Kerbalism negatively. None that influence UI have changed the issue. I also ran KSP on a clean install with just the base game, Kerbalism, and its dependencies installed. Still got the same issue. 

I'm on KSP 1.3.1. I installed the BackPort-ed version of the mod. 

I have no Idea what the issue could be.

**Comment by PiezPiedPy** [comment]
Check your UI scaling in the Kerbalism Settings.cfg, they are at the bottom of the file.

**Comment by LogicalEnigma** [comment]
The UI Scaling is at 1.0 for Width and Length (which I assume is the default). I've tried manipulating them but it just looks the same, just slightly larger.

**Comment by PiezPiedPy** [comment]
strange, I'll look into it

**Comment by LogicalEnigma** [comment]
![kerbalism issuess](https://user-images.githubusercontent.com/13333949/46386431-6ad88d80-c68f-11e8-88a1-f447f4afbc15.png)

This is with the setting "UIScale" set to 2.0

**Comment by LogicalEnigma** [comment]
> strange, I'll look into it
> btw what download did you use, Spacedock, GitHub or CKAN and what version ?

SpaceDock. I downloaded the v1.90.0, the version backported to 1.3.1. I even tried 1.80.1. Had the same issue.

**Comment by PiezPiedPy** [comment]
Ok 😉

**Comment by LogicalEnigma** [comment]
Hey, I found a fix (if it even qualifies as a fix). I downloaded it via CKAN and it works perfectly fine. No idea why. Thanks for responding when the time came though!

**Comment by Pa781** [comment]
Hi, I have the exact same issue with a clean KSP 1.3.1 install. I tried multiple versions of Kerbalism, from 1.9.0 to 2.1.2, both manually and with CKAN.
On some versions the applauncher.png icon is cropped, sometimes not, but the other icons always are. They are cropped in a way that only the top-right quarter is visible, looks like a alignement issue. I tried modifying the applauncher.png from 38x38 to 76x76 with the actual icon moved to the top-right corner, the image was resized and still cropped, the icon just got smaller.
The only version I tried that didn't show this issue was 1.2.8, on KSP 1.2.2 and 1.3.1.

**Comment by PiezPiedPy** [comment]
I can't find the problem that causes this for the life of me, so I gave up :/

**Comment by Pa781** [comment]
**Looks like I fixed it**. (At least with Kerbalism 2.1.2 on KSP 1.3.1; I rebuilt it and took the Kerbalism.dll, so it'll probably break everything if used in another version - but the problem only seem to happen in 1.3.1 anyway)
Note that with this fix icons won't scale with the UI Scale in-game setting anymore; but at least they show up correctly.

1. Dowload this [Kerbalism.dll](http://s000.tinyupload.com/index.php?file_id=25440535069014870549) and put it in GameData\Kerbalism
2. The vessel filter icons will look huge and overflow, you can batch resize all the .png icons in GameData\Kerbalism\Textures\vessels to 20x20 with an online tool like [iloveimg.com](https://www.iloveimg.com/resize-image/resize-png)
3. :
![20190309_The_Expanse_1 3 1_Y7D286](https://user-images.githubusercontent.com/48333218/54071472-11dbd980-426d-11e9-9363-73c9eace6c5a.png)

The fix:
There's an issue with the function that scales the texures (maybe because KSP 1.3.1 uses an older version of Unity ?). I don't understand it, so in Icons.cs I just replaced all GetUIScaledTexture with GetTexture directly.

**Comment by PiezPiedPy** [comment]
Out of curiosity what Platform are you using and what Texture setting have you used in KSP's graphics settings ?

**Comment by Pa781** [comment]
What do you mean by platform ? I edited the source code with Visual Studio 2017, there's a complete guide in the source .zip called Contributing.md. As for the settings I turned them down to minimum with a 1280x720 resolution on my development install to save time, but the screenshot above comes from my regular install (1920x1080, Quality Level = Good, Texture Quality = Half Res, AA = x8, Fullscreen disabled with -popupwindow).

**Comment by PiezPiedPy** [comment]
Platform means Windows, mac etc. We had problems with the icons on the mac builds. As for texture level, there are known problems with KSP and icons when using LowRes, maybe try with HighRes and see what happens.

btw I co-wrote the Contributing.md 😉

**Comment by steamp0rt** [comment]
@Pa781 post the code that you changed

**Comment by Pa781** [comment]
I'm on Windows 10, and Full Res doesn't solve the issue. Also thanks @PiezPiedPy for that quality read :)
As for the code:
```
///<summary> Initializes the icons </summary>
internal static void Initialize()
{
	TexturePath = KSPUtil.ApplicationRootPath + "GameData/Kerbalism/Textures/";

	empty = Lib.GetTexture("empty");                      // an empty icon to maintain alignment
	close = Lib.GetTexture("close");                      // black close icon
	left_arrow = Lib.GetTexture("left-arrow");            // white left arrow
	right_arrow = Lib.GetTexture("right-arrow");          // white right arrow
	toggle_green = Lib.GetTexture("toggle-green");        // green check mark
	toggle_red = Lib.GetTexture("toggle-red");            // red check mark

	send_black = Lib.GetTexture("send-black");            // used by file man
	send_cyan = Lib.GetTexture("send-cyan");
	lab_black = Lib.GetTexture("lab-black");
	lab_cyan = Lib.GetTexture("lab-cyan");

	applauncher = Lib.GetTexture("applauncher", 38, 38);

	small_info = Lib.GetTexture("small-info");
	small_folder = Lib.GetTexture("small-folder");
	small_console = Lib.GetTexture("small-console");
	small_config = Lib.GetTexture("small-config");
	small_search = Lib.GetTexture("small-search");
	small_notes = Lib.GetTexture("small-notes");

	category_normal = Lib.GetTexture("category-normal");
	category_selected = Lib.GetTexture("category-selected");

	sun_black = Lib.GetTexture("sun-black");
	sun_white = Lib.GetTexture("sun-white");

	battery_white = Lib.GetTexture("battery-white");
	battery_yellow = Lib.GetTexture("battery-yellow");
	battery_red = Lib.GetTexture("battery-red");

	box_white = Lib.GetTexture("box-white");
	box_yellow = Lib.GetTexture("box-yellow");
	box_red = Lib.GetTexture("box-red");

	wrench_white = Lib.GetTexture("wrench-white");
	wrench_yellow = Lib.GetTexture("wrench-yellow");
	wrench_red = Lib.GetTexture("wrench-red");

	signal_white = Lib.GetTexture("signal-white");
	signal_yellow = Lib.GetTexture("signal-yellow");
	signal_red = Lib.GetTexture("signal-red");

	recycle_yellow = Lib.GetTexture("recycle-yellow");
	recycle_red = Lib.GetTexture("recycle-red");

	radiation_yellow = Lib.GetTexture("radiation-yellow");
	radiation_red = Lib.GetTexture("radiation-red");

	health_white = Lib.GetTexture("health-white");
	health_yellow = Lib.GetTexture("health-yellow");
	health_red = Lib.GetTexture("health-red");

	brain_white = Lib.GetTexture("brain-white");
	brain_yellow = Lib.GetTexture("brain-yellow");
	brain_red = Lib.GetTexture("brain-red");

	storm_yellow = Lib.GetTexture("storm-yellow");
	storm_red = Lib.GetTexture("storm-red");

	plant_white = Lib.GetTexture("plant-white");
	plant_yellow = Lib.GetTexture("plant-yellow");

	station_black = Lib.GetTexture("vessels/station-black");
	station_white = Lib.GetTexture("vessels/station-white");

	base_black = Lib.GetTexture("vessels/base-black");
	base_white = Lib.GetTexture("vessels/base-white");

	ship_black = Lib.GetTexture("vessels/ship-black");
	ship_white = Lib.GetTexture("vessels/ship-white");

	probe_black = Lib.GetTexture("vessels/probe-black");
	probe_white = Lib.GetTexture("vessels/probe-white");

	relay_black = Lib.GetTexture("vessels/relay-black");
	relay_white = Lib.GetTexture("vessels/relay-white");

	rover_black = Lib.GetTexture("vessels/rover-black");
	rover_white = Lib.GetTexture("vessels/rover-white");

	lander_black = Lib.GetTexture("vessels/lander-black");
	lander_white = Lib.GetTexture("vessels/lander-white");

	eva_black = Lib.GetTexture("vessels/eva-black");
	eva_white = Lib.GetTexture("vessels/eva-white");

	plane_black = Lib.GetTexture("vessels/plane-black");
	plane_white = Lib.GetTexture("vessels/plane-white");
}
```
As you can see I just used GetTexture here instead of GetUIScaledTexture to load icons without changing their size.

**Comment by PiezPiedPy** [comment]
probably would be better to use the KSP13 directive in conjunction with the changes.

**Comment by Pa781** [comment]
Well, I didn't intended to do a commit or any broad release... I don't really know much about the issue and only circumvented it, removing a feature (Icons scaling with UI) so I only uploaded a fix for anyone with this issue; maybe someone else can do it properly, in the mean time there's this fix.
It's limited to 1.3.1 by definition 🙃 but if the issue appear on another version I guess it wouldn't take much effort to copy paste this part of the code.

**Comment by steamp0rt** [comment]
what did you change? in comparison to the current file

**Comment by steamp0rt** [comment]
see if this fixes it @Pa781 https://builds.steamport.xyz/Kerbalism-2.2.0-BUILD433.zip

**Comment by Pa781** [comment]
The icons are ok in the VAB: 
![UI2](https://user-images.githubusercontent.com/48333218/54190235-bf402e80-44b3-11e9-933f-11412ed2a51c.png)
But not for the vessel filter ones which aren't rescaled in-game :
![UI](https://user-images.githubusercontent.com/48333218/54190226-bc453e00-44b3-11e9-930f-28c3fc9742e4.png)
(Same on 1280x720 or 1920x1080 resolutions, I tried just in case)

**Comment by steamp0rt** [comment]
How were they being rescaled in your code?

**Comment by Pa781** [comment]
They weren't, I resized those icons manually with an online tool. The other icons were already correctly sized, but they won't dynamically scale either

**Comment by steamp0rt** [comment]
Hm, I'll have to tackle this problem myself

**Comment by gotmachine** [comment]
Is this still an issue ?
