### ISSUE TITLE
Request: transmission checksum errors not only cosmetical (and RT delay capable)

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#230]
A science data set is sent in packages.
The full set is sent at once for each science result as usual.
But it stays in the transmission queue with a different color (colorblind-friendly and tooltip).
As soon as the ack comes back from HomeWorld (incl. RT delay), it will be deleted from the queue.
If a transmission error occurred (magnetic field of gas giant, CME or what ever), the wrong packets are requested for retransmission - and again the color of the queue entry has another different color (colorblind friendly and tooltip).
And again, the ack is waited for (RT).
This procedure continues as long as the full data set is not completely sent without crc errors.

The higher the distance - the nearer to the border of the antenna range - the higher the risk of crc errors.
Plus the already mentioned CME, magnetic field thing.

**Comment by SirMortimer** [comment]
The gameplay effect would be that the player has to wait longer until the transmission finishes, depending on environmental factors that deteriorate with increasing distance, which is very similar to what we have now with the **drastically** nerfed transmission rates in the new science system (ever tried transmitting from Eeloo in stock?)
Plus, implementing checksum error simulation would be quite an effort. Something similar could be done by varying the transmission rates depending on the environment, but IMO that's beyond what Kerbalism should do, at least for now, but it could be implemented by 3rd party mods.

Kerbalism now has an API function that allows 3rd party mods to implement their own communication thing. It's internally being used for RT, and at least one other mod is using it for realism overhaul.
