### ISSUE TITLE
Suggestion: middle-click "INFO" UI also should show signal readout

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#255]
Only the main UI shows the signal readout.

The extra UI which is opened by middle-clicking on "INFO" also should show it.

**Comment by HaullyGames** [comment]
Fixing it tomorrow

**Comment by gotmachine** [comment]
Is that fixed ? Should we close ?

**Comment by SirMortimer** [comment]
Yup. AFAIK basic signal info (bandwith, what's transmitting) is in the info tab.
