### ISSUE TITLE
Suggestion: clicking on the signal readout icon with the signal info tooltip should open UI window

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#256]
The UI window should show the whole connection chain (CommNet and RemoteTech), incl. all hops, their bitrates and their signal strenghts in a comprehensive list.

**Comment by HaullyGames** [comment]
How will it look when you have 30 vessels?

**Comment by Gordon-Dry** [comment]
Scrollbar!
