### ISSUE TITLE
The fps in Tracking Station are still lower with Kerbalism, but higher than with Kerbalism 1.5.1

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#27]
When I enable FPS Limiter mod - set to 32 fps - the fps drop down to 22.
When I disable, it's up to 60 (VSynced).

In Kerbalism 1.5.1 the fps drop in Tracking Station was really bad.

Perhaps the ContractConfigurator fix is the reason for the improvement.
https://github.com/steamp0rt/Kerbalism/issues/9

It doesn't matter if the sphere rendering is enabled or not.
Perhaps the fact that I use -force-glcore is the culprit?

And finally, I only have this large fps drop in Tracking Station when Kerbalism is installed.

**Comment by Gordon-Dry** [comment]
Using the private build of PiezPiedBy there is no change I could recognize - the transmission speed (upper limit) and signal loss issues still persist so this could be the reason.

**Comment by Gordon-Dry** [comment]
@steamp0rt because the silly game core just blows up to max. fps in SPC and utilizes the CPU and GPU for nothing and my rig becomes loud.

I always have to go to VAB to make it calm down.

With an fps limit to 32 it's way better, but still an issue.

**Comment by steamp0rt** [comment]
V-Sync would be a good balance between high fps and cpu-gpu usage, tho?

**Comment by Gordon-Dry** [comment]
Yes, but SPC is "special" regarding fan noise...

**Comment by HaullyGames** [comment]
@Gordon-Dry 
Please confirm the FPS dropping when you are using only Kerbalism with KSP, if you are based in the last GameData that you shared with me, when I played with that folder, my FPS dropped to 33 using your GameData with more than 180 mods, using my GameData with around 112 mods, my FPS stay around 120.

**Comment by Gordon-Dry** [comment]
@HaullyGames I will do - I'm also curious what is the issue.
Some months ago it was clearly Kerbalism, then it was better, then it became worse somehow.

And as it's impossible to check the CPU resources used by single mod dlls it's impossible to find the culprit quick.

**Comment by Gordon-Dry** [comment]
@HaullyGames Ok, I do it the hard way:
Adding one mod after another (incl. depedencies ofc)

But - because Unity/KSP is kinda weird - if the issue occurs after adding a specific mod does not implicitly mean that this mod is the culprit - it could™ be that it's another mod but the last one added just triggers the issue ...

**Comment by Gordon-Dry** [comment]
First finding - after I added the TriggerTech folder which contains
ARP - AlternateResourcePanel
KAC - KerbalAlarmClock
TWP - TransferWindowPlanner

the fps dropped down to 12 (from locked 60) ...

Now I try to find if it's one specific mod or just generally all from TriggerTech.

When I isolated that I try it with that problematic mod but without Kerbalism.

**Comment by Gordon-Dry** [comment]
So, it's KerbalAlarmClock ... but with only Kerbalism + dependencies + RemoteTech the issue is gone again.

I will test the KCT+ScrapYard+MonthlyBudgets suite next (it already was in my previous testing).

**Comment by Gordon-Dry** [comment]
^ah, not really "gone", the drop is "only" down to 32 fps which I did not recognize without FPSView mod ...

Next test is with KCT+ScrapYard+MonthlyBudgets to see if the change is significant or not.

**Comment by Gordon-Dry** [comment]
https://github.com/TriggerAu/KerbalAlarmClock/issues/207
