### ISSUE TITLE
Radiation belt warning on unloaded vessel - that is not crossing any radiation belt when loaded

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#273]
A station @ 300 km Kerbin orbit @ 45° inclination.

In focus I can follow it for days without any radiation belt warning.

When unloaded and in SPC I get regular warnings and the crew will die soon ...

**Comment by gotmachine** [comment]
Very likely related to a known issues with incoherent environment evaluation at high timewarp speeds / with unloaded vessels. Currently no ETA on a fix for that.
