### ISSUE TITLE
ModuleFuelTanks/RealFuels support

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#277]
May anybody please check this out, it's just basic support by patches. Code changes will be needed later:
https://github.com/Gordon-Dry/Kerbalism/tree/RealFuels-support

**Comment by Gordon-Dry** [comment]
Added patch for modularFuelTanks - the brother of RealFuels.

**Comment by SirMortimer** [comment]
I don't understand the issue. I guess real fuels is used in RO, which (optionally) uses Kerbalism, how is Kerbalism concerned by what liquid you happen to carry in your tanks?

**Comment by Gordon-Dry** [comment]
Especially because of the different modules RF/MFT uses for the tanks and the contents.

It's not just "other resources".

**Comment by SirMortimer** [comment]
Which modules? What do they do? What would be needed to be done to support them?

**Comment by Gordon-Dry** [comment]
In the part there is _ModuleFuelTanks_, which will have a _type_ like for example Cryogenic or LifeSupport or ServiceModule or whatever.

Also the switching of _type_ can be configured for parts.
So a tank can be a default fuel tank or a service tank.
Or a specific part can be a service module or a life support tank.

The _type_ and the contents of a type are defined in _TANK_DEFINITION_ like for example:
```
TANK_DEFINITION
{
	name = ServiceModule
	highlyPressurized = True
	basemass = 0.00003 * volume
	TANK
	{
		name = LqdOxygen
		mass = 0.000079
		utilization = 1
		fillable = True
		amount = 0.0
		maxAmount = 0.0
		temperature = 90.15
		wallThickness = 0.001
		wallConduction = 11.4
		insulationThickness = 0.05
		insulationConduction = 0.000017
		note = (has insulation, pressurized)
		boiloffProduct = Oxygen
		isDewar = true
	}
	TANK
	{
		name = Kerosene
		mass = 0.000077
		utilization = 1
		fillable = True
		amount = 0.0
		maxAmount = 0.0
		note = (pressurized)
	}
	TANK
	{
		name = LqdHydrogen
		mass = 0.000067
		utilization = 1
		fillable = True
		amount = 0.0
		maxAmount = 0.0
		temperature = 20.15
		wallThickness = 0.001
		wallConduction = 5.8
		insulationThickness = 0.05
		insulationConduction = 0.000017
		note = (has insulation, pressurized)
		boiloffProduct = Hydrogen
		isDewar = true
	}
 . . . etc.
}
```

**Comment by gotmachine** [comment]
Please explain what is the requested feature ?
Do you mean you want specific tank definitions for Kerbalism resources ?
Other than that, I don't think anybody will add support for a different switcher than our configure module for switchable ECLSS process/IRSU/etc.

**Comment by Tutul-** [comment]
I don't know if that was the original request but is it possible to generate realFuel from kerbalism process ? At least replace Oxidizer/Liquid Fuel with two from of RealFuel ?

**Comment by gotmachine** [comment]
Closing this, 4 years later I still have no idea what this issue is about.
