### ISSUE TITLE
Planner should recognize sickbays' EC consumption

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#278]
_SickbayRDU
_SickbayTV

both in Default.cfg

**Comment by PiezPiedPy** [comment]
@SirMortimer should be able to fix this, its pretty easy to add stuff into the planner

**Comment by gotmachine** [comment]
From what mods are they / what do they do ?

**Comment by lordcirth** [comment]
> From what mods are they / what do they do ?

They are part of Kerbalism... The Sickbay/RDU heals radiation and the TV heals stress.

**Comment by SirMortimer** [comment]
The planner does include it. You just need to turn it on in the VAB
