### ISSUE TITLE
Scrubbers on vessels built by EL don't work

### ISSUE THREAD

**Issue by Lach01298** [Kerbalism/Kerbalism#299]
If you build a vessel that has "Good" scrubbing capability in the planner, using Extra-planetary launch pads the scrubbers for some reason don't scrub enough and the CO2 level rises even thought there is enough scrubbers and there is electricity.

Version: v2.0.0 using KSP 1.5.1

**Comment by lordcirth** [comment]
Are the scrubbers on?  Do they consume electricity?  Do they scrub at all?  (Do they fill a CO2 tank?)

**Comment by Lach01298** [comment]
Did more testing: Scrubbers are "Running", They don't seem to be scrubbing at all, CO2 tanks don't get filled and electricity is not being used. This is also the same for the Humidity controller (i.e. it's "running", not using electricity and humidity is rising)

**Comment by lordcirth** [comment]
Thanks.  If you toggle them off and on again, do they work?

**Comment by Lach01298** [comment]
No they don't work. I can't get them to work even leaving the vessel or game doesn't fix it.

**Comment by madman2003** [comment]
A debug build of kerbalism can help to figure if the "pseudo resources" that enable the processes are actually present in the part, because it makes all resources visible.

**Comment by SirMortimer** [comment]
Don't think this is relevant any more. Please reopen if it is.
