### ISSUE TITLE
Near Future Electrical Reactor Control Panel Missing

### ISSUE THREAD

**Issue by shaman327** [Kerbalism/Kerbalism#305]
I'm not sure if this is a compatibility issue or not but it does affect the ability to control reactors in NFE.

**Version and Mod Info**
- KSP 1.6.1.2401  x64
- Module Manager 3.1.3
- Kerbalism 2.1.1
- Near Future Electrical 0.10.4
- B9 part switch 2.5.1  *required by NFE
- Community Resource Pack 1.0.0.0 *required by NFE
- Dynamic Battery Storage 1.3.3 *required by NFE

Method to reproduce:

1. Install fresh KSP 1.6.1.2401 and all the mods above minus Kerbalism
2. Run KSP then create a sandbox game all defaults
3. Build a new vessel consisting of Command Module and NFE fission Reactor.
4. Add Engineer to the crew (Just in case)
5. Launch vessel
6. You should see the icon in the toolbar for the NFE Reactor Control Panel. Open it and you should have full functionality.  (Start/Stop, set power output, etc)
7. Quit KSP.
8. Add Kerbalism 2.1.1 mod
9. Repeat steps 2 - 5.
10. The NFE Control Panel is no longer there and you can no longer manage the reactor except to start or stop it.

**Comment by the-emerald** [comment]
I have KSP v.1.4.5 and after updating Kerbalism from v1.8.0 to v.2.1.2 the issue occured.

**Comment by madman2003** [comment]
Kerbalism has its own resource simulator which is pretty much like a total conversion (vs a simple mod), so it strips near future electrical of most custom partmodules. And implements the reactors using kerbalism processes. The UI panel is probably tied into one of the partmodules being removed.

**Comment by steamp0rt** [comment]
pretty much what @madman2003 said

**Comment by the-emerald** [comment]
Something I've noticed is that the reactor is still "smart" enough to only generate the amount of energy the ship needs?

**Comment by PiezPiedPy** [comment]
That's something the processes do automatically, which is what the reactors run on, neat ay 😃
