### ISSUE TITLE
Suggestion: add exercise bike to other modules besides the hitchiker

### ISSUE THREAD

**Issue by aggie88** [Kerbalism/Kerbalism#308]
for example the hab or lab module from kpbs, stockalike station parts or some of the inflatable from pathfinder.

**Comment by SirMortimer** [comment]
I don't know any of those mods (well, besides stockalike). More specifically, I don't know the names of the parts that would need to be patched, which is the bulk of the work to get this done.

Currently the treadmill is added to:

* The hitchiker
* SXT SXTDLK83EHabitat
* Kerbalow KA330exterior
* SSPX sspx-habitation-375-1, sspx-habitation-375-2, sspx-habitation-375-3, sspx-inflatable-hab-25-1, sspx-inflatable-hab-25-2, sspx-inflatable-centrifuge-25-1, sspx-expandable-centrifuge-375-*

If you need more, please create a PR with the necessary config changes. The relevant files are in GameData/Kerbalism/Support, there you will find some examples to work from:

```
@PART[nameOfThePart]:NEEDS[NameOfTheMod,FeatureComfort]:AFTER[Kerbalism]
{
        MODULE:NEEDS[FeatureComfort]
        {
                name = Comfort
                desc = insert a witty description here
                bonus = exercise
        }

        MODULE:NEEDS[FeatureReliability]
        {
                name = Reliability
                type = Comfort
                title = Treadmill
                repair = Engineer
                mtbf = 36288000
                extra_cost = 0.25
                extra_mass = 0.05
        }
}
```
