### ISSUE TITLE
Science flagged as sample not available for ShipManifest science transfer

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#31]
I added a science return capsule to my probe, but I have no chance to get the sample into the capsule using ShipManifest, because ShipManifest does not "see" it.

Actually it's a total Kerbalism-internal sample, unavailable to stock or ShipManifest.

It's like there HAS TO be a manned mission that gathers the sample during EVA.

The probe got no Tarsier HardDrive, so I don't know if that would work correctly (it was quirky with 1.5.x).

I suggest to make it possible to transfer the sample to another part (return capsule) and send it back to Kerbin surface.

**Comment by SirMortimer** [comment]
This is probably the same issue as #249, which now can be solved by setting `dataIsCollectable = false` on the experiment.
