### ISSUE TITLE
SSTU (and all custom) solar panel compability

### ISSUE THREAD

**Issue by assassinacc** [Kerbalism/Kerbalism#310]
I noticed kerbalism isn't recognizing the SSTU solar panels as solar panels. They produce EC just fine, when the craft is loaded, but background simulation and editor planner don't seem to get the data needed to calculate these things.
Some digging revealed to me that SSTU isn't using the stock solar panel part module and using following MM-patch (which adds the kerbalism reliability part module) doesn't seem enough to make kerbalism recognize them as solar panels
```
@PART[*]:HAS[@MODULE[SSTUSolarPanelDeployable]]:NEEDS[Kerbalism,SSTU]:AFTER[SSTU]
{
	MODULE
	{
		name = Reliability
		type = ModuleCurvedSolarPanel
		title = Solar Panel
		redundancy = Power Generation
		repair = true
		mtbf = 36288000
		extra_cost = 2.5
		extra_mass = 1.0
	}
}
```
At this point I realized this problem can't be solved by a simple MM-patch and rather needs support by the kerbalism plugin. 
My idea would be to add a dummy part module where you can specify parameters (like it's done in the stock solar panel part module), so kerbalism can handle it. This would not only allow compability for SSTU but for all mods with solar panel which don't use the stock part module.

If anything more is needed to help to solve this issue, just let me know.

**Comment by Milkywegian** [comment]
I've been looking over cfgs for a week to fix this but couldn't.

**Comment by Milkywegian** [comment]
Maybe try to patch it the way gotmachine patched MOLE solar panels.

**Comment by assassinacc** [comment]
I don't think it will work that way for SSTU. Even if it works, you'd need to find out the pivot name of each part. And there are a lot of parts with inbuilt solar panels. As far as I know the stock part module doesn't support this all-in-one solutions. I guess that's why SSTU uses custom part modules for their solar panels.
I'd rather like to see support from Kerbalism for custom solar panel part modules than "ugly" and time consuming hacks for each mod with custom panels.

**Comment by UsernamesAreAlwaysTaken** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/117090-wip16x-sstulabs-low-part-count-solutions-orbiters-landers-lifters-dev-thread-11-18-18/&do=findComment&comment=3561283

My attempt at patching SSTU. there's some loss of functionality, go through the readme.
I'll probably revisit them at a later date.

**Comment by SirMortimer** [comment]
Sorry to be the bearer of bad news, but SSTU support probably won't happen. Ever.

**Comment by gotmachine** [comment]
This is being worked on, see f6fa275f3ae966069c8f5016445e7b9bb9355724
