### ISSUE TITLE
Oxygen not Consumed nor Calculated in Planner

### ISSUE THREAD

**Issue by pap1723** [Kerbalism/Kerbalism#312]
Hello, I am running version 2.1.1 on KSP v 1.3.1 and the Oxygen Rules are not working. There is no oxygen consumed by the Kerbals and in the Planner in the Editor, it shows no oxygen will be consumed.

The same version works fine on 1.4.5. I know 1.3.1 is very old, but this is something I am working on for the Realism Overhaul configs.

Thanks!

**Comment by PiezPiedPy** [comment]
Have you tried the latest dev build, I'm sure this has been fixed with PR #304

**Comment by SirMortimer** [comment]
Probably long fixed.
