### ISSUE TITLE
Fix EC rate in planner vs actual vessel

### ISSUE THREAD

**Issue by syscryp** [Kerbalism/Kerbalism#313]
I'm using the latest dev build. The rate of EC consumption is much higher on active vessels than predicted by the planner in the VAB. 

Unfortunately, the in-flight GUI doesn't provide a breakdown of where the consumption is coming from, so I can't see if it's a particular part. 

Can others replicate?

**Comment by PiezPiedPy** [comment]
That's usually caused by a mod conflict, main suspects are the antennas and pods. If I ever get the time I might update the monitor to show the extra details if its possible.

**Comment by steamp0rt** [comment]
Are you using Module Manager 4.x? If so, downgrade to 3.x.

**Comment by syscryp** [comment]
I was using MM 3.1.3 at the time. I've now upgraded to Kerbalism 2.1.2 and the latest MM. Same problem.

I first encountered the problem with a vessel using a BDB Leo/Gemini pod. I tested it with a stock Mk1 pod as well, same problem. 

The total EC consumption seems to be roughly double what the Planner predicts it should be - but only when there is a Kerbal in the pod. 

I suspect it might be to do with the climatisation process, for two reasons. First, because the problem only arises when there is a kerbal in the pod, and second because climatisation is the only thing I can't turn off using the Kerbalism in-flight UI.

**Comment by PiezPiedPy** [comment]
@HaullyGames or @Gordon-Dry seem to be the most knowledgeable regarding BlueDog support, I'm pretty sure Gordon was also having high EC usage problems but cant remember if he solved the problem.

**Comment by PiezPiedPy** [comment]
@syscryp In case you don't know the support file for Bluedog is in the GameData/Kerbalism/Support/Bluedog.cfg file

**Comment by syscryp** [comment]
Thanks, but like I said, I'm also getting this on stock parts, so I don't believe it's a compatibility issue with BDB.

**Comment by HaullyGames** [comment]
I will review it!
Could you give me a vessel template?
Such as a small mod list + vessel description with small part list.

Note: One problem that I know is related to solar panel, when you load it you have the real amount of EC based on light received for each panel, unloaded vessel most time generates more EC because don't check it, not sure if it is related to my code or it is by KSP design.

Could you confirm if that it is not the case?

**Comment by syscryp** [comment]
Hi. I'm afraid it's nothing to do with solar panels, BDB, MM versions or, VSR. I've eliminated all of them. It happens on all crewed pods, but not consistently. Even a stock Mk1 pod with no other parts and hacked into orbit will show the same bug - just not all the time. 

Weirdly, it only happens on some savegames and not others, then after a while it creeps into unaffected savegames too. I'm very reluctant to remove all my mods to test this further myself, because it only appears in a developed game and I don't want to break my saves.

Here are some observations though:
- The bugged consumption rate always seems to be exactly double or triple the what the consumption should be, as if Kerbalism is double or triple-couting the ECLSS modules. Sometimes switching ECLSS processes on and off makes some difference to the consumption rate, but other times it doesn't make any difference at all. When it does make a difference, it's only counted once, as if there is a copy running in the background that I can't control. Other resource consumption rates seem to work as expected.

For example: if the the planner says consumption for a vessel should be 77EC/s, it's actually 151EC/s in flight, which is almost exactly twice what it should be. I've seen it almost exactly three times, too. (I think the slight difference from exact factors is accounted for by non-Kerbalism things like antennas).

If I load an existing save with crewed ships in flight, the consumption is as expected, until I load the vessel. Then the bug kicks in and consumption doubles or triples. When I then unload the vessel and go back to KSC, the UI still shows the bugged consumption rate. Even if I go back to the main menu and load the savegame again, the bugged rate is still there, even on an unloaded vessel. The only way to return it to normal is to close and reopen KSP entirely.

Based on everything I've observed, my guess is that Kerbalism (or something else) is creating a sort of copy of the vessel at the point it is loaded.

I really hope you can identify and fix this bug. It's driving me mad, and I'd be most grateful.

`KSP: 1.6.1 (Win64) - Unity: 2017.1.3p1 - OS: Windows 10  (10.0.0) 64bit
ClickThroughBlocker - 0.1.6.10
KSP API Extensions /L - 2.1.0.8
Toolbar - 1.7.17.15
ToolbarControl - 0.1.6.20
ABCors - 0.5.0.4
AlmostFreeLaunchClamps - 0.2.2
Airplane Plus - 25.0
B9 Animation Modules - 1.3.2
B9 Part Switch - 2.5
B9 Aerospace Procedural Parts - 0.50
BAM - 1.3.2.5
Bluedog Design Bureau - 1.5.1
Bon Voyage - 0.14.3
CameraTools - 1.11
Chatterer Extended - 0.6.2
Chatterer - 0.9.96.2332
Community Category Kit - 4.1
Community Resource Pack - 1.1
CommunityTechTree - 3.3.6
Connected Living Space - 1.2.6.2
Contract Configurator - 1.27.1
Contract Pack: Anomaly Surveyor - 1.7.1
Contract Pack: Field Research - 1.2.1
Contract Pack: RemoteTech - 2.1.4
Contract Pack: Tourism Plus - 1.5.2
CrewRandR - 1.1.9.1
Community Terrain Texture Pack - 1.0.4
CustomBarnKit - 1.1.19
DangIt - 0.7.18.2
DecouplerShroud - 0.6.1
DescentMode - 0.2.2
DistantObjectEnhancement - 1.9.1
DMagic Orbital Science - 1.4.2
CapCom Mission Control On The Go - 1.0.2.10
Contract Parser - 1.0.8
Progress Parser - 1.0.10
EarnYourStripes - 2.0
EditorExtensionsRedux - 3.3.19.10
EngineIgnitor - 1.3.4.1
Environmental Visual Enhancements - 1.4.2.2
FASA Launch Clamps - 1.1.4
Ferram Aerospace Research - 0.15.9.6
Firespitter - 7.11
FlightTracker - 1.0
FMRS (Flight Manager For Reusable Stages) - 1.2.7.4
HideEmptyTechTreeNodes - 1.1
HullcamVDSContinued - 0.1.10.2
ImprovedChaseCamera - 1.6.2.1
JanitorsCloset - 0.3.4.6
RasterPropMonitor - 0.30.6
KAS - 1.1.6876.38030
KerbalChangelog - 1.1.4
Kerbal Engineer Redux - 1.1.5.7
Kerbal Flight Indicators - 17.0
Kerbal Foundries - 2.2.6.16
Kerbalism - 2.1.2
Kerbal Joint Reinforcement /L - 3.4.0.4
KerbalLaunchFailure - 0.4.10.3
InlineBallutes - 1.2.9.7
Kerbal Inventory System - 1.18.6971.42939
<b><color=#CA7B3C>Kopernicus</color></b> - 1.6.1.1
KRASH - 0.5.29.7
<b><color=#9B59B6>Kronometer</color></b> - 1.3.1.2
AdvancedFlyByWire - 1.8.1.3
KSP-AVC Plugin - 1.2.0.7
KSPWheel - 0.12.10.28
Landing Height - 2.2.0.5
MagiCore - 1.3.1.4
MandatoryRCS - 1.5
MandatoryRCS Part Pack - 1.1
ModularFlightIntegrator - 1.2.6
NASA_CountDown - 1.3.7.5
Docking Port Alignment Indicator - 6.8.2
NearFutureConstruction - 1.0.6
NearFutureProps - 0.5
NearFutureSpacecraft - 1.0.3
Final Frontier - 1.5.3.3465
Notes - 0.14.2.1
NRAP - 1.5.13
OuterPlanetsMod - 2.2.2
PartCommanderContinued - 1.1.5.2
PartWizardContinued - 1.3.7.6
PEBKAC Launch Escape - 1.4.1
PlanetShine - 0.2.6.1
Precise Maneuver - 2.4.1
Procedural Fairings - 1.5.0.5
Procedural Parts - 1.3.16.1
QuickBrake - 1.3.4.1
QuickExit - 2.1.4.1
QuickSAS - 1.1.4.1
QuickSearch - 3.2.3
RCS Build Aid - 0.9.7.4
RealBattery - 0.1.4.1
RealChute - 1.4.7.2
RealPlume - Stock - 1.3.1
Recovery Controller - 0.0.3.7
ReentryParticleEffect - 1.4
RemoteTech - 1.9.1
SafeChute - 2.1.16
SCANsat - 1.1.8.10
ScrapYard - 1.1.1
SETI-CareerChallenge - 1.3
SETI-Contracts - 1.3
SETI-CustomBarnKitConfig - 0.9.1
SETI-ProbeParts - 1.3.0.2
SETI-Rebalance - 1.3.0.2
SETI-RemoteTechConfig - 1.3.0.1
Ship Effects Continued - 1.0.8.4
SmartParts - 1.9.13.4
StageRecovery - 1.9.1
Stock Visual Enhancements - 1.3.0.4
Strategia - 1.7.3
TankLock - 0.2.5.4
ThrottleLimitExtended - 2.0.7.2
ThroughTheEyes - 2.0.2.4
Tracking Station Evolved - 1.0.4.1
Trajectories - 2.2
Kerbal Alarm Clock - 3.10
Transfer Window Planner - 1.6.3
TrimIndicator - 1.6
TweakScale - 2.4.1
Universal Storage 2 - 1.5.1.9
Unmanned before Manned - 1.3.0.2
Unmanned before Manned - Challenge - 1.3
EVAParachutesAndEjectionSeats - 0.1.16
Waypoint Manager - 2.7.5
OrbitalDecay - 1.6.1.1
SolarCycleSimulator - 1.1.0.1
World Stabilizer - 0.9.3`

**Comment by PiezPiedPy** [comment]
It could be any one of the mods you have installed causing the issue, I recommend reading this https://github.com/steamp0rt/Kerbalism/blob/master/CONTRIBUTING.md#removing-mods-for-debugging

**Comment by syscryp** [comment]
Ok, Tried that. 

I removed every single mod, validated the KSP installation (so it's just KSP 1.6.1 and Making History). Loaded the bugged save, hacked a Mk1 pod into orbit: no EC consumption at all (as expected). So it's not something inherent to my installation of KSP.

- Downloaded fresh copies of Kerbalism, MM 4.0.2 and Community Resource Pack, Loaded a copy of the same bugged save, and hacked a Mk1 pod into orbit again. The phantom EC consumption problem is still there: Planner predicted .52 EC/s in the sun in LKO with scrubber, pressure control and air pump running. Actual figure was .80 to .82 EC/s in the sun (or 0.56 if I switch off scrubber, pressure control and air pump). So it's almost certainly something with Kerbalism, but it's not a mod conflict. 

- Created a new sandbox game, and did the same again with a Mk1 pod: no problem, functioning as expected. So it seems to be linked to particular savegames.

Another thought - could some of the ECLSS modules be running at full power all the time, instead of partial use when needed?

**Comment by syscryp** [comment]
[output_log.zip](https://github.com/steamp0rt/Kerbalism/files/2898065/output_log.zip)

**Comment by syscryp** [comment]
Ignore my point about the bug appearing on some saves. It's inconsistent, but it seems to apply in all conditions.

**Comment by PiezPiedPy** [comment]
If the savefile is bugged there is nothing we can do about it, you could try editing the save file though.

You have to use new vessels to check for bugs, otherwise old bugs that have been fixed might still seem to exist because the values the old bugs created and saved in a saved craft or a savefile can be re-loaded and make it appear like the bug still exists.

**Comment by syscryp** [comment]
Yes, If you look at my last comment, I said I was wrong: it's happening on all save files, just not consistently.

And yes, I've been using new vessels. Like I said, I've been hacking naked Mk1 pods into orbit using Set Orbit.  I've been using a new pod every time I change something.

I'm not imagining this. _Please_ can you take a look at the outlook_log?

**Comment by PiezPiedPy** [comment]
I've noticed the pods you have checked are the new versions, I'll take a look as I did notice habitats where missing from those pods, that issue has been fixed for the next release. You could try the dev build but I doubt it will fix your issue. https://builds.steamport.xyz/Kerbalism-2.2.0-BUILD422.zip

**Comment by PiezPiedPy** [comment]
I've looked into this and can not replicate your issue. Have you set your orbit height to the correct value and then check if your numbers match, The Orbit set by default with the debug menu is the equivalent of Low Orbit on the Planner.

![screenshot0](https://user-images.githubusercontent.com/17555434/53309232-a07c4e00-389e-11e9-93dd-a9300266ec14.png)
![screenshot1](https://user-images.githubusercontent.com/17555434/53309243-b5f17800-389e-11e9-926c-18054f105e99.png)

Even after a few saves and loads, no change 🤷‍♂️ 
![screenshot2](https://user-images.githubusercontent.com/17555434/53309266-d8839100-389e-11e9-9613-16ddc934950f.png)

**Comment by PiezPiedPy** [comment]
> Created a new sandbox game, and did the same again with a Mk1 pod: no problem, functioning as expected. So it seems to be linked to particular savegames.

This shows Kerbalism is fine, its the effected savegames that are bugged.

**Comment by PiezPiedPy** [comment]
Try giving your cache a clean by running this in your KSP root
[CleanMM.zip](https://github.com/steamp0rt/Kerbalism/files/2898717/CleanMM.zip)

**Comment by SirMortimer** [comment]
Can reproduce:

Naked Mk1 pod, 1 crew inside.
Launch it and hack it into orbit (default orbit height): usage is 0.045/s
Return to space center: usage is 0.045/s
Go back to the pod: usage is 0.107/s.

It seems that the EC consumption rate is simulated twice.

**Comment by SirMortimer** [comment]
I cannot reproduce it on my main computer, which is a bit faster.

**Comment by SirMortimer** [comment]
This is a tricky one to reproduce, but I think I managed to do so while there was some debug logging in the code. It looks like the process execution is done twice. This was logged in Profile.Execute(), and there was only one vessel in the save game.

Look at the time stamps of the log, and look at elapsed_s. It doesn't add up.

`[LOG 08:23:35.563] [Kerbalism]  -> verbose: Profile.Execute - Executing for mk1pod.v2 elapsed_s 0.0199999995529652
[LOG 08:23:35.644] [Kerbalism]  -> verbose: Profile.Execute - Executing for mk1pod.v2 elapsed_s 0.0199999995529652
[LOG 08:23:35.646] [Kerbalism]  -> verbose: Profile.Execute - Executing for mk1pod.v2 elapsed_s 0.0199999995529652
[LOG 08:23:35.694] [Kerbalism]  -> verbose: Profile.Execute - Executing for mk1pod.v2 elapsed_s 0.0199999995529652
[LOG 08:23:35.697] [Kerbalism]  -> verbose: Profile.Execute - Executing for mk1pod.v2 elapsed_s 0.0199999995529652`

**Comment by syscryp** [comment]
Great! I'm glad you've figured it out. So is this fixed in the latest build?

**Comment by SirMortimer** [comment]
I don’t know tbh. If you’re on KSP 1.6 I can give you a new Kerbalism16.bin, would be very interesting to see if you still can reproduce it. Could you drop into discord?

**Comment by SirMortimer** [comment]
Tests confirmed the issue is not fixed. We'll do a test again once #356 is done, OK?

**Comment by SirMortimer** [comment]
@syscryp check in discord, please

**Comment by SirMortimer** [comment]
@syscryp pinged you in discord with another experiment to pin down the issue

**Comment by SirMortimer** [comment]
@syscryp I never saw this issue since, so I think it's fixed although I'm not 100% certain why and where. If you still see this happening, please reopen this issue or create a new one.
