### ISSUE TITLE
Nuclear reactors stop working on vessel unload & game load

### ISSUE THREAD

**Issue by the-emerald** [Kerbalism/Kerbalism#325]
The latter is reproducible every time, but sometimes when the vessel is unloaded nuclear reactors will suddenly stop working. Very annoying for ships that rely on nuclear power (limits my ability to timewarp)

**Comment by PiezPiedPy** [comment]
are you using the dev version ?

**Comment by the-emerald** [comment]
Yes

**Comment by PiezPiedPy** [comment]
k, I'll check it but not today, i'm fkd

**Comment by SirMortimer** [comment]
Is this still an issue with 3.0?

**Comment by gotmachine** [comment]
Closing this, see #461 for updates on NFE support
