### ISSUE TITLE
Console being spammed with errors which puts a large load on CPU and causes unbearable stutters.

### ISSUE THREAD

**Issue by Pepethecat** [Kerbalism/Kerbalism#326]
This bug could be caused by some of my other mods but im not sure. But it is really really causing issues for me in the VAB because it is literally spamming my console with errors and shit which literally uses so much of my CPU that my game stutters.
https://cdn.discordapp.com/attachments/457286501470961686/548608117932425226/unknown.png

Here is my Log.

[KSP.log](https://github.com/steamp0rt/Kerbalism/files/2907474/KSP.log)

Edit; when I remove the mod the issues go away entirely which is why I suspect it is this mod.
By installing https://forum.kerbalspaceprogram.com/index.php?/topic/106089-16x-cryogenic-engines-high-isp-chemical-rockets-january-21/ and deleting whatever dependencies came with cryoengines that I already had installed and replacing them with the ones that were packaged with the mod seemed to have fixed the issue. which is weird. Even then there is still stuttering suggesting that it wasn't the mod's fault. But I'm going to keep this up since it could still cause other errors that I haven't discovered. Here is my log after installing cryoengines.

[KSP.log](https://github.com/steamp0rt/Kerbalism/files/2907572/KSP.log)

**Comment by PiezPiedPy** [comment]
Nothing weird about having the correct versions of dependencies installed 😛 
The stuttering in the VAB/SPH is being investigated. see PR #323

**Comment by steamp0rt** [comment]
#323 is merged. Status on this issue?

**Comment by SirMortimer** [comment]
Closing this. Please reopen if still a problem.
