### ISSUE TITLE
Dump valve settings are ineffective until vessel was loaded once

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#337]
Dump valve settings (persisted in valve_i) are without effect until the vessel is loaded.

**Comment by PiezPiedPy** [comment]
parsing all the vessels when Kerbalism starts at Gamesave load to set toggles and configs etc for the vessel cache should fix this problem and maybe some other related problems with the processes.

**Comment by SirMortimer** [comment]
It’s not that easy I’m afraid. Kerbalism runs many processes only once per vessel, without a relation to the parts (if any!) they run in. The only thing that controls if a process runs or not is the amount of pseudo resources available for that process (this was broken in automation). Shit hits the fan when there are >1 parts with the same process and conflicting dump valve settings

**Comment by PiezPiedPy** [comment]
ahh I see, so maybe we can make the dump valve settings global, so changing a valve on one part changes the valve settings on all the other parts that have the same process. Might be problems with vessels docking and conflicting valve settings, maybe just use a first part loaded sets all basis.

**Comment by theJesuit** [comment]
Perhaps we could set a priority one? If that is set at say a station then anything docked operates as station.  When vessels undocking they revert to their own.  But keep first loaded if there is no set priority one.

**Comment by gotmachine** [comment]
Is that fixed ?

**Comment by SirMortimer** [comment]
no.

**Comment by gotmachine** [comment]
fixed by https://github.com/Kerbalism/Kerbalism/commit/d6400a0c3cf8d3db028bdf45f6dfb19f7bf6d3e8
