### ISSUE TITLE
Help Needed: does anyone know a mod that changes a Kerbals CV?

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#372]
When lifetime radaiation is on, it would be immensely useful to display the career radiation a Kerbal had been exposed to somewhere in the astronaut complex, or on the CV that is displayed when your mouse hovers over a Kerbal (see screenshots). But I have no Idea how to do that.

Does anyone know a way to change the text in there? Does anyone know a mod that already does that?

![screenshot0](https://user-images.githubusercontent.com/43166475/55619755-ab79a680-5799-11e9-9c4d-4e96d780818d.png)
![screenshot1](https://user-images.githubusercontent.com/43166475/55619756-ab79a680-5799-11e9-943c-481df9634275.png)

**Comment by Standecco** [comment]
I recall USI was doing it too, but I'm 100% sure GPP does it too. In fact, I have looked at the configs and it's exactly what it does: add information about kerbals, although not dynamic. It does so through Sigma Replacements, proabably with the description module.

**Comment by SirMortimer** [comment]
closed for now, this will be for a later version.
