### ISSUE TITLE
Kerbalism and Telemachus reborn antenna power use

### ISSUE THREAD

**Issue by tomimas** [Kerbalism/Kerbalism#373]
KSP 1.6.1
Kerbalism: 1.2.1
Telemachus 1.6.22.F2 (https://github.com/TeleIO/Telemachus-1)

I don't know if this is an issue or a feature, but the power use of antennas is rather hefty, when these two mods are combined. Part says 1.8/min, but Kerbalism says 12.020/s. Everything is fine when only either one is installed.

[Just OKTO with Kerbalism and Telemachus](https://suuronen.eu/blog/wp-content/uploads/2019/04/kerbalism_and_telemachus-1.png)

[Just OKTO with Kerbalism](https://suuronen.eu/blog/wp-content/uploads/2019/04/kerbalism.png)
Note, that those two numbers does not match: 1.2/min and 0.032/s should be 1.92/min

Telemachus uses some sort of antenna bitRate (factor of per thousands) to calculate it's power need. Does Kerbalism use same sort of technique? Because, simply adding a single HG-5 Relay Antenna to the OKTO causes the power use to be over 50/s. So double multiplication is happening somewhere. I have no clue, what can and cannot be done with mods. Could it be possible to introduce somewhere that if Telemachus is installed use only Kerbalism power use calculations?

I did contact the the other modder also, as I would like to see these two awesome mods to be able to work together, and now are not.

**Comment by SirMortimer** [comment]
I won't look at this until they fix the zip file. https://github.com/TeleIO/Telemachus-1/issues/12

**Comment by SirMortimer** [comment]
![screenshot2](https://user-images.githubusercontent.com/43166475/71189903-dce0c680-2283-11ea-9849-668ad5d11244.png)

Screenshot was taken with the current version of Kerbalism, I think the issue has been resolved since 3.1.
