### ISSUE TITLE
Tweakscaled EC-generating parts have wrong output

### ISSUE THREAD

**Issue by ghost** [Kerbalism/Kerbalism#386]
Planner shows the EC output rate for the non-tweakscaled part, rather than it's actual value.

**Comment by gotmachine** [comment]
What tweakscaled parts ? Can you be more specific ?
I don't think Kerbalism does support tweakscale, and it certainly don't support parts that generate EC not using it's own processes.

**Comment by UsernamesAreAlwaysTaken** [comment]
It's a planner issue.
Tweakscaled parts work as intended, via patches. The planner doesn;t update based on the resized part though, it displays ec consumptions of default size parts.

I'd assume the same is accurate for resized habitat surfaces/volumes, and anything that the planner calculates tbh.

**Comment by gotmachine** [comment]
See https://github.com/Kerbalism/Kerbalism/issues/709
