### ISSUE TITLE
SSTU habitats not working

### ISSUE THREAD

**Issue by Tonas1997** [Kerbalism/Kerbalism#387]
There seems to be a problem with SSTU's command modules: their habitats can't be enabled on the editor, since the tooltip gets stuck on the "pressurizing..." state.

![screenshot0](https://user-images.githubusercontent.com/43859708/57961981-c6981400-790a-11e9-8fb0-eb4197c36a96.png)

This is obviously a bit inconvenient, since there's no way of getting accurate volume/surface values from the Kerbalism readouts.

**Comment by UsernamesAreAlwaysTaken** [comment]
SSTU needs custom patches, due to mod conflict. SSTUVolumeContainer prevents Kerbalism Habitats from working alltogether. It's a known issue.

If you have some MM Fu, i can give you a set of patches, but they need fixing. I'm currently busy with something else, thus this is not really a priority for me right now. Feel free to fix them yourself.

**Comment by Tonas1997** [comment]
Would it be simply a matter of disabling SSTUVolumeContainer modules? I reckon that alone wouldn't cause any nasty side effects, since MFT works the same way (and it is already implemented on SSTU aprts anyways).

**Comment by UsernamesAreAlwaysTaken** [comment]
That breaks the resource containers. You lose the ability to hold fuel and any other resources, but those can be added manually later, and the fuel switching can be implemented through B9 or through Kerbalism's own Configure.

The killer is the loss of adaptive resource amounts based on the variable part model, that cannot be simulated properly. More specifically, the resource stays the same wether you have a 1.25m short tank or a 10m 9 core tank.

**Comment by Tonas1997** [comment]
So the patches you're developing will allow for a seamless integration between both mods, or are there any intrinsic limitations?

**Comment by UsernamesAreAlwaysTaken** [comment]
``` seamless```
Lol no.

**Comment by Tonas1997** [comment]
Ok, so I guess it is hopeless, then 😐 

To be honest, I hadn't even realized SSTU's pods had part variations... I was used to playing with that mod on 1.3.1 and it integrated with Kerbalism quite well back then; personally, I would be happy to sacrifice adaptative resources and Kerbalism configs for every part variation **if** that meant I could use the pods on their default states. 

As for the pods with resources... I could manage with separate tanks to compensate or something like that.

**Comment by UsernamesAreAlwaysTaken** [comment]
there is a set of patches but they're semi-broken. i have to have another go at them, but as i said, before, i have slightly more important stuff to take care of right now.

**Comment by SirMortimer** [comment]
Sorry to be the bearer of bad news, but SSTU support probably won't happen. Ever.

**Comment by UsernamesAreAlwaysTaken** [comment]
`Sorry to be the bearer of bad news, but SSTU support probably won't happen. Ever.`
that didn't age very well.

**Comment by gotmachine** [comment]
Well it sis say "probably". And support will be possible because of changes on the SSTU side, that will only work in the new SSTU update.
