### ISSUE TITLE
Non-6hour day support

### ISSUE THREAD

**Issue by Darkherring** [Kerbalism/Kerbalism#392]
Planner and monitor are showing inconsistent behaviour in 3.0. previously, in 2.1.2 it all used 6h day so it was consistent, but right now, planner uses 6h day, monitor in KSC also, bit the one in flight uses, in my case, 9h day.
It's getting really distracting.

**Comment by SirMortimer** [comment]
I think that's fixed, at least in the current development version. Reopen if not.
