### ISSUE TITLE
Resource display named resource

### ISSUE THREAD

**Issue by theJesuit** [Kerbalism/Kerbalism#396]
I just noticed that CRP have a localisation string for the display names of their resources.
In the right click on capsules or tanks show displayName, but kerbalism only uses the name of resources.

RESOURCE_DEFINITION
{
    name = Nitrogen
	displayName = #LOC_CRP_Nitrogen_DisplayName

Could kerbalism be altered to use the displayName please.

This would also benefit potential CRP localisation.

**Comment by SirMortimer** [comment]
Should be done.
