### ISSUE TITLE
Configs could be in separate base folder?

### ISSUE THREAD

**Issue by theJesuit** [Kerbalism/Kerbalism#398]
Just thinking about manual vs. CKAN installs with the 'default', RO installs, SIMPLEX etc...

Maybe the configs could be in a separate folder.  This would mean people who like to tweak their own, or install different ones don't accidentally delete when the base gets updated.

so GameData/Kerbalism  // this is to keep the current mods that support kerbalism happy
and GameData/KerbalismStandard // this is would be the default profile the Core download.

Have profile author's release their  configs in folders like the RO config being in GameData/KerbalismRO, and Simplex config GameData/KerbalismSimplex

Then have mods that support kerbalism transition from Kerbalism to KerbalismStandard if appropriate - as so many don't support via profileDefault

**Comment by SirMortimer** [comment]
If you do it like this, people who install >1 different configuration sets (and there will be some) will end up with 2 configurations.

Alternative:
```
GameData/Kerbalism ← Kerbalism Core
GameData/KerbalismConfig ← either RO, or default config, or custom configs
```

**Comment by SirMortimer** [comment]
Commit https://github.com/Kerbalism/Kerbalism/commit/1ef072aa6173caf6c8832584d95c4c48ea703cc3 should take care of this.

Note that this also requires an update of the CKAN configs.

**Comment by theJesuit** [comment]
You Sir, are a gentleman.

**Comment by theJesuit** [comment]
However easier to diagnose the issue if user has both gamedata/KerbalismDefault AND gamedata/KerbalismRO

**Comment by theJesuit** [comment]
I believe that this has been done in Beta 2
