### ISSUE TITLE
Experiment : add a ground contact check

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#401]
<a href="https://github.com/SirMortimer"><img src="https://avatars2.githubusercontent.com/u/43166475?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SirMortimer](https://github.com/SirMortimer)**
_Wednesday Apr 03, 2019 at 23:12 GMT_
_Originally opened as https://github.com/SirMortimer/Kerbalism/issues/22_

----

(currently, a DMOS drill will collect a sample even if it's not touching the ground). this will be a pain, but you can check DMOS MODULES: DMBioDrill, DMXRayDiffract for example for ideas.

**Comment by SirMortimer** [comment]
<a href="https://github.com/SirMortimer"><img src="https://avatars2.githubusercontent.com/u/43166475?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SirMortimer](https://github.com/SirMortimer)**
_Tuesday Apr 30, 2019 at 06:21 GMT_

----

Problem is:

1. Terrain height data is only available for loaded vessels
2. Position of a part on a vessel is only available for loaded vessels

So there needs to be a cached value for "this has ground contact" which then will be used in background sims.

**Comment by SirMortimer** [comment]
<a href="https://github.com/SirMortimer"><img src="https://avatars2.githubusercontent.com/u/43166475?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SirMortimer](https://github.com/SirMortimer)**
_Tuesday Apr 30, 2019 at 06:27 GMT_

----

Thinking of it, is a surface drill really something that takes a very long time to collect a sample? I would be perfectly happy with surface drills providing instant science via the stock experiment dialog. In other words: leave them as they are.

Besides, it's even more complicated than it looks at a first glance. I need to find out how much height above ground is acceptable for a drill (long vs. short drills)

**Comment by gotmachine** [comment]
Reverted the various DMOS drills to their original module in https://github.com/Kerbalism/Kerbalism/commit/e935ca641bb213df58d3c0735331f89031417197, so this isn't needed anymore.
