### ISSUE TITLE
Experiment anomaly-related requirements

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#405]
<a href="https://github.com/UsernamesAreAlwaysTaken"><img src="https://avatars3.githubusercontent.com/u/48958828?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [UsernamesAreAlwaysTaken](https://github.com/UsernamesAreAlwaysTaken)**
_Monday Apr 22, 2019 at 22:30 GMT_
_Originally opened as https://github.com/SirMortimer/Kerbalism/issues/52_

----

IF. Big, massive, humongous, ridiculous IF you have the will and time, ^.

If not, no big loss.

Not a priority or something you actively have to do by any stretch of imagination.

**Comment by SirMortimer** [comment]
<a href="https://github.com/UsernamesAreAlwaysTaken"><img src="https://avatars3.githubusercontent.com/u/48958828?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [UsernamesAreAlwaysTaken](https://github.com/UsernamesAreAlwaysTaken)**
_Monday Apr 22, 2019 at 22:41 GMT_

----

^ see the if statement there. could be done similar to current asteroid check: MaxAnomalyDistance. this would solve the problem instantly

**Comment by gotmachine** [comment]
I guess this was for DMOS support, solved by reverting to the DMOS module in https://github.com/Kerbalism/Kerbalism/commit/e935ca641bb213df58d3c0735331f89031417197. Don't reinvent the wheel.
