### ISSUE TITLE
Animation handling of parts with multiple experiments

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#410]
<a href="https://github.com/UsernamesAreAlwaysTaken"><img src="https://avatars3.githubusercontent.com/u/48958828?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [UsernamesAreAlwaysTaken](https://github.com/UsernamesAreAlwaysTaken)**
_Monday May 06, 2019 at 02:45 GMT_
_Originally opened as https://github.com/SirMortimer/Kerbalism/issues/73_

----

As it currently stands, if the part has 2+ experiments on it (there's a few, modded parts mostly), each experiment either uses the same animation, or only the first one has one.

This causes 2 issues, depending on approach: 
For 1: every time you start an experiment, it plays the animation. Not a big deal, i can live with it, but this is shiny territory, and people certainly love shiny. E.G: start experiment 1, animation plays. Start experiment 2: the animation plays again, without reversing the initial state. It's a bit wonky and janky, but again, not that critical. Eye candy.

For 2: Animation plays once for the first experiments, other experiments don't have animations, which means they can run while not deployed. This again is not really gamebreaking, but see above: Eye candy.

Proposed sollution: New module that handles all the animation related shit for experiments. Experiments themselves would have to check the deployed/not deployed state (similar fashion to ModuleAnimateGeneric - stock). Let experiments trigger the animation in that module, and if already deployed, do nothing. For retracting, check if any other experiment is running that uses the same animation, if none - retract, if there's still active experiments on that part with the same animation - do nothing. No new buttons, animations prefferably need to be handled passively by experiments.

**Comment by SirMortimer** [comment]
<a href="https://github.com/UsernamesAreAlwaysTaken"><img src="https://avatars3.githubusercontent.com/u/48958828?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [UsernamesAreAlwaysTaken](https://github.com/UsernamesAreAlwaysTaken)**
_Monday May 06, 2019 at 02:48 GMT_

----

edit: this will also simplify global experiment patches, if animations are handled separately in a different module. currently i have to search and patch experiments WITH animations first, then run the same search and patch experiments without animations, MM throws errors otherwise when it can't find a animation field (because it's not present)

**Comment by SirMortimer** [comment]
<a href="https://github.com/gotmachine"><img src="https://avatars1.githubusercontent.com/u/24925209?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gotmachine](https://github.com/gotmachine)**
_Sunday May 19, 2019 at 20:44 GMT_

----

This should probably be handled by the configure module.

**Comment by gotmachine** [comment]
Not perfect but good enough solution in a23ab4c82ce4179a9a2233aefdc20d23c03d3fcd
