### ISSUE TITLE
Scale experiments data size according to body size

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#412]
<a href="https://github.com/UsernamesAreAlwaysTaken"><img src="https://avatars3.githubusercontent.com/u/48958828?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [UsernamesAreAlwaysTaken](https://github.com/UsernamesAreAlwaysTaken)**
_Saturday May 11, 2019 at 15:34 GMT_
_Originally opened as https://github.com/SirMortimer/Kerbalism/issues/77_

----

Would it be possible to use the body radius as a multiplier to modify data scales of certain experiments based on how big the body is? 

mostly thinking about surface scanners such as scansat (i'm sure we can find others as well). Bigger body = more data. This has to be done in plugin, as i can't configure that with MM patches (can;t differentiate between bodies with stock EXPERIMENT_DEFINITION).

set a public field with "usebodyradiusmultiplier = true/false" that applies to datascales. I'm not sure how or if it'll work, but just putting it out there.

**Comment by SirMortimer** [comment]
<a href="https://github.com/gotmachine"><img src="https://avatars1.githubusercontent.com/u/24925209?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gotmachine](https://github.com/gotmachine)**
_Thursday May 16, 2019 at 20:08 GMT_

----

A potential issue is that the stock system will behave weirdly if the stored (retrieved) results for the same experiment have different sizes. In particular science point values and completion levels in the RnD archive UI will be wrong. Not sure this can be worked around.

Concerning ScanSat, this is a special case. I'm not familiar with it but I from what I saw in the compatibility module I think we should be able to scale the data according to the actual progression, 

But as for the general idea, I will look into it. Should be easier to do in my refactored version than in the current codebase, for various reasons, and also because that will include our custom EXPERIMENT_INFO configs that override and extend the stock EXPERIMENT_DEFINITION. 

One thing to note is that my refactor has a limitation on max data size. Hard limit is 1048576 TB but to prevent any internal overflow I think i will introduce a 1024 TB soft limit. I think currently the experiment with the largest datasize is the infrared telescope at 275 TB.

This could work as a "bodyRadiusDataScale = X", meaning that the default data size is for the radius of the home body (Kerbin) and the data size for the biggest body is the default size * X

We could use the surface area of the body but that would lead to humongous data sizes for gas giants and I'm not sure it's really much more realistic.

**Comment by SirMortimer** [comment]
<a href="https://github.com/UsernamesAreAlwaysTaken"><img src="https://avatars3.githubusercontent.com/u/48958828?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [UsernamesAreAlwaysTaken](https://github.com/UsernamesAreAlwaysTaken)**
_Thursday May 16, 2019 at 21:07 GMT_

----

No single experiment should hit that data cap realistically, because of the data transmission times. The IR Telescope is an exception, as it's a 25 year experiment. Nothing else comes even close.

Once you sort the EXPERIMENT_INFO, you'll have to guide me through what it does and what i can do with it, as I'll most likely have to rewrite a bunch of patches.

**Comment by gotmachine** [comment]
Way too complex to implement. Closing.
