### ISSUE TITLE
Longer science time in JNSQ

### ISSUE THREAD

**Issue by TheRace** [Kerbalism/Kerbalism#417]
Playing with JNSQ (2.7x size) experiments take longer, e.g. radiation scan takes 16 minutes instead of the normal 10. Related to planet resizing? Should science time be affected?

**Comment by SirMortimer** [comment]
not related to JNSQ, it happens in a vanilla game too. something is wrong.

**Comment by SirMortimer** [comment]
Fixed. That happened during the intergration of the breaking ground DLC
