### ISSUE TITLE
experiments only use the first drive

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#418]
reproduce:

have 2 drives
record data until the first drive is full
-> no more recording done.

**Comment by Gordon-Dry** [comment]
All HDs got the HdId = 0, right?

As long as the vessel is not recovered ;) ofc

So my 2 cents: when all HDs are Id = 0, how can a 2nd HD be filled ever?

**Comment by SirMortimer** [comment]
hdId is assigned the part's flight ID on runtime, it's not supposed to be configured. With that ID, kerbalism knows which drives belong to which part, which is important if vessels dock, undock, when parts explode, when grabbing data on EVA or when drawing a hilight on the part that contains the drive.

**Comment by SirMortimer** [comment]
fixed.
