### ISSUE TITLE
Kopernicus 1.7.1-4, Kerbalism 3.0, KSP 1.7.1 won't load unless DLC installed

### ISSUE THREAD

**Issue by theJesuit** [Kerbalism/Kerbalism#419]
So, with nothing else but 
KSP 1.7.1
Community
Kerbalism
Kerbalism Config
Kopernicus (1.7.1-4) obvs
ModuleFlightIntergrator

MM 4.0.2

Loading screen gets stuck with Kopernicus:Kerbalism/kerbalismXX.bin
but only in the Serentity (Breaking Ground dlc) is NOT installed.

Each mod, Kerbalism, Kopernicus, load separately WITHOUT the dlc installed.
Both mods load WITH dlc installed.

So...

**Comment by steamp0rt** [comment]
I'm guessing you upgraded from a alpha/beta and forgot to delete the .bin files.
