### ISSUE TITLE
Experiments must be ran twice to get the science

### ISSUE THREAD

**Issue by BennieCopeland** [Kerbalism/Kerbalism#421]
When running an experiment/crew report, it will complete at 100% but still have something like 0.2 science points remaining. Running the experiment a second time will catch that last 0.2 points and trigger the message from KSC about receiving the science. I'm running Kerbalism 3.0.1.

**Comment by SirMortimer** [comment]
Are you running the DLC Breaking Ground?

**Comment by UsernamesAreAlwaysTaken** [comment]
^ he's working on it. We're aware.

**Comment by BennieCopeland** [comment]
Yes

**Comment by SirMortimer** [comment]
Found it. Expect an update
