### ISSUE TITLE
Sounding Rockets support

### ISSUE THREAD

**Issue by steamp0rt** [Kerbalism/Kerbalism#425]
https://forum.kerbalspaceprogram.com/index.php?/topic/92434-13-sounding-rockets-start-small-dream-big-050/

**Comment by steamp0rt** [comment]
It apparently has new science experiments

**Comment by UsernamesAreAlwaysTaken** [comment]
https://github.com/Kerbalism/Kerbalism/commit/6edd14a334376ebded7f8f48253bd784c84009fd
