### ISSUE TITLE
Upgrades don't Upgrade.

### ISSUE THREAD

**Issue by Breach-Candy** [Kerbalism/Kerbalism#430]
Getting the HDD upgrade in "basic science" doesn't actually upgrade the disk.

**Comment by Breach-Candy** [comment]
Hol up - Only parts with more than 2MB storage get upgraded.

**Comment by Breach-Candy** [comment]
https://github.com/Kerbalism/Kerbalism/compare/master...Breach-Candy:patch-1

**Comment by SirMortimer** [comment]
actually that's intentional. otherwise you'd get a sputnik with 32mb or something at the end of the tech tree. it's an incentive to upgrade to better cores.

**Comment by Breach-Candy** [comment]
But you also wont have unpatched cores at late tech tree have more than 0.5MB.

**Comment by UsernamesAreAlwaysTaken** [comment]
No. the upgrade system is entirely intentional. It was tested again and again, and it behaves as intended.
for 0.5MB parts, that measn they're unpatched. They simply need custom hdd defs.

**Comment by UsernamesAreAlwaysTaken** [comment]
also, please do not merge that patch.
