### ISSUE TITLE
add support for [x]science please

### ISSUE THREAD

**Issue by alexmannen** [Kerbalism/Kerbalism#433]
that mod keeps track of what science you have done and havent also on what biomes.

**Comment by steamp0rt** [comment]
they had to add support on their side

**Comment by SirMortimer** [comment]
The plan is not to rely on [x] Science for that functionality. Kerbalism changed the way science works on a fundamental level, which renders at least half of the features provided by science mods pointless. 

We were already discussing some UI that helps with tracking which science has been done, can be done, which vessel is still provididing science value etc. Don't know if there is an issue for that.

**Comment by Breach-Candy** [comment]
Use kerbalism automation tab. all experiments can be done from there, automatically too.
