### ISSUE TITLE
Experiment information on automation 'time remaining' tooltip

### ISSUE THREAD

**Issue by Damien212** [Kerbalism/Kerbalism#435]
When running an experiment in orbit that resets per biome, it can often be hard to keep track of what situation you're currently sampling (Low Space Shores, High Space Forest etc). If you're transmitting too fast to see the experiment in the data tab then you have to work it out through KER biome readout etc.

If the information that's usually shown in data (situation/biome, possibly science taken/remaining) could be in a mouseover tooltip on the automation tab 'time remaining' countdown it'd help a lot.

**Comment by SirMortimer** [comment]
That's maybe something for #447

**Comment by gotmachine** [comment]
Fixed. A lot.
