### ISSUE TITLE
RemoteTech support is broken

### ISSUE THREAD

**Issue by Angel-0a** [Kerbalism/Kerbalism#436]
1. Kerbalism doesn't account for working antennas EC consumption on unloaded vessels with no connection.
2. when connection is lost, Kerbalism starts showing 100% signal strength, allowing for science transmission and remote devices control.

**Comment by syscryp** [comment]
Experiencing same bug. Any progress on this at all?

**Comment by syscryp** [comment]
Actually, found a potential workaround - go into stock settings and switch on CommNet.

**Comment by gotmachine** [comment]
I'm not very familiar with the comms/antenna code, and as usual it's an obscure hacky not-a-single comment spaghetti mess, but from a quick look I believe that CommNet indeed need to be enabled for the RT support code to work.

When CommNet isn't enabled, do you see a kerbalism log message with "RemoteTech starting up" in your KSP.log ?

Not tested but I don't think the `GameEvents.CommNet.OnNetworkInitialized` will be fired if commnet isn't enabled : https://github.com/Kerbalism/Kerbalism/blob/0b974ac0fc3574bece88d6763c662df40c4a4c00/src/Kerbalism/System/Callbacks.cs#L54

@SirMortimer ?

**Comment by Angel-0a** [comment]
Hmm, unless I'm doing something wrong, I can't enable CommNet. Or to be more precise - I can do it, and I see it works, but when I change the screen (for example I switch from the Tracking Station to the Space Center) it immediately gets corrected and something turns it off. I tired to set CommNetEnabled to True in both RemoteTech_Settings.cfg and my save file, but something keeps correcting it back ASAP. Does RT even allow CommNet to be enabled alongside RT? Are these two not conflicting, as they try to do the same job in different ways?

**Comment by gotmachine** [comment]
I was thinking the newer versions of RT were built upon CommNet but after giving a quick look this it still not the case. So no, enabling CommNet won't do any good, and RT is probably actively disabling it. 

Honestly I think the Kerbalism support code for RT is just broken. I never really played with it, I've no idea of how things are supposed to work so I won't put my hands in that, sorry. This will have to wait for someone else to look into it.

**Comment by gotmachine** [comment]
RT support added back in Kerbalism 3.15
