### ISSUE TITLE
DMagic's dmlaserblastscan produces 12 kg sample?

### ISSUE THREAD

**Issue by infoman** [Kerbalism/Kerbalism#437]
How can DMagic's Laser Surface Scan be a sample? It literally just puffs a laser onto surface and looks at the spectrum, but instead in Kerbalism it tries to dig a 12 kg chunk of rock.

It's closest IRL analog should be [Curiosity's ChemCam](https://en.wikipedia.org/wiki/Chemistry_and_Camera_complex), which obviously doesn't produce any samples, and anyways, how can a relatively weak laser vaporize 12 kg of rock and how it's supposed to collect a vaporized sample in a vacuum?

**Comment by Breach-Candy** [comment]
>how it's supposed to collect a vaporized sample in a vacuum?
It's possible.

As for the rest, I agree.

**Comment by infoman** [comment]
Same question for Dynamic Albedo of Neutrons (dmNAlbedoScan) and X-Ray diffraction (collects a small sample according to description but supposed to analyze it in-place).

**Comment by UsernamesAreAlwaysTaken** [comment]
https://github.com/Kerbalism/Kerbalism/commit/ee7b3d94f95522db67fe8b355bdf5e871b6f18f0

Should fix. Please test. Let me know.

**Comment by infoman** [comment]
Data size is probably too much (14.5 gigs from 10 minutes exposure?). With RoveMate having only about 237 MB of storage it will take ages to complete and transmit. Should probably be about 1000 times smaller I think.

**Comment by UsernamesAreAlwaysTaken** [comment]
Fixed the requirements for XRAYDIFFRACT.
Data scales will probably stay the same, for balance purposes (balance is subjective). As this can be run in the background, stick an antenna on the rover and it'll transmit the data eventually.
