### ISSUE TITLE
[RO] Drive capacity customization API

### ISSUE THREAD

**Issue by gotmachine** [Kerbalism/Kerbalism#438]
Asked by Standecco for RO support : 
Adding a way for other plugins to change the drive capacities in the editor trough an API method.
Quick analysis :  
- That would require making the partmodule capacity fields persistent so the set capacity is carried trough flight.
- The API method would need to trigger an update of the underlying drive object capacities and of the partmodule PAW UI capacity string.

**Comment by gotmachine** [comment]
In dev branch, parts with multiple drive partmodules should now have their capacites merged (https://github.com/Kerbalism/Kerbalism/commit/6f0695ff634a9cf4f5f57a46089cf8754858aeb0). This is an experimental feature not really meant as to be used in this way, but maybe you can leverage it. 

Please try and see if you encounter any issue.

**Comment by SirMortimer** [comment]
Could this maybe done with B9 part switch? Some tweakable that would alter the capacity?

**Comment by gotmachine** [comment]
That will not work as the underlying drive object will already be created with the unmodified capacity when B9PS will reload it to "switch" it. We need to implement a more solid HardDrive(s) to Drive synchronization init method, with capacities aggregation in case of multiple modules.

**Comment by SirMortimer** [comment]
How about just adding a (configurable) capacity tweak? Similar to what the kOS processors have, increase/decrease capacity at a cost of a set amount of funds and mass? Does it have to be API?

**Comment by gotmachine** [comment]
That was what I was thinking, make the partmodule capacities persistent KSPFields so changes to them in the editor are carried to flight (currently the prfab config+upgrade value is used). 

But having that as a tweakeable will conflict with the use of upgrades.

I'm not sure exactly what is @Standecco current plan, but initially it involved the procedural avionics module from RO being able to change the capacities in the editor, that's why I raised the API method possibility, just a simple thing that would set the persistent capacities fields values in the editor, and update the corresponding drive object so the editor PAW cpacity info is accurate.

**Comment by SirMortimer** [comment]
I think this should do the trick
![sizes](https://user-images.githubusercontent.com/43166475/64127106-af453f80-cdb0-11e9-92ba-de018ee62da8.gif)

**Comment by Standecco** [comment]
While the slider implemented with 4d27385 is much better than the previous system, it still doesn't allow for full customization: its linear scaling for size, cost and mass poorly translates to real world improvements, which have always been exponential and more often than not cheaper than previous implementations. I had sketched a rough progression, that would follow these values (tech tiers are those found in the RP-1 tree)

Tech Tier | Data Capacity | Cost
------------ | ------------- | -----
Basic | 488 B | 50f
Interplanetary | 2.9 kB | 200f
Mature avionics | 655 kB | 230f
Large Scale | 20 MB | 300f
Advanced | 150 MB | 200f
Long Term | 400 MB | 50f
Modern | 8 GB | 20f

These capacities are taken from various probes throughout history, while the costs are extrapolated from the current procedural avionics cost in RP-1; nothing has to be exactly identical to these values, but I'd like to have a development curve that resembles them.
If you think an API would be more useful / easier to develop than giving more variables to the current module, then I'm perfectly fine with it too.

**Comment by SirMortimer** [comment]
I don't understand the problem. Wouldn't you be using _different_ parts with different part module configurations for different eras?

**Comment by Standecco** [comment]
Nope, we only have 1 procedural avionics part. Its configuration is handled internally

**Comment by SirMortimer** [comment]
Then I don't know what I could do to support that use case while maintaining any resemblance of sanity within the part module. Ideas?

**Comment by gotmachine** [comment]
Honestly this has to be done from the ModuleAvionics side. That's why I was proposing to give them the tools to mess with the capacities from their plugin.

**Comment by Standecco** [comment]
While an API is perfectly fine, a simpler solution might be giving exponential scaling to the existing module. I put the values in a logarithmic table, and this is the outcome: 
![image](https://user-images.githubusercontent.com/43384369/64197710-0c132980-ce87-11e9-8c92-20288916dcf7.png)
As you can see, it's close enough, in my opinion. You decide though, having an API would allow us to let the player choose the exact size of their storage and scale the cost and mass based on the unlocked tech level. That's the way I'd do it, at least.

**Comment by SirMortimer** [comment]
This would be the API variant: in the editor, you set maxDataCapacityFactor to 0, that disables the slider. then you set effectiveDataCapacity to whatever you want. same for sample capacities, that should work just fine. you can handle extra mass and cost from procedural avionics.
