### ISSUE TITLE
USI Sounding Rockets matbay experiment reconfig doesn't work

### ISSUE THREAD

**Issue by Breach-Candy** [Kerbalism/Kerbalism#440]
See #playtesting on discord

**Comment by UsernamesAreAlwaysTaken** [comment]
https://github.com/Kerbalism/Kerbalism/commit/44a43dd6b298b81d6a2690d7f024d86d4bb182bb

This should probably fix it. Test pls, and let me know.

**Comment by UsernamesAreAlwaysTaken** [comment]
Fixed again. I forgot how to MM.
This time for good. Closed.
