### ISSUE TITLE
unmanned probes getting radiation belt pop-ups

### ISSUE THREAD

**Issue by Breach-Candy** [Kerbalism/Kerbalism#441]

**Comment by gotmachine** [comment]
Not a bug, but could be nice to add a check for that, indeed.

**Comment by Breach-Candy** [comment]
what I meant is that currently, unmanned vessels are getting rad belt pop-ups and shouldn't be

**Comment by SirMortimer** [comment]
the first time you enter a radiation belt you get a popup, this is intentional.

**Comment by SirMortimer** [comment]
That's the intended behaviour: you see the warning only for crewed vessels, OR if you're entering the belt for the first time (I wouldn't want to remove that).
```
// we only show the warning for manned vessels, or for all vessels the first time its crossed
bool must_warn = vi.crew_count > 0 || !DB.landmarks.belt_crossing;
```
