### ISSUE TITLE
Probodobodyne QBE overpowered in "Unkerballed start"

### ISSUE THREAD

**Issue by TheRace** [Kerbalism/Kerbalism#443]
With unkreballed start tech tree, the QBE probe core is available it tier three in the tree, and has a  staggering 82MB of storage. Storage should be nerfed in this tech tree, if possible

**Comment by UsernamesAreAlwaysTaken** [comment]
There's no current plans for Unkerballed Start support. 
Custom tech trees are a pain to balance, and require a massive time investment (have to play with them for a while to get where they're going with it).
Currently we only provide support for CTT, and if you want a unmanned start, we also support Probes Before Crew.

No ETA on other tech tree/unmanned starts mod support for now.

**Comment by maushacks** [comment]
@UsernamesAreAlwaysTaken It is just a thought: But would it be possible to make internal data storage capacity of the pods dependent upon progress on the tech tree, basically implementing Moore's law in kerbalism, at least as an option? So, one can have a slider when building a rocket that goes from low capacity but heavy magnetic tapes to solid state disks eventually. 
That might circumvent the issue of tech tree varieties being too advanced.

**Comment by lordcirth** [comment]
> @UsernamesAreAlwaysTaken It is just a thought: But would it be possible to make internal data storage capacity of the pods dependent upon progress on the tech tree, basically implementing Moore's law in kerbalism, at least as an option? So, one can have a slider when building a rocket that goes from low capacity but heavy magnetic tapes to solid state disks eventually.
> That might circumvent the issue of tech tree varieties being too advanced.

That is already how it works, except that it's at specific tech nodes that the upgrades happen. Similar to how new ECLSS / ISRU processes are unlocked.

**Comment by maushacks** [comment]
@lordcirth Oh, thanks for the clarification! I did not realize this.

**Comment by SirMortimer** [comment]
https://github.com/Kerbalism/Kerbalism/commit/53b92975e2b78eda2fe91e0814487185c1c270e6
