### ISSUE TITLE
Kerbnet brokes for most probes

### ISSUE THREAD

**Issue by dawidh15** [Kerbalism/Kerbalism#448]
I notice Kerbnet says "Kerbnet is offline", and showed no data, no refreshing, etc. Then I uninstalled all mods.

Afterwards I installed Community Resource Pack (CRP), and run some in-game test, with Kerbnet, and they were OK.

Then, I installed Kerbalism, and Kerbnet broke again.

I also notice that you can scan all resources with using CRP, but when you installed kerbalism, you can't see *Ore* (the stock resource).

This is a very recent and clean installation of KSP (about a week ago).

Good Luck, it will be cool to have Kerbalism working with Kerbnet

**Comment by gotmachine** [comment]
can anyone confirm this ?

**Comment by UsernamesAreAlwaysTaken** [comment]
No clue about Kerbnet, but i'll check the ore issue.

may be an oversight on my part

**Comment by dawidh15** [comment]
Hello:

I reinstalled KSP 1.7.3, and the issue is no longer there. Not sure if you fixed it, but, I think you can close this issue now.

BTW, Ore resource can be seen now.

Thanks for the follow up.

**Comment by SirMortimer** [comment]
OK :)
