### ISSUE TITLE
SSPX - Incorrect part volume

### ISSUE THREAD

**Issue by Tacombel** [Kerbalism/Kerbalism#450]
PXL-1 and PXL-2 have the same volume and surface
![image](https://user-images.githubusercontent.com/17971083/60253382-5a76db80-98cc-11e9-9138-895829c1ebea.png)
![image](https://user-images.githubusercontent.com/17971083/60253413-6793ca80-98cc-11e9-980e-c561568eff2e.png)

**Comment by UsernamesAreAlwaysTaken** [comment]
Wrongly configured parts. 

https://github.com/Kerbalism/Kerbalism/blob/master/GameData/Kerbalism/Support/SSPX.cfg
Lines 463 to 549. I wouldn;t be surprised if the inflatable habs also have wrong values.

The person who wrote the config decided to apply the same volume to all parts of the same size for some reason. This applies to a lot of parts from SSPX.

Will fix today, needs a bunch of simple and tedious geometry and math to calculate actual volumes and surfaces.

**Comment by maushacks** [comment]
Hello, I have a similar issue with HGR (Home-Grown Fixes for Home-Grown Rockets), which shouldn't receive any patches from Kerbalism, however, two of its capsulas got ridiculous volumes. I doubt their bounding boxes are this insanely huge though. Any idea what might have gotten wrong?
![image](https://user-images.githubusercontent.com/51866804/60751671-ea4a1300-9fb9-11e9-97eb-ccb72a343407.png)
