### ISSUE TITLE
Repeated entries in B9Partswitch.cfg file

### ISSUE THREAD

**Issue by Galenmacil** [Kerbalism/Kerbalism#452]
This file: .\GameData\Kerbalism\Support\B9PartSwitch.cfg

As two repeating entries at line 75 and 95 respectively:

B9_TANK_TYPE
{
	name = Sewage
	tankMass =  0.00010627500
	tankCost = 0.15
	RESOURCE
	{
		name = Waste
		unitsPerVolume = 0.4946378
		percentFilled = 0
	}
	RESOURCE
	{
		name = WasteWater
		unitsPerVolume = 0.5053622
		percentFilled = 0
	}
}

**Comment by SirMortimer** [comment]
thanks, fixed
