### ISSUE TITLE
Asteroid surface sample: NullReferenceException

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#458]
> From discord: `The Destroyer`
> Sooo apparently Kerbals cant take a sample from asteroids either, I'm betting its kerbalism due to the way it changes science

This might or might not be related to Kerbalism, however we should take a look at it.

```
[EXC 23:24:33.677] NullReferenceException: Object reference not set to an instance of an object
        ModuleAsteroid.performSampleExperiment (.ModuleScienceContainer collector)
        ModuleAsteroid.TakeSampleEVAEvent ()
        BaseEvent.Invoke ()
        UIPartActionButton.OnClick ()
        UnityEngine.Events.InvokableCall.Invoke ()
        UnityEngine.Events.UnityEvent.Invoke ()
        UnityEngine.UI.Button.Press ()
        UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData)
        UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
        UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
        UnityEngine.EventSystems.EventSystem:Update()

```
![unknown](https://user-images.githubusercontent.com/43166475/60872288-b62e5680-a234-11e9-923d-308277bbaa6a.png)

**Comment by SirMortimer** [comment]
![unknown-2](https://user-images.githubusercontent.com/43166475/60872425-eece3000-a234-11e9-8704-68f1ab6dd162.png)
higher res image

**Comment by UsernamesAreAlwaysTaken** [comment]
Interesting. The experiment itself should be left with stock behavior due to us not being able to check for asteroid landing.

I have no idea what's causing the NRE. Will fiddle with it soon, and will post an update.

**Comment by gotmachine** [comment]
That's why ( ModuleAsteroid.TakeSampleEVAEvent() code) :
```
ModuleScienceContainer collector = FlightGlobals.ActiveVessel.FindPartModuleImplementing<ModuleScienceContainer>();
performSampleExperiment(collector);
```

and then in ModuleAsteroid.performSampleExperiment(ModuleScienceContainer collector) : 
```
if (collector.HasData(experimentData))
{
    ScreenMessages.PostScreenMessage("<color=orange>[" + collector.part.partInfo.title + "]: <i>" + experimentData.title + cacheAutoLOC_230121, 5f, ScreenMessageStyle.UPPER_LEFT);
    return;
}
GameEvents.OnExperimentDeployed.Fire(experimentData);
if (collector.AddData(experimentData))
{
    collector.ReviewData();
}
```

To fix, it's either 
- Harmony patching the ModuleAsteroid.TakeSampleEVAEvent method for it to put the data on our drive
- Implementing a "part colliders distance check" condition in the experiment module and implementing custom subject_id generation, which will require quite a lot of modifications.

I'm gonna fix this the easy-and-dirty way by harmony patching the ModuleAsteroid module.

**Comment by gotmachine** [comment]
Should be fixed.

Note that there is a new setting available in settings.cfg : "AsteroidSampleMassPerMB"

Comment : when taking an asteroid sample, mass (in t) per MB of sample (baseValue * dataScale). default of 0.00002 => 34 Kg in stock
