### ISSUE TITLE
Moving samples into the container causes the experiments to run again

### ISSUE THREAD

**Issue by lordcirth** [Kerbalism/Kerbalism#459]
To reproduce: Launch a craft with a 2 material bays and an experiment storage unit. Run the mat bay until it's done. Move samples into the container using "Move data here". The mat bay starts collecting duplicate data into it's own storage all over again.

**Comment by gotmachine** [comment]
The current handling of experiment automatic mode / completion checks is indeed far from perfect. May be revamped at some point.

**Comment by gotmachine** [comment]
Merged with #446
