### ISSUE TITLE
Can't fullfil DLC pickup and return contracts with Kerbalism installed. 

### ISSUE THREAD

**Issue by JohnDavidLarsen** [Kerbalism/Kerbalism#460]
Can't fullfil DLC pickup and return mun stone or greenstone contracts with Kerbalism installed. 
(Probably same for Duna berries)

**Comment by JohnDavidLarsen** [comment]
I should clarify. If I have a contract to pick up a Mun Stone I can successfully pick it up. Kerbalism transmits it as science not as a sample. When I return to kerbin the contract will not be considered complete.

**Comment by JohnDavidLarsen** [comment]
https://forum.kerbalspaceprogram.com/index.php?/topic/172400-140-171-kerbalism-v302/&do=findComment&comment=3631307

**Comment by gotmachine** [comment]
This should be fixed by the the fix for #476 (dev branch), see https://github.com/Kerbalism/Kerbalism/commit/56e1879d7eeb509f626ebe29e6a319254396e3c5
