### ISSUE TITLE
USI Kolonization Systems (MKS/OKS) support

### ISSUE THREAD

**Issue by MaximeBrean** [Kerbalism/Kerbalism#464]
Kerbalism flag `USI Kolonization Systems (MKS/OKS)` as conflicting on CKAN.

I'm wondering what is the incompatibility here because the mod bring some nice parts that I want to use along with Kerbalism.

**Comment by gotmachine** [comment]
The resource simulation is incompatible, and there is too much feature overlap. We have no plan to support USI-LS or MKS.

**Comment by UsernamesAreAlwaysTaken** [comment]
As stated above, there's too much feature overlap, and I don't see a reason to support it. 

To support USI, we'd have to nuke everything and rebuild the parts from scratch with our own modules,but at that point MKS becomes like any other part mod, as it loses all custom functionality. 

IMO there's better part mods around.
