### ISSUE TITLE
Science elements appear twice for EVA kerbal

### ISSUE THREAD

**Issue by MaximeBrean** [Kerbalism/Kerbalism#468]
Hello !

Science and scrubber buttons appear twice for EVA Kerbal in PAW menu as show below

![duplicate-science](https://user-images.githubusercontent.com/17298958/61395045-c7c2ce80-a8c4-11e9-852e-da37be20e80a.png)

Pic taken in a fresh career mode with default parameters on 1.7.3 (both DLC) and only Kerbalism 3.0.2 with dependencies pulled by CKAN.

Kind regards.

**Comment by SirMortimer** [comment]
This happens with Breaking Grounds and has to do with what they do to EVAs.

**Comment by MaximeBrean** [comment]
I also found that depending on suit skin, the problem is only with old suit skin as you could see below (new one in the middle):

![image](https://user-images.githubusercontent.com/17298958/61397948-4458ab80-a8cb-11e9-8c0d-4a4f8a0228c5.png)


Below is the same setup with a pristine KSP 1.7.3 with both DLC (no duplicated crew report):

![image](https://user-images.githubusercontent.com/17298958/61397905-33a83580-a8cb-11e9-8518-a973bb54c2b8.png)

**Comment by MaximeBrean** [comment]
With Serenity, Squad duplicated kerbalEVA parts that correspond to old spacesuit but only add the new ROCScience module. They are located in `SquadExpansion/Serenity/Parts/Prebuilt`.
KSP will then merge parts definition with the same name.

MM identify part using their path. As there is two kerbalEVA definition, MM will apply patches to both definition and KSP will merge both definition at the end.

Result is then duplicated properties and nodes.

The solution is to prune everything added by Kerbalism in the FINAL MM pass only for redefined parts. For kerbalEVA* parts, we can use the KerbalEVA module.

PR will come in minutes.

I will also open a issue about this on MM side to look for a workaround.

**Comment by gotmachine** [comment]
We are aware of the issue and have a config fix that will be released very soon.

**Comment by MaximeBrean** [comment]
Do you know if current repo content for configuration is compatible with latest release ? Or there was too much work done on it ?

**Comment by gotmachine** [comment]
I think you can download [the current config](https://github.com/Kerbalism/Kerbalism/tree/master/GameData/KerbalismConfig) and use it safely with the latest core release.

**Comment by MaximeBrean** [comment]
Thanks !
Reliability module is still duplicated though :(

**Comment by SirMortimer** [comment]
The duplicate reliability is probably due to the two experiments on the EVA (EVA report + surface sample). Both can "fail", which IMO is nonsense.

**Comment by MaximeBrean** [comment]
By duplicated, I mean also defined into the part added by Serenity.
The missing HAS requirement is https://github.com/Kerbalism/Kerbalism/blob/7575f1b6a62b0876dfaf835f6be306321c0905d4/GameData/KerbalismConfig/System/Reliability.cfg#L783

Adding `!Module[KerbalEVA]` in the HAS will also exclude kerbalEVA redefinition.

**Comment by SirMortimer** [comment]
Should be good now, I'll test this later.

**Comment by SirMortimer** [comment]
This should be fixed with the updated configuration. See [here](https://github.com/Kerbalism/Kerbalism/releases).
