### ISSUE TITLE
Kerbal Atomics: engines radiation sources

### ISSUE THREAD

**Issue by Shiolle** [Kerbalism/Kerbalism#469]
Some of the nuclear thermal rockets in this mod are missing radiation sources (see linked document for the list of engines). I've tried to add the missing values myself, extrapolating from existing engines according to their power. Resulting file is attached below. Calculations can be found [here](https://docs.google.com/spreadsheets/d/1e0MzwAC8koIHX82uX02qhFOIa01m59-YO_Kg2VOCzGE).

[KerbalAtomics.zip](https://github.com/Kerbalism/Kerbalism/files/3403754/KerbalAtomics.zip)

**Comment by gotmachine** [comment]
Seems alright. Maybe @UsernamesAreAlwaysTaken can do a quick review ?

**Comment by SirMortimer** [comment]
Looks good to me
