### ISSUE TITLE
DataRateDampingExponent might need to be clarified

### ISSUE THREAD

**Issue by DetPikachu** [Kerbalism/Kerbalism#472]
So I'm playing in a 2.5x scale system, and when I went to change the DataRateDampingExponent in the kerbalism settings files it said 'exponent by which antenna bandwidth decreases with distance. rescaled systems will require a smaller value'. Which I initially interpreted as 'decrease the number here for systems bigger than stock', which was supported by SirMortimer's post on the mod's forum thread ([link to that here](https://forum.kerbalspaceprogram.com/index.php?/topic/172400-140-171-kerbalism-v302/&do=findComment&comment=3628821)).

When I replaced the value to 4 (since that was what was suggested) however, the bandwidth climbed up. I tried again with 3.5, and again with 2, and it kept going up; even though the satelite in Duna orbit that I was using for testing was as far away from Kerbin as possible, it had something like 2Mb/s bandwidth. Then I realized that the value _increases_ the dampening of the data rate, so you actually have to increase the value. Set it to 15 and now the Kerbin-Duna data rate is at around 530Kb/s.

Looking back on it, I suppose the config file isn't technically wrong (you are increasing the _dampening_ value, therefore the _bandwidth_ value decreases), but it should be worded a bit better to avoid confusion. I'd suggest replacing 'rescaled systems will require a smaller value' with 'systems that have been scaled up or down should change this value accordingly'. That way, people who play in bigger systems will replace the default value with a bigger number, and those that play in smaller systems will put a smaller number.

**Comment by lordcirth** [comment]
So, you were playing at 2.5x, and you decreased the number as SirMortimer's post said, and you correctly got more bandwidth. Lowering the exponent means you get similar data rates around Duna as you would at 1x.

But it's true that it was assumed that rescaled systems are bigger, not smaller. Bigger is much more common, but it should be documented.
