### ISSUE TITLE
Universal Storage 2 probe core doesn't receive HDD upgrade

### ISSUE THREAD

**Issue by MaximeBrean** [Kerbalism/Kerbalism#474]
No more than the title say actually. The probe core stay at 512Kb of HDD space.
As there is already a compatibility patch for US2, it would be nice if the probe core (name: `USDoubleProbeCore`) get upgrades.

**Comment by gotmachine** [comment]
This is intended only parts that have a base HDD of 2Mb or more gets upgraded, see https://github.com/Kerbalism/Kerbalism/issues/430
But you're not the first to be surprised, and I personally disagree with the idea. 
I don't like that early available parts are made useless in the late game, it should be the point of upgrades.
Keeping this open for awareness.

**Comment by MaximeBrean** [comment]
So if I get it right, the probe core need a custom HDD configuration.
Considering that it's unlocked in the same tree node than the Probodobodyne HECS, and it have same stats (weight, SAS, reaction wheel, electricity, ...), could it get a the same base HDD size ?

**Comment by UsernamesAreAlwaysTaken** [comment]
```
and I personally disagree with the idea
```
```
And it would avoid having to create and maintain custom HDD configs for every mod.
```
The choices I had was to apply blanket drive sizes based on tree position, which comes with 2 issues: 
1: Makes all parts in the same tier uniform, which kind of makes them bland
2: Removes any semblance of choice between parts for science purposes (there is still a cosmetic one), as, considering drive size alone, people would go for the cheapest option available.

Thus i went with custom drive sizes (I understand the implications very well, I had to write the patches) to give parts a niche. Think lander cans vs orbital pods. Landers will have more sample storage, pods should have balanced sizes, while probe cores get more drive space in the same tier.

Yes, it's causing problems, but I assume the other options would cause some as well. Pick your poison basically.

Regarding differential upgrades, again, it was a choice. I had the universal upgrades in the beginning, but feels unnatural to see a few GB drive on a stayputnik. MUH IMMERSION basically.
Another reason was to avoid the situation where players would go for stayputniks all the time. Want morre space? Use better parts.

Again, all this was choice. I had to patch the system, thus I had some freedom regarding the functionality.

**Comment by UsernamesAreAlwaysTaken** [comment]
Small update:

Currently working on a way to automatically assign base drive sizes that are calculated from part stats, such as mass, cost, tech tier, etc.

This should remove the need for manually and individually patching drives on parts. 
It's currently functional, though balance and progression needs tweaking. 

Regarding upgrades, I'm still keen on differential upgrades based on initial drive size. Higher tech parts will have higher base drives, thus they'll get the better upgrades. I'll keep it as an incentive to use better parts and spend more money for more complex missions.

**Comment by sswelm** [comment]
IMHO there should be more upgrades

**Comment by UsernamesAreAlwaysTaken** [comment]
Maybe. I was thinking about it at some point, but then it turns into a massive upgrade spam on parts.

I'm open to the idea of more, but smaller upgrades to give the players a constant sense of progression. Plus now I can actually filter by tech tier instead of some base drive size.

**Comment by MaximeBrean** [comment]
What about a dedicated HDD part ? With or without upgrade.

**Comment by UsernamesAreAlwaysTaken** [comment]
KER parts can be used as stand-alone HDD parts.

Without KER, I'm afraid we can;t accomodate that. We would need someone to model those parts, and we don't have anyone to do that.

**Comment by MaximeBrean** [comment]
Another idea, what about making a HDD supplement through unmanned experiments and pod configurations ? The latest one may be tricky to set because the pod configuration is available for all maned part.
Regarding probes core (which I extensively use), I usually strip unmanned experiments in favor of dedicated parts, but that's my own play-style.

**Comment by gotmachine** [comment]
I think the latest changes with user-upgradeable drive sizes + the MM-patch changes cover most the drive size issues.
