### ISSUE TITLE
Contracts (and other things) checks for science data fail on vessel recovery

### ISSUE THREAD

**Issue by gotmachine** [Kerbalism/Kerbalism#476]
Visible issue : "return a Mun rock" type contracts aren't completed on vessel recovery
See also #249 (same root cause)

**Analysis**
On vessel recovery, the contract completion code is searching for the corresponding "subjectID" in the "ScienceData" node of every protoPartModuleSnapshot.moduleValues node in Expansions.Serenity.Contracts.CollectROCScienceRetrieval.OnVesselRecoveryProcessing(ProtoVessel pv, MissionRecoveryDialog mrDialog, float recoveryScore)
Obviously it won't find it as those proto values don't exist with kerbalism.

No matter from what module (ours/ stock / mods) the data is generated, it's always stored in our drives as we remove all ModuleScienceContainer modules.
Unless the mod that search for the data is doing it while the vessel is loaded AND it's using IScienceDataContainer (we implement it in harddrive), it won't find anaything.
Since vessel recovery has to be done on the protovessel, the only way for stock/mods is by searching for the ModuleScienceContainer protovalues.

There are other part of stock / other mods that might be expecting to find the stock science data on vessel recovery, so maybe we should implement a global fix.

**Possible solution**

Maybe we can implement a global fix like this :
- Before vessel recovery (~~onVesselRecovered gameevent, happens before onVesselRecoveryProcessing~~) SEE EDIT
- Convert all files/samples from the vessel drives to a list of stock "ScienceData" objects (we already have the code for that in HardDrive.GetData())
- Call `scienceData.Save(node.AddNode("ScienceData"))` for each ScienceData in the list, with node being the HardDrive protoPartModuleSnapshot.moduleValues confignode.

This should work because since any module can store data (because that can happen in any PM that implements IScienceDataContainer), the stock recovery code actually search all protomodules for  "ScienceData" nodes in protoPartModuleSnapshot.moduleValues. We can expect other mods or stock features to act the same way.

This will let the stock science data recovery happen, and anything that expect it  to be here in onVesselRecoveryProcessing should regain compatibility.
This would replace the current code we have in Callbacks.VesselRecoveryProcessing.
Possible drawback is that the stock crediting code will happen instead of our own (in Science.Credit), but there isn't really any customization in this.

EDIT :
Actually it's the other way around, onVesselRecoveryProcessing is fired by onVesselRecovered.
So depending on the order in wich callbacks for onVesselRecovered happen, that won't work.

This said, onVesselRecoveryProcessing in fired from only one place, in `VesselRecovery.OnVesselRecovered()`, which is a callback added to onVesselRecovered.
So possible workaround is to use an harmony Prefix method attached to `VesselRecovery.OnVesselRecovered()`.
I don't think there is any other reliable way to detect that event earlier.

**Comment by SirMortimer** [comment]
Should be fixed. Need to test this specifically for Breaking Grounds, but I'm optimistic.
