### ISSUE TITLE
Recovering early film experiment through KCT does not reset depletion

### ISSUE THREAD

**Issue by nepphhh** [Kerbalism/Kerbalism#478]
To reproduce: Build plane with early film experiment, run to depletion. Recover via KCT. Experiment is still depleted when re-launched. Opening the KCT editor and saving does not change depleted status. To recover fully, experiment part must be replaced.

**Comment by UsernamesAreAlwaysTaken** [comment]
What in the world is early film experiment?

Info. A lot more of it please.

**Comment by SirMortimer** [comment]
Its a RO sample experiment.

It should behave the same like a goo canister.

**Comment by UsernamesAreAlwaysTaken** [comment]
So basically, the sampling_mass does not reset on launching a new vessel.

This is never an issue with Kerbalism alone, or with most other mods. Seems like KCT is causing issues (as usual).

**Comment by SirMortimer** [comment]
We had that same issue before the 3.0 release (won't dig out the issue now) and i thought it was fixed. Apparently not.

**Comment by SirMortimer** [comment]
Hopefully fixed for good by using the KSP `GameEvents.OnVesselRollout` callback.
