### ISSUE TITLE
Non-linear degeneration

### ISSUE THREAD

**Issue by SevenOfCarina** [Kerbalism/Kerbalism#481]
Right now, once a particular threshold is crossed for environmental conditions, kerbals always have a fixed stress increase/degeneration rate. The cabin overheating to 320K might be temporarily survivable depending on humidity, but 350K will kill them within moments. It'd be nice if the degeneration rate increased as the conditions get more extreme, starting low enough that there's enough time to fix problems before everyone dies/has a breakdown. I'm attempting to have certain things like temperature fluctuations, high humidity, etc. cause stress, so is there any way to implement such a tracker?

**Comment by gotmachine** [comment]
You could try to add the "temperature" and "humidity" modifiers to the stress rule, but I'm not sure of the consequences.

**Comment by SevenOfCarina** [comment]
It doesn't appear do do anything. Or I've screwed up somewhere. I'll keep trying. Does low temperature actually kill kerbals?

**Comment by gotmachine** [comment]
> Does low temperature actually kill kerbals?

Yes. All rules kill kerbals unless they have "breakdown = true", in which case the degeneration cause a breakdown.

If you want to play with the configs, I suggets reading the [wiki first](https://github.com/Kerbalism/Kerbalism/wiki)
