### ISSUE TITLE
Show experiment result description in the file manager tooltip

### ISSUE THREAD

**Issue by gotmachine** [Kerbalism/Kerbalism#488]
Should be doable, I think there is a stock method that use the subject_id to retrieve the message, need to investigate

**Comment by SirMortimer** [comment]
I always wanted to have that in the finished message that pops up when an experiment is done, but never got around (or cared enough) to look into it.

**Comment by gotmachine** [comment]
Added in https://github.com/Kerbalism/Kerbalism/commit/359770ba5885effbf54a60dad2aa55d60b11a09a (dev branch)
