### ISSUE TITLE
Probably ScrapYard : Exceptions due to drive dictionary with duplicates FlightID

### ISSUE THREAD

**Issue by vonWatters** [Kerbalism/Kerbalism#495]
Hi, I've been wrestling with the following for days, haven't found useful references anywhere (here, forum, Google) and would be very grateful for opinions.

Version: current 3.0.2 downloaded today.
Symptoms:
* Log constantly spams
` ArgumentException: An element with the same key already exists in the dictionary  `
Once started it continues in all scenes.
* EVAs have no monoprop
* Solar panels don't generate EC
* An existing station starts oscillating to destruction when it's loaded into scene when approaching it (but not when I command directly)

Things I've tried to reproduce:
1) I originally thought the problem was a single vessel since problems started after its launch, so I reloaded before it was first used: works fine until I save and reload, at which point whatever state the vessel's in (pad or launched to orbit) the log spam starts.
2) Remove all but Kerbalism, CryoTanks, CryoEngines, StationPartsExpansionRedux (necessary for my ship).  Same result as 1).
And now more worryingly:
3) Copied KSP installation, removed all mods except Kerbalism & Config.
Loaded old save: VAB -> add a Mk1 pod = spams
`Exception: NullReferenceException: Object reference not set to an instance of an object`
4) Same "clean" config as 3) but created new career: same result.  Can an entire install get corrupted?

Files: KSP logs for both errors, plus a save file ("Raven" is the ship I originally had problems with)
https://gofile.io/?c=kzYCCs

Sample log paragraph (they change slightly):
```
ArgumentException: An element with the same key already exists in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.UInt32,KERBALISM.Drive].Add (UInt32 key, KERBALISM.Drive value) [0x00000] in <filename unknown>:0 
  at KERBALISM.Drive.GetDriveParts (.Vessel vessel) [0x00000] in <filename unknown>:0 
  at KERBALISM.Drive.GetDrives (.Vessel vessel, Boolean include_private) [0x00000] in <filename unknown>:0 
  at KERBALISM.Drive.GetCapacity (.Vessel vessel, System.Double& free_capacity, System.Double& total_capacity) [0x00000] in <filename unknown>:0 
  at KERBALISM.Vessel_info..ctor (.Vessel v, Guid vessel_id, UInt64 inc) [0x00000] in <filename unknown>:0 
  at KERBALISM.Cache.VesselInfo (.Vessel v) [0x00000] in <filename unknown>:0 
  at KERBALISM.Monitor.Render_vessel (KERBALISM.Panel p, .Vessel v, Boolean selected) [0x00000] in <filename unknown>:0 
  at KERBALISM.Monitor.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.Launcher.Update () [0x00000] in <filename unknown>:0 
  at KERBALISM.UI.Update (Boolean show_window) [0x00000] in <filename unknown>:0 
  at KERBALISM.Kerbalism.Update () [0x00000] in <filename unknown>:0 
```

**Comment by gotmachine** [comment]
Thanks for the detailed report. Drives are definitely prone to issues because they are handled differently than normal KSP objects (because we need them to exist on unloaded vessels).

> removed all mods except Kerbalism & Config.

Just to be sure : you kept CommunityResourcePack and ModuleManager ?

> 4. Same "clean" config as 3) but created new career: same result. Can an entire install get corrupted?

New career and new craft ? Or reloading the problematic craft ? That definitely isn't possible, although please make sure that you also (manually) deleted your old saves and craft inside the "saves" folder.

I highly suspect Scrapyard to cause issues with drives. I'm not very familiar with the mod but for some reason the "inventory" saves the drive partmodule persistent data, and the last recovered part  (I guess) flight seems to be saved with it.

If scrapyard somehow reapply this confignode to new parts, it's very likely to cause trouble like the `ArgumentException: An element with the same key already exists in the dictionary` you are getting, although I'm not sure of the exact steps.

```
ScrapYard.InventoryPart
{
	_name = mk1-3pod
	_dryCost = 4087.00024
	_id = 3777556669
	_timesRecovered = 1
	_inventoried = True
	MODULE
	{
		name = HardDrive
		isEnabled = True
		hdId = 2401786877 // THIS IS IS VERY WORRYING
		stagingEnabled = True
		UPGRADESAPPLIED
		{
			upgrade = HDD-Upgrade1
			upgrade = HDD-Upgrade2
			upgrade = SampleCapacity-Upgrade1
			upgrade = SampleCapacity-Upgrade2
		}
	}
}
```

**Comment by gotmachine** [comment]
Notified SeveredSolo about the issue. I'm waiting for a response but it looks like there is a blacklist config we could leverage if the issue is effectively caused by ScrapYard : 

From https://github.com/severedsolo/ScrapYard/blob/master/GameData/ScrapYard/ModuleTemplates.cfg : 
```
//Forbidden templates are used to define modules that shouldn't be stored in the inventory
//If a part has any forbidden modules, it isn't stored
//This isn't really fleshed out yet
//SY_FORBIDDEN_TEMPLATE
//{
//  name = KerbalEVA //don't allow EVA kerbals to be added to the inventory
//}
```

**Comment by vonWatters** [comment]
Thanks for the quick response!  To answer your points:
* I'd removed CRP - didn't think to check dependencies
* It was a new career & new craft, but I didn't manually delete the old files

I'd been wondering about duplicate IDs but couldn't find a way to cross-check them all.

I'm not bothered about Drive parts being blacklisted so I'll give this a go with/without mods & old saves, though might be a couple of days before I get a chance.  For my existing save, if I change one of the duplicate IDs to a random number (after checking it's not already present...) is that likely to resurrect it, or just cause more problems?

**Comment by gotmachine** [comment]
@vonWatters CRP is mandatory, not having it was causing the nullrefs in your 3. and 4. attempts.

I suggest not removing mods for testing with the existing save. Doing that usually break stuff, which doesn't help in troubleshooting the initial problem.

For your existing save, I suggest editing it to remove all the `Module { }` nodes that have `name = HardDrive` inside all those `ScrapYard.InventoryPart` nodes. Be careful not to mess the `{` and `}` blocks. Then try with the little patch I posted and let us know is that does it.

**Comment by severedsolo** [comment]
@vonWatters I am confused as to why you are using ScrapYard at all. You have no mods that use it. ScrapYard does nothing by itself.

Can I please get the craft file that was having problems, so I can see if I can reproduce the issue.

**Comment by severedsolo** [comment]
I'm not able to reproduce in your save by loading a new Mk1-3 pod and applying the inventory.

**Comment by SirMortimer** [comment]
There's also something we did in Kerbalism: whenever a new vessel rolls out, we now make sure to re-initialize the hard drive ID.

**Comment by vonWatters** [comment]
Thanks all.  I added the patch and edited my save, and that appears to have done the trick: I've launched a couple of new vessels and re-loaded several times since with no issues.
