### ISSUE TITLE
Airplane engine failure. 

### ISSUE THREAD

**Issue by JohnDavidLarsen** [Kerbalism/Kerbalism#510]
Not sure if I'd call this a bug but I ran into something interesting yesterday running a recent dev build. Was flying an airplane and botched the landing so reverted to a quicksave from right before the landing. It loaded my plane flying and instantly an engine failed (one of two so unbalanced). I couldn't get out and fix it, so quickloaded again and the engine was fine. This got me wondering, does a quick load of an active engine trigger a engine ignition and a 10% chance of failure. Also do plane engines fail randomly before the timer for life goes out?  You can't get out and fix a flying plane.

**Comment by SirMortimer** [comment]
Looks like loading triggers the code that detects an iginition. Air breathing engines (i.e. jet engines) are not supposed to have an ignition limit, and a rated duration of 24 hours. But they still come with a turn on failure probability of ~1% - that's what triggered the failure (BTW, you can check that in the F3 flight log).

**Comment by SirMortimer** [comment]
Fix will be in the next dev build.

**Comment by JohnDavidLarsen** [comment]
Thanks, one more thing.. Lets say I did fly this for 23 hours, I landed.  Is there a way to repair, inspect the engine before it fails in order to revive the 24 hour window of usage?

**Comment by SirMortimer** [comment]
Yep: you can do maintenance on EVA.

Go to the engine part, inspect it, and if something needs repair, you can repair it before it breaks down. That works on all parts with some degree of wear, that is when they get close to their failure date, engines that have been used for more than (i think) 50% of the rated time or ignitions.

You might need a kerbal with a defined trait (Engineer, or Scientist) for the repair, that depends on the parts configuration.
