### ISSUE TITLE
Build 7211: Failures not reflected on parts

### ISSUE THREAD

**Issue by thunder175** [Kerbalism/Kerbalism#516]
Had a spacecraft with multiple failures tonight. Unfortunately neither of the parts are shown as broken on the Kerbalism failure screen, nor via the right click menu. 

![image](https://user-images.githubusercontent.com/25423868/65841857-c49c8380-e2f4-11e9-8e3b-c67f807773fc.png)

**Comment by SirMortimer** [comment]
Possibly related:

> I had 4 solar panels in symmetry, and all four failed at the same time. Unless I am incredibly unlucky it shouldn't happened. As soon as I switched to it. But you are right it must be related to radiation someway, because there where another two parts damaged
