### ISSUE TITLE
Infrared Telescope experiment inconsistent

### ISSUE THREAD

**Issue by Tacombel** [Kerbalism/Kerbalism#518]
![image](https://user-images.githubusercontent.com/17971083/66272756-1ce00200-e86e-11e9-94ca-c54d82fd0617.png)
The experiment description says Space high, but it is already running at 68km. Orbit 80x68 (Still climbing)

**Comment by gotmachine** [comment]
the mess with the situation evaluation should be fixed in next dev build.
