### ISSUE TITLE
Build 7233 Engine runtime infinite

### ISSUE THREAD

**Issue by TheRace** [Kerbalism/Kerbalism#521]
Engine runtime does not decrease under thrust. Number of available ignitions does not go down with repeated thrust--> no thust --> thrust.

**Comment by SirMortimer** [comment]
Works for me... are you using some non-stock engines?

**Comment by TheRace** [comment]
It might have been on some of the engines from Unkerballed start. I'll try some stock engines as soon as I can.

**Comment by SirMortimer** [comment]
Unkerballed start just reorders the tech tree, it's what I'm using myself.

Just to make sure: do you see ignition counters and burn duration in the right click menu on the engine, but they don't change at all?

**Comment by TheRace** [comment]
Seems to only happen on one craft. Tried two different saves and three crafts (one was a test craft with all the engines), and it's just that one craft where it doesn't count down.
![20191022210352_1](https://user-images.githubusercontent.com/51422287/67325633-bfa6aa80-f515-11e9-9199-7893f31e7ee8.jpg)
![20191022210132_1](https://user-images.githubusercontent.com/51422287/67325634-bfa6aa80-f515-11e9-9791-b354fdf8682b.jpg)

Pictures are the craft in question between burns. 

Oh well

**Comment by SirMortimer** [comment]
That is very weird. It should work on all engines if it works on one, technically they are very much the same. Maybe something with ScrapYard, but I wouldn't know how...

Maybe there's something odd in the persisted state. Could you send me the save file (and tell me the name of the affected craft so I know what to look for)?

**Comment by TheRace** [comment]
https://www.dropbox.com/s/6dvfav5id9i4ie5/JNSQ.zip?dl=0

Ship is Scanimin. The one for scanning minmus
