### ISSUE TITLE
labels Mk1 pod "Unpressurized'

### ISSUE THREAD

**Issue by zer0Kerbal** [Kerbalism/Kerbalism#523]
```
// Unpressurized.cfg v1.1.1
// Kerbalism
// created: 24 Oct 19
// updated: 27 Oct 19

@PART[mk1pod,mk1pod_v2]:NEEDS[FeatureComfort]:FOR[FeatureComfort]
{
	@title ^= :(.)$:$0<color=red> (UNPRESSURIZED)</color> :
	@description ^= :Mk1:<i><color=red>unpressurized</color></i> Mk1:
}

// CC BY-NC-SA-4.0
// zer0Kerbal
```

**Comment by gotmachine** [comment]
Kerbalism is public domain. We don't accept licensed contributions.

**Comment by SirMortimer** [comment]
- `FOR[FeatureComfort]`should be replaced by `FOR[KERBALISM]`, I don't know if `FOR[FeatureComfort]` would even work.
- I wouldn't do it in a dedicated file, rather add the description and title bits to `System/Habitat.cfg` which is where the unpressurized config comes from. Keep it all in one place, that way we won't forget about it when it changes in the future.

**Comment by SirMortimer** [comment]
<img width="565" alt="description" src="https://user-images.githubusercontent.com/43166475/67640198-2b638b80-f8f9-11e9-94c3-ba1c2599c326.png">

That should do it.

**Comment by steamp0rt** [comment]
I kinda wanted to re-license Kerbalism under GPL in the past but that'd be a pain.

**Comment by zer0Kerbal** [comment]
> 
> 
> Kerbalism is public domain. We don't accept licensed contributions.

In order to protect myself (and to make sure there is a license) I always include one.
change it if you want, you have my permission.

**Comment by zer0Kerbal** [comment]
@SirMortimer it does work (the :FOR[]) but not perfectly. 
Thank you. most excellent. 👍 💯 :)
