### ISSUE TITLE
Issue with new sciense system

### ISSUE THREAD

**Issue by Stasboss19993** [Kerbalism/Kerbalism#524]
Hello. It great mod, i like new sciense. But I have some problem with experement "CHILLED" from sciense lab. "Not kerbin" even landed or low space on Minmus, Eve ect.

**Comment by SirMortimer** [comment]
That sounds like a problem that was either existing in 3.0.2, or manifested by having multiple conflicting configurations.

Easiest fix: delete the Kerbalism folders in your GameData (both of them), download [the latest dev build](https://github.com/Kerbalism/DevBuilds/releases) and use that. We're very close to a release, so you might as well use that.

**Comment by Stasboss19993** [comment]
thanks
