### ISSUE TITLE
battery depletion seems to anger the NaN kraken, fantom G force, the sun disappears

### ISSUE THREAD

**Issue by jinnturtle** [Kerbalism/Kerbalism#525]
### Info
* Playing with Realistic Progression One modpack.
* Playing on linux Ubuntu 18.04

### What happens
Took me some time to track this down, it seems when a probe (without means to generate power) runs out of power during high warp speed (>1000 I think) while I am in the KSC view, the battery icon starts showing NaN - perpetual (the probe was in low Earth orbit, don't know if that's relevant).
Next time a vessel is launched, once this new craft reaches space, it starts getting affected by an increasingly strong phantom force and spins, this continues for a few seconds until the vessel disintegrates due to high G. If I try to launch another vessel, when this new vessel reaches space, everything disappears and I'm staring into empty space, my funds go to 000000, etc. When back to KSC view, the sun is not there. If trying to load a game, the sun is still not there, sometimes the game crashes and linux reports a memory segmentation fault in the game process.

### How to restore
To restore things back to a sane state: the game has to be closed and restarted, persistent save files replaced with some earlier saves before loading the game. Unless the offending NaN vehicle is removed via the Tracking Centre, the situation repeats itself in similar fashion.

**Comment by gotmachine** [comment]
This is fixed since build 7237.
But thanks for the report.

**Comment by jinnturtle** [comment]
Oh, sorry for the noise then.
And thanks a million for the fix suggestion.
