### ISSUE TITLE
Control path readout shows part name, not vessel name

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#531]
See pic:
![Screen-2019-11-08_03-00-05](https://user-images.githubusercontent.com/29145213/68443381-fe09be00-01d3-11ea-9290-daceb3751dae.jpg)
The main UI Info tab shows the target as vessel name, the control path UI shows the target as part name.

**Comment by Gordon-Dry** [comment]
After the relay vessel was out of physics range, the readout changed to
IDCSP Relay 1-A (unloaded)
and was okay again...

**Comment by SirMortimer** [comment]
That looks a lot like another mod providing the comms to Kerbalism. RealAntennas, perhaps?

**Comment by Gordon-Dry** [comment]
Nope. RealAntennas in a stockish environemt is too much of a hassle right now.
But I got those:
https://forum.kerbalspaceprogram.com/index.php?/topic/177292-18-commnet-antennas-extension-commnet-antennas-info-2019-10-19/
In the thread the word "Kerbalism" is not mentioned once ... so I guess it should be okay.
No exceptions of any kind btw.

**Comment by Gordon-Dry** [comment]
Some confirmation:
![Screen-2019-11-22_00-45-50](https://user-images.githubusercontent.com/29145213/69386034-9bc7b780-0cc1-11ea-8c64-5613134e4cf6.jpg)
Also the word "unloaded" in brackets some times is uppercase and sometimes is lowercase...
Is there some duplicate code or why is that?

**Comment by SirMortimer** [comment]
This might be the culprit:

https://github.com/Kerbalism/Kerbalism/blob/c5bdcb83efb9ade95f0ef4b7596906b7e854be99/src/Kerbalism/Comms/AntennaInfoCommNet.cs#L243

I think we're supposed to use ``displayName`` here (see line 221)

Also, this replaces "Kerbin" in the name of any vessel in the path with "DSN"
