### ISSUE TITLE
bluedog_Apollo_Subsatellite_Core.cfg got multiple SolarPanelFixer modules

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#536]
GameData\Bluedog_DB\Parts\Apollo\bluedog_Apollo_Subsatellite_Core.cfg

This part got multiple ModuleDeployableSolarPanel and so it also got the same amount of
```
		MODULE
		{
			name = SolarPanelFixer
		}
```

I don't know if this is intended or not.

**Comment by gotmachine** [comment]
it is
