### ISSUE TITLE
bluedog_SmallSquarePanel_Static broken after launch

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#538]
This solar panel is just broken shortly after launch.
In LKO at 150km, even did not touch the belts.

Excerpt from MM cache:
```
UrlConfig
{
	parentUrl = Bluedog_DB/Parts/ProbeExpansion/SmallSquarePanel/bluedog_SmallSquarePanel_Static.cfg
	PART
	{
		name = bluedog_SmallSquarePanel_Static
		module = Part
		author = CobaltWolf
		rescaleFactor = 1
		node_attach = 0.0, 0.0, 0.0, -1.0, 0.0, 0.0
		TechRequired = engineering101
		entryCost = 1500
		cost = 100
		category = Electrical
		subcategory = 0
		title = HLR-SSQ Mini Solar Panel
		manufacturer = Bluedog Design Bureau
		description = A small, static photovoltaic panel for things that need a small amount of electricity.
		attachRules = 0,1,0,0,1
		mass = 0.003
		dragModelType = default
		maximum_drag = 0.2
		minimum_drag = 0.2
		angularDrag = 1
		crashTolerance = 8
		maxTemp = 1200
		thermalMassModifier = 2.0
		emissiveConstant = 0.95
		heatConductivity = 0.04
		bulkheadProfiles = srf
		tags = solar panel ec generator
		MODEL
		{
			model = Bluedog_DB/Parts/ProbeExpansion/SmallSquarePanel/bluedog_SmallSquarePanel_Static
		}
		MODULE
		{
			name = ModuleDeployableSolarPanel
			sunTracking = False
			raycastTransformName = sunCatcher
			pivotName = sunCatcher
			isBreakable = true
			resourceName = ElectricCharge
			chargeRate = 0.25
			retractable = true
			powerCurve
			{
				key = 206000000000 0 0 0
				key = 13599840256 1 0 0
				key = 68773560320 0.5 0 0
				key = 0 10 0 0
			}
		}
		MODULE
		{
			isEnabled = True
			name = BuoyancyControl
			enabled = true
		}
		MODULE
		{
			name = GeometryPartModule
		}
		MODULE
		{
			name = FARAeroPartModule
		}
		MODULE
		{
			name = FARPartModule
		}
		MODULE
		{
			name = SolarPanelFixer
		}
		MODULE
		{
			name = Reliability
			type = SolarPanelFixer
			title = Solar Panel
			redundancy = Power Generation
			repair = true
			mtbf = 36288000
			extra_cost = 2.5
			extra_mass = 1.0
			rated_radiation = 0.09
			radiation_decay_rate = 10
		}
	}
}
```

I guess other models are also affected.

**Comment by Gordon-Dry** [comment]
I had to repair a quicksave to fix it.

The affected ModuleDeployableSolarPanel
`deployState = BROKEN -> deployState = EXTENDED`
and SolarPanelFixer
`state = Broken -> state = Static`

**Comment by gotmachine** [comment]
There isn't any place in our code where we could be setting the `ModuleDeployableSolarPanel` to `deployState = BROKEN`, that can only happen due to **stock** solar panel failure when the panel is destroyed by atmo drag or collision, or if another mod is setting it (FAR maybe ?).

I will try to reproduce using only Kerbalism and BDB when I got some time.

**Comment by Gordon-Dry** [comment]
The last session (with - cough - KSP-IE also installed) was okay again.
But...
Next session I got KSP-IE removed.
Perhaps™ KSP-IE was the reason.
Still unconfirmed.

**Comment by Gordon-Dry** [comment]
It was not KSP-IE.
I uninstalled it 4 days ago.

Last session I had a launcher with that same panel 3x radially attached at the payload base.

They were just immediately broken after the fairing was jettisoned.
If I use other panels it does not happen (yet).

**Comment by SirMortimer** [comment]
I don't see how this could be caused by Kerbalism. Please reopen if this can be confirmed.
