### ISSUE TITLE
Electrical Consumption off the chart when using ResearchBodies.

### ISSUE THREAD

**Issue by Gora511** [Kerbalism/Kerbalism#539]
I have installed on Kerbalism and ResearchBodies. When using only Kerbalism, Electrical consumption in the Electrical Planner is showing consumption of .04 ec/sec. When combining with ResearchBodies, the electrical consumption jump to 12.08 ec/sec. 12.00 is comming from communication. When looking at the module of a probe core, it seems to be pointing to the electrical charge per packet.

Other Mods installed are dependencies of those two mods. However, if I remove strickly ResearchBodies, the problem goes away

**Comment by SirMortimer** [comment]
It's an issue with a broken config file that comes with ResearchBodies (see -> [here](https://github.com/JPLRepo/ResearchBodies/issues/48)).

Fix is to simply delete that file.

**Comment by SirMortimer** [comment]
Update: the FAQ has more details.

https://github.com/Kerbalism/Kerbalism/wiki/FAQ#q-my-probes-use-12-ecs-for-comms-and-die-within-seconds
