### ISSUE TITLE
[KSP 1.8.1] Mk1 pod doesn't have pressurization option after unlocking "Engineering 101"

### ISSUE THREAD

**Issue by RedshiftVelocities** [Kerbalism/Kerbalism#545]
The MK1 command pod (as well as the entire lineup of 1.25m crewed parts) are never upgraded to be pressurized. I'm running heavily modded install, so there might be some incompatibilities. Even in sandbox mode, those parts still show up as being unpressurized. Is this a bug? Deliberate feature? Thanks!

**Comment by AndresHdzArv** [comment]
I have the same issue, also modded, which mods do you have?

**Comment by RedshiftVelocities** [comment]
Quite a few; I can copy the list over in a bit.

**Comment by RedshiftVelocities** [comment]
Not in the most friendly format, but here ya go: [https://controlc.com/90da8e01](https://controlc.com/90da8e01)

**Comment by Cruesoe** [comment]
The MK1 pod is not supposed to ever be pressurised. I don't believe this is a bug but a feature meant to add to the challenge.
If you want a cosy pressured pod you'll need to use a bigger one!

**Comment by RedshiftVelocities** [comment]
Ah, ok. Thanks!
