### ISSUE TITLE
[KSP 1.8.1] [Kerbalism 3.1] PD3 Weather Station, deployable science error

### ISSUE THREAD

**Issue by Cruesoe** [Kerbalism/Kerbalism#546]
The weather station description implies an atmosphere is required to run and yet the science archive shows science can be collected from the Kerbin moons.

![Untitled](https://user-images.githubusercontent.com/49525542/69658455-2159b780-1074-11ea-97cf-539ed4b101f2.png)

**Comment by eberkain** [comment]
I tried it just to be sure and you cannot run the weather station on the mun.
