### ISSUE TITLE
ScanSAt altimetry scan automation does not work in timewarp ("only" science data provided)

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#547]
The "real" altimetry scan does not occur when in timewarp - also with low timewarp values. Only the Kerbalism science is provided then.

I have set automation parameters for the scanner.  When the scanner is enabled for a short data burst (HDD full in few seconds) while in timewarp then the altimetry map does never show a change.

But!
Before I decoupled the upper stage, I got double the HDD capacity (4 MB) and under these circumstances also with low timewarp the altimetry scan occured ...

When I slow down the timewarp before the free HDD capacity reaches 90% (the turn-on-trigger for ScanSAT altimetry scan) and watch in realtime, then it works.

Besides that,  the "Active Scanner Completion Percentage" sticks at 0%.
![Screen-2019-11-27_00-42-20](https://user-images.githubusercontent.com/29145213/69682418-9b5c6180-10b1-11ea-8a8f-c5de816fdc99.jpg)
Perhaps it changes after a scene change?

I'm sure that it "normally" shows the actual value. And ofc it could be that this is totally unrelated to Kerbalism.
But it also could be a hint to the above mentioned issue.

**Comment by Gordon-Dry** [comment]
After a scene change away from Minmus and back to the vessel the "Active Scanner Completion Percentage" still shows 0%.
Not sure if this should be a seperate issue or if it is related.

**Comment by Gordon-Dry** [comment]
btw, the CapCom info window for the associated contract shows the actual percentage of the altimetry scan.
So it could™ be that the 0% by-the-side-issue is NOT related to Kerbalism.

So focus back on the main issue.

**Comment by Gordon-Dry** [comment]
Update:
After I turned off the automation for the ScanSAT altimetry scanner to be triggered at low and high HDD capacity and just let it run and do the turning on and off itself - it worked again.

**Comment by Gordon-Dry** [comment]
And:
Also now the ScanSAT window shows the percentage!
There is a correlation somehow.

**Comment by SirMortimer** [comment]
> After a scene change away from Minmus and back to the vessel the "Active Scanner Completion Percentage" still shows 0%.

I think the key word here is "active". I guess at the time you looked at it, the SCANsat scanner was turned off, and that window only looks at the completion percentage of the scanners that are currently turned on - not of the map type that is being displayed.

I advise against using automation to turn a SCANsat scanner on and off again, that could conflict with how the integration works in Kerbalism.

Regarding the rest... here's

## How ScanSAT works under the hood

In a stock KSP game, SCANsat completely bypasses all data transmission while a probe is scanning a body and gernerating a map. The scanner part has a button that lets you generate data, it is that data you have to transmit back to Kerbin to get science points. But that is totally independent from the map generation itself. You can scan a body with a probe, never transmit anything back from that probe, and still see the map in the SCANsat windows.

I looked into the SCANsat code to search for ways to change that, can't be done. So we have to work around that.

Kerbalism always had special integration for SCANsat, before 3.0 it was used to turn SCANsat scanners off if there is no EC remaining on an unloaded vessel, and then back on again once EC is restored. The new science system does something similar.

There is a part module, KerbalismScansat, that acts as a bridge between Kerbalism and the SCANsat mod. What that part module does is: look at how much of the body has been scanned (in percent), and if the percentage went up, generate some data and store it. _How much_ data depends on _the difference in scan completion percentage_. Then, if the drive is full, it turn the scanner off until the drive is empty again.

This simulates the need to transmit data back before you can see a map, although technically it doesn't exactly work like that. If you're clever, you could just keep deleting the file on the hard drive of the probe, and the scanner would happily continue scanning without transmitting anything. But then you would loose the science points for the parrt that you deleted - forever, there is no way you can re-generate that data.

SCANsat updates it's scanners periodically at intervals. This means that depending on your current time warp speed, a probe could be scanning a big chunk of a body between two updates, which then would generate an enormeous amount of data in the drive, much much more than it can store. Kerbalism would turn the scanner off, wait until the data has been transmitted, and then turn it on again. At that point, whatever part of the body that happens to be in the view range of the probe at that point will be considered as scanned by SCANsat, which will likely lead to the next enormeous chunk of data being generated. There is no way to scan less, or to slow the scanner down any other way than turn it off and on again.

**Comment by Gordon-Dry** [comment]
I got it.
