### ISSUE TITLE
Info text "Configurable unmanned experiments" needs line break before it

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#553]
See
![Screen-2019-12-02_19-14-24](https://user-images.githubusercontent.com/29145213/69983930-22895980-1538-11ea-838f-1cbcce6d61e1.jpg)
![Screen-2019-12-02_19-14-37](https://user-images.githubusercontent.com/29145213/69983932-22895980-1538-11ea-9a8e-fac716443eed.jpg)
![Screen-2019-12-02_19-14-51](https://user-images.githubusercontent.com/29145213/69983933-22895980-1538-11ea-9af9-f2ce724bcb45.jpg)

**Comment by Gordon-Dry** [comment]
Or a hyphen.

**Comment by gotmachine** [comment]
That field was removed entirely
