### ISSUE TITLE
Science becomes permanently stuck inflight if vessel is destroyed

### ISSUE THREAD

**Issue by nateberkopec** [Kerbalism/Kerbalism#554]
Steps to reproduce:

1. Orbit with a Science 9001/Materials Study and the part that holds extra science data (forget the name).
2. Run the Materials Study experiment, transfer the resulting data/sample to the extra container.
3. Crash/destroy the craft.

The Materials Study science value for whatever biome you ran it in will still show up as "inflight".

**Comment by nateberkopec** [comment]
I'm not sure if this affects all science experiments or even if the step of transferring data is necessary, this is just a description of how I encountered the issue.

**Comment by nateberkopec** [comment]
I'm guessing this may be because [this callback](https://github.com/Kerbalism/Kerbalism/blob/155d2b02c947c285163b116ca0b1aa5f2dc84736/src/Kerbalism/Patches/VesselRecovery_OnVesselRecovered.cs#L79) is never called when the craft is completely destroyed?

**Comment by nateberkopec** [comment]
Ah, this seems likely. Maybe we need to attach to `onVesselTerminated` and/or `onVesselDestroy`?

**Comment by gotmachine** [comment]
I can't test right now but it is very unlikely that it is "permanently stuck", as the in flight data is recalculated from scratch on every deserialization/serialization cycle. Are you sure the parts are actually destroyed ? Data sitting on parts/vessels marked as "debris" will still count.

**Comment by nateberkopec** [comment]
> There can be some cases of the inflight science staying a while (until you go trough a reload / scene change) if it was on a vessel that was destroyed while unloaded. 

Hmm. Not the case for me, as the vessel was loaded when destroyed. I'll fire it up again tonight and try to learn more about the reproduction steps.

> the in flight data is recalculated from scratch on every deserialization/serialization cycle by iterating on all parts

Ah, where is this code?
