### ISSUE TITLE
Water recycling overproduces water

### ISSUE THREAD

**Issue by ccaviness** [Kerbalism/Kerbalism#557]
It seems water recycler is creating water. On a few crafts that I've put a water recycler on, I have a permanent surplus. I can start with half tank of water, and it will fill up over time.

In a test craft (MK1-3 Command pod, ECLSS configured for water recycling, supply container for waste, battery, solar panel), I show a continuous surplus of +0.028/h water.

Kerbalism shows "-0.067/h  drinking" and "+0.095/h  water recycler". I suspect this means the resource consumption/production is incorrect.

I've tested this with vanilla 1.8.1, Kerbalism 3.1 (release). SFS and KPS.log attached.

[water.zip](https://github.com/Kerbalism/Kerbalism/files/3942314/water.zip)

**Comment by ccaviness** [comment]
It looks like the water recycler process is set up correctly:
https://github.com/Kerbalism/Kerbalism/blob/155d2b02c947c285163b116ca0b1aa5f2dc84736/GameData/KerbalismConfig/Profiles/Default.cfg#L232
Not sure where the extra water is coming from.

**Comment by SirMortimer** [comment]
Can't reproduce.

- Cheated a Mk3 Cockpit with 4 Kerbals into orbit, with plenty of water, food and o2
- Added a empty tank for the surplus water and sewage
- Added a water recycler

Result: after 279 days, I've _lost_ 123 units of water.

**Comment by ccaviness** [comment]
Weird. I reproduced this twice in a completely vanilla 1.8.1 install. And it's still happening in my modded install.

I'll repro again, this time with video evidence. Maybe that will be enlightening.

**Comment by gotmachine** [comment]
> Kerbalism shows "-0.067/h drinking" and "+0.095/h water recycler". I suspect this means the resource consumption/production is incorrect.

Note that the "-0.067/h drinking" is an average, as drinking is a ~1-2 hours interval rule. This mean that when it happens, the water recycler will go full rate (because there is waste water to process), but it will likely stop before the next "drink".

**Comment by SirMortimer** [comment]
Just loaded your save game, and it doesn't show a full water tank for me
<img width="660" alt="waterworld" src="https://user-images.githubusercontent.com/43166475/70655281-434c6000-1c58-11ea-8663-e31289c4f880.png">
MET is 1d 5h, which could be consistent with my results (I have more crew on board)

**Comment by ccaviness** [comment]
> Note that the "-0.067/h drinking" is an average, as drinking is a ~1-2 hours interval rule. This mean that when it happens, the water recycler will go full rate (because there is waste water to process), but it will likely stop before the next "drink".

Ok, but what seems to be happening, at least on my vanilla 1.8.1 install, is the recycler kicks in when the first kerbal takes a drink, and stays on full-tilt, miraculously replenishing my water supply.

I've uploaded a video here: https://youtu.be/Av-h3PQa-K4 (should be higher res once YouTube processes further)

The recycler kicks in at 4:25, which is about 1h30 MET. After that, it stays on and the water supply steadily increases.

KSP.log and sfs files attached as well.
[water 2.zip](https://github.com/Kerbalism/Kerbalism/files/3952346/water.2.zip)
