### ISSUE TITLE
Surface sample results in logspam and severe lag. No progress is being made, despite timewarping.

### ISSUE THREAD

**Issue by jarmund** [Kerbalism/Kerbalism#562]
It appears that surface samples during EVA don't work when playing in science mode.
In career, I simply get an ingame-error saying requirements not met (as intended, I assume, seeing as I haven't upgraded any bulidings). However, in science (and probably sandbox, I have not tested), the logspam starts, preventing any progress from being made and reducing FPS to below 1.
I have not attemted a workaround, as I haven't messed around with KSP mods, but it sounds trivial to avoid this check when in science and sandbox.
The logspam:

```
[EXC 00:06:21.077] NullReferenceException: Object reference not set to an instance of an object
	KERBALISM.ExperimentRequirements.GetFacilityLevel (SpaceCenterFacility facility) (at <8a4e42ca56234bf4a928e828c42914e6>:0)
	KERBALISM.ExperimentRequirements.TestRequirements (Vessel v, KERBALISM.ExperimentRequirements+RequireResult[]& results, System.Boolean testAll) (at <8a4e42ca56234bf4a928e828c42914e6>:0)
	KERBALISM.Experiment.RunningUpdate (Vessel v, KERBALISM.VesselData vd, KERBALISM.Situation vs, KERBALISM.Experiment prefab, System.UInt32 hdId, System.Boolean didPrepare, System.Boolean isShrouded, KERBALISM.ResourceInfo ec, KERBALISM.VesselResources resources, System.Collections.Generic.List`1[T] resourceDefs, KERBALISM.ExperimentInfo expInfo, KERBALISM.Experiment+RunningState expState, System.Double elapsed_s, System.Int32& lastSituationId, System.Double& remainingSampleMass, KERBALISM.SubjectData& subjectData, System.String& mainIssue) (at <8a4e42ca56234bf4a928e828c42914e6>:0)
	KERBALISM.Experiment.FixedUpdate () (at <8a4e42ca56234bf4a928e828c42914e6>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

....repeated until surface sampling is stopped.

Happens regardless which mods are installed alongside kerbalism.
Using KSP version 1.8.1.2694, Modulemanager 4.1.3, and Kerbalism 3.1
[KSP/GameData/KerbalismConfig/Settings.cfg](https://github.com/Kerbalism/Kerbalism/files/3947584/Settings.cfg.txt)
[KSP/KSP.log](https://github.com/Kerbalism/Kerbalism/files/3947586/KSP.log)

**EDIT:** I forgot to add that this happens in both my main save and in a brand new save I made for tracking down this issue.

**Comment by SirMortimer** [comment]
Probably the same issue as #527 

Try with a dev build, that should fix it.

**Comment by SirMortimer** [comment]
But thanks for the report, I wished they all were as detailed :)

**Comment by jarmund** [comment]
I've been dealing enough with user written bug/fault reports that I know how impossible they are to deal with without details. I have so many NDA-affected examples I wish I could share.
Could you please provide me with a dev build, preferably a backwards compatible one? I don't have the tools necessary to build one myself.

**Comment by SirMortimer** [comment]
Dev builds can be found here -> https://github.com/Kerbalism/DevBuilds/releases

and they're compatible, too :)

**Comment by jarmund** [comment]
Neato, cheers!

**Comment by jarmund** [comment]
Confirmed fixed in build 7284. Time to dig some dirt!
