### ISSUE TITLE
Science over time makes (RP-1) start very difficult

### ISSUE THREAD

**Issue by nablabla** [Kerbalism/Kerbalism#569]
Hi, science experiments take time, ok I get that, But... reading a thermometer/barometer?
It makes it kind of impossible to collect science in the early game. I build a sounding rocket and can not get the initial science because it just takes to long and the rocket crashes. Could it be possible to reduce these mega-simple experiemnts time to something more conceivable like 5s ?

**Comment by Rockstar04** [comment]
I believe things like this need to be taken up with the maintainers of RP-1. 

https://github.com/KSP-RO/RP-0
https://github.com/Standecco/ROKerbalism

**Comment by gotmachine** [comment]
The default Kerbalism config pack is balanced for stock.
If you are talking about the ROKerbalism config pack, please refer to Rockstar04 comment.
