### ISSUE TITLE
Later enhancement: CommnetConstellation taken into account

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#57]
This is an enhancement request for later.

The signal fixes are working.
And they don't create issues when Commnet Constellations is installed - afaik.
But they use stock methods how a connection occurs - I guess.

If that what the Kerbalism.dll "sees" is what CommnetConstellation has already changed then it's okay.

But I don't know.

Especially that with CommnetConstellation different antennas on the same vessel can have different channels on which they transfer is something that Kerbalism just cannot see when all combinable antennas are just combined in a stockalike manner.

In some edge case, when the antennas are combined in a stockalike fashion, they would have a connection to KSC.
But with CommnetConstellation it could be that a direct connection to KSC is not possible by combining DIRECT antennas, but for example one relay antenna has a direct connection to another relay antenna in stationary orbit around Kerbin.
That would mean that the transfer quality and speed only depends this specific relay antenna - and even more specific - the relay antenna on the target relay satellite and then the DIRECT antenna that is transmitting from the satellite to KSC.

I don't know if these parameters of unloaded vessels can be seen by Kerbalism or if CommnetConstellation itself provides some API for this.

But it would be great if Kerbalism just does not only assume stockalike connections over the Commnet but the real connections as established by CommnetConstellation.

https://github.com/KSP-TaxiService/CommNetConstellation

**Comment by SirMortimer** [comment]
CommNetConstellations could use the same comms API that is being used by realism overhaul, and  internally by RT. Kerbalism adding code to support other 3rd party comm mods isn't going to happen because it cannot be maintained.
