### ISSUE TITLE
mk2 inline cockpit issues

### ISSUE THREAD

**Issue by Its-Just-Luci** [Kerbalism/Kerbalism#572]
Something in the mk2 inline cockpit is drawing 12 units of electricity per second with all systems turned off.

**Comment by lordcirth** [comment]
Sounds like a mod conflict. Please list the mods you have installed.

**Comment by gotmachine** [comment]
see https://github.com/Kerbalism/Kerbalism/issues/539

**Comment by SirMortimer** [comment]
also, see https://github.com/JPLRepo/ResearchBodies/issues/48
