### ISSUE TITLE
Feature Request - inverse square law for reactor radiation

### ISSUE THREAD

**Issue by sashan13** [Kerbalism/Kerbalism#579]
So, I've got a bit of a problem with nuclear reactors and other emitters. They seem to give my Kerbals same doses regardless of where are they on the craft. A reactor 200 meters away is orders of magnitude safer than the one pressed right next to the crew can.
**Solution**: implement inverse square law when calculating exposure rate from a reactor. I think calculating distances between each crewed part and each emitter would be practical. Update rate can be really low anyways.
Calculating shielding by e.g. fuel tanks and other heavy parts would be good but may be too complex to implement. 
Mod version: latest for KSP 1.7

**Comment by SirMortimer** [comment]
It already works that way. See the following screenshots that I took, for comparison. Note the radiation in the (unshielded) habitat is lower (0.7 millirads) with a long truss between the reactor and the capsule, vs. 0.064 rads (= 64 millirads) without the truss.
![rad1](https://user-images.githubusercontent.com/43166475/73080504-37de8c80-3ec6-11ea-95b6-fa82de9e5845.png)
![rad2](https://user-images.githubusercontent.com/43166475/73080505-38772300-3ec6-11ea-89a3-700eb6fdcc1d.png)
