### ISSUE TITLE
Aurtomation : add high/low orbit triggers

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#58]
Add the following auto triggers to the UI:

- low orbit
- high orbit

**Comment by SirMortimer** [comment]
What's the use case? Starting/Stopping experiments? (This is now done differently)

I'd rather not add additional auto triggers to the UI, especially not for situations. The list of triggers already is quite long (20 entries), and currently you just can click through them one by one. We should get a better UI for that, something with a tree view maybe. But we don't have a tree.
