### ISSUE TITLE
Consistent crash 10-20 seconds after entering save.

### ISSUE THREAD

**Issue by HorizonFulcrum** [Kerbalism/Kerbalism#585]
Consistent crash when entering any save. Occurs 10-20 seconds after entering. Clean install, Kerbalism only: Kerbalism, Kerbalism-config and Community Resource Pack. Log is attached.
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4101346/KSP.log)

**Comment by gotmachine** [comment]
Thanks for the report.
This has already been fixed in this commit : ea29f97d8c1031508f32817da2cb2aa8f01e5220
I suggest to get the latest dev build here : https://github.com/Kerbalism/DevBuilds/releases
