### ISSUE TITLE
SSTU Issues

### ISSUE THREAD

**Issue by Its-Just-Luci** [Kerbalism/Kerbalism#586]
SSTU station modules seem to be "compatible" with kerbalism, yet for some reason they appear to have no internal volume or surface area

**Comment by gotmachine** [comment]
Works for me with SSTU 0.11.49.161, KSP 1.7.3 and Kerbalism 3.2 release
Please provide your `KSP.log` and `GameData\ModuleManage.ConfigCache` files.
