### ISSUE TITLE
Better part models

### ISSUE THREAD

**Issue by gotmachine** [Kerbalism/Kerbalism#593]
Fore reference, those are the current parts : https://imgur.com/a/V7lhPiS
List of what could be nice to have with custom, unified style models:
- [x] Stack cylindrical configurable "service module"
  - [x] Store configurable small amounts of life support related resources (food, water, oxygen, nitrogen, hydrogen, monoprop)
  - [x] And configurable LS processes like pressure control, scrubber, water / waste recyclers, fuel cells
  - [x] A radially jettisonable shroud could be nice (like the useless MH service bays)
  - [x] Alternatively, have two 2 model variants, one "aerodynamic worthy" and one with exposed machinery/tanks/containers
  - [x] Otherwise, plain and simple aerodynamic cylinder with maybe a few details
  - [x] Relatively flat : a bit longer than the stock reaction wheels maybe.
  - [x] 0.625m x ~0.2m
  - [x] 1.25m x ~0.3m
  - [x] 2.5m x ~0.6m
  - [ ] A 1.875m version could be nice
- [x] Radial configurable supply containers :
  - [x] For storing life support resources : food, water, waste
  - [x] Space worthy looking (no "bags") : something that would look good radially attached to habitats or even pod parts
  - [x] Rectangular (or maybe a slightly trapezoid / slanted section) with something like a 0.33 x 0.33 x 1.0 ratio
  - [x] Maybe 4 lengths (based on the above ratio) : 0.4m, 0.8m, 1.6m, 3.2m
- [x] Radial general purpose gases/liquids tanks
  - [x] For oxygen/hydrogen/ammonia/CO2
  - [ ] maybe monoprop too
  - [x] Design wise, something like the stock radial MP tanks should be good
  - [x] Preferably cylindrical, but an additional set of spherical ones can be nice
  - [x] Diameters : 0.15 / 0.30/ 0.60 / 1.0
- [x] Stack general general purpose supply containers :
  - [x] Plain and simple flat cylinders, same sizes as the service modules
  - [x] Match the design of the radial supply containers
  - [x] For storing food/water/wastewater/waste, etc
  - [x] 0.625/1.25/2.5/3.75 m
- [ ] Chemical Processor Unit (replacement for the scaled down stock convert-o-tron)
  - [ ] 3 sizes for 1, 2 or 3 different processes
  - [ ] surface attachable
  - [ ] Design: space-exposed machinery, this is intended to sit in a service bay or fairing
  - [ ] optional: different models to distinguish the processes, by texture or/and shape (WaterElectrolysis, Sabatier, Haber, WasteIncinerator, Anthraquinone, HydrazineProduction, NitroHydrazine, MRE, SCO, SOE)

**Comment by SirMortimer** [comment]
The geiger counter needs to be looked at, too. Depending on where you place it, it has a tendency to be clipped inside the parent part so that it no longer is visible. It's probably a simple configuration change, but I don't know the first thing about parts :(

**Comment by lordcirth** [comment]
If parts are to be remodelled, it would make the most sense to make them as close to the Restock parts as possible, for consistency.

**Comment by Arkolis** [comment]
Got, Here is my list of parts I'm working on if more are needed/wanted let me know or post it here. List does not include parts already listed above.
X-Done
P- Prototype

-- Parts --
Ring habitat
Greenhouse
Atmospheric Extractor
Oceanic Pumps

-- Custom Science Part - Multiple experiments --
	 X	BEEP - Biome Exclusive Experiment Package
	 X	DING - Dynamic investigation of Null Gravity			-Currently on restock survey scanner
	 X	TICK - Transmissible investigation of cosmic knowledge	-Currently on restock survey scanner
	 X	WING - Wandering Investigation Not on the Ground
Curve - Checking Undulating Radial Vectors of Environment: Checking roundness of the atmosphere
CLOUD - Cumulative Longitudinal Overland Understating of Dynamic - Aircraft experiment

**Comment by SirMortimer** [comment]
I suggest we do this via issues on the Parts project - see there: https://github.com/Kerbalism/Parts/issues

Makes it easier to track progress and discuss.
