### ISSUE TITLE
Default Config - CKAN

### ISSUE THREAD

**Issue by YpsilonTM** [Kerbalism/Kerbalism#601]
As soon as I check Default Config in CKAN I can't apply the changes. If uncheck it and install. It asks wich config I like to choose default is not one of them.
![ckan_VRe7ipJ0QW](https://user-images.githubusercontent.com/22861150/74084960-866a5a00-4a74-11ea-8b58-617343ac32fa.png)

Edit: Well It didn't show but now I saw it. Its not a Kerbalism fault. this is the reason.
![ckan_fKaHsMwE3C](https://user-images.githubusercontent.com/22861150/74085039-68512980-4a75-11ea-9c87-059b2bd3d2c6.png)
But maybe handy you guys know these 2 are conflicting

**Comment by gotmachine** [comment]
Make sure you don't have an incompatible mod installed : 
![image](https://user-images.githubusercontent.com/24925209/74085034-61c2b200-4a75-11ea-837e-1fad631c1f87.png)

**Comment by YpsilonTM** [comment]
@gotmachine My apologies for posting to fast should have digged a little deeper. You are right those 2 conflict.

**Comment by YpsilonTM** [comment]
One thing though: Since those 2 conflict it's not possible to install DeepFreeze. Just to let you know because Kerbalism's info states: Works with DeepFreeze

xxx Greetz Ypsilon

**Comment by gotmachine** [comment]
Yep, it's because the DeepFreeze ckan entry list BackgroundResources as a dependency, but it should be a recommendation. It isn't required for DeepFreeze to work.

**Comment by YpsilonTM** [comment]
Well I opened up an issue in the DeepFreeze CKAN so they maybe can change it.
[Issue 96 - DeepFreeze](https://github.com/JPLRepo/DeepFreeze/issues/96)
