### ISSUE TITLE
Hiding vessels from the vessel list

### ISSUE THREAD

**Issue by tivec** [Kerbalism/Kerbalism#602]
I propose adding a "hidden" category from the vessel list, similar to the default filters. A vessel could be hidden via its CFG page, and found in a similar fashion as for toggling visible groups. This could help for when people have a lot of communications satellites or contract satellites that don't need to be monitored cluttering up the list.

**Comment by eberkain** [comment]
Adding a couple customizable categories might be a better alternative so we could apply our own label and icon to a category.  I have wanted a separate category for GPS satellites in the past.

**Comment by tivec** [comment]
I remember that the vessel categories were hard coded as an enum in previous versions of KSP, so it is most probably not going to be possible to add own labels that easily - unless Kerbalism adds an interface for this for their own windows :)

**Comment by SirMortimer** [comment]
In the CFG tab, there's a new option to hide a vessel from the vessel ist. Hidden vessels are (surprisingly) hidden by default, unless you click the new filter icon to the bottom right (that currently looks like a sun but might change shape once the need for a better icon arises).

<img width="381" alt="hidden1" src="https://user-images.githubusercontent.com/43166475/74633513-12aa0a80-5162-11ea-97f3-6e8892050113.png">

<img width="388" alt="hidden2" src="https://user-images.githubusercontent.com/43166475/74633523-176ebe80-5162-11ea-95e7-ae8fbd23f259.png">

**Comment by tivec** [comment]
As for icon, you could use https://game-icons.net/1x1/lorc/interdiction.html or something along those lines. Or a satellite with a slash over it, or something along those lines.

The mod Haystack Continued (https://forum.kerbalspaceprogram.com/index.php?/topic/81114-12-2016-10-28-haystack-continued-v0521/) has a button to manage hidden vessels.
