### ISSUE TITLE
Life Support Resource Bug

### ISSUE THREAD

**Issue by Jesse931** [Kerbalism/Kerbalism#605]
After playing around with the new update, I've noticed a bug in how Food and Water (and possibly electricity, though I haven't checked) are handled. Specifically, the kerbal, when going on EVA, takes Food and Water with them (note that the kerbal has 1.35 units of food and 0.7 units of water, but there were only 1.22 units of food and NO water in the capsule):
![image](https://user-images.githubusercontent.com/29842927/74711154-42ecba00-51f1-11ea-8989-92ddecb967e3.png)
![image](https://user-images.githubusercontent.com/29842927/74711075-15077580-51f1-11ea-80b3-522fa824884b.png)

Food and water is removed from the vessel (there is water in the vessel because a fuel cell is running, not because of any further issues):
![image](https://user-images.githubusercontent.com/29842927/74711059-0c16a400-51f1-11ea-9758-7c1183c1c08a.png)

But when the kerbal returns to the pod, all food and water on the kerbal is re-added to the ship:
![image](https://user-images.githubusercontent.com/29842927/74711186-5e57c500-51f1-11ea-9dbc-f208613db309.png)

Now the ship has an additional 0.13 units of food, and _full_ water, for 1.35 and 0.7 units respectively.

Steps to reproduce:

1. Spawn in a ship with a crewed command module (I haven't tested if this is only an issue with the Mk1 Command Pod)
2. Allow time to pass (enough for food/water to be consumed)
3. EVA kerbal
4. Re-enter the command pod

If you need any more information, I'm happy to provide it.

**Comment by SirMortimer** [comment]
Kerbalism checked for parts with name `kerbalEVA` or `kerbalEVAfemale` - which broke when Squad added other suit variants (vintage, future). Now we check for the KerbalEVA part module instead, which should be pretty robust.
