### ISSUE TITLE
1.9.0 Support

### ISSUE THREAD

**Issue by Fearaniar** [Kerbalism/Kerbalism#607]
It doesn't seem like the new version of KSP is utilizing the resources of Kerbalism.

In KSP's GameData Folder:

-CommunityResourcePack
-Kerbalism
-KerbalismConfig
-Squad
-SquadExpansion
-ModuleManager.4.1.3
-and everything else associated with ModuleManager...

Everything--I believe--is up to date and nothing else has been modified. And I do have both KSP expansions.

So when I go into the VAB or SPH and bring up a resource supply part--like those for food, water, oxygen etc...--it doesn't actually contain anything, and there's no extra information on the parts either. For any of the kerbalized command modules, no information on life support is provided and no shielding can be applied. And it doesn't look like anything of Kerbalism is really utilized in flight.

I do believe the mod is installed correctly, and this problem resolves resolves itself if I were to switch back to KSP-1.8.1.

I've never tried CKAN before, but I might give it a go and see if that somehow fixes things because I don't see anyone else here with this issue...

At any rate, I love the mod, and just wanted to see if I could get compatibility for 1.9.0!

**Comment by gotmachine** [comment]
Please upload your KSP.log file

**Comment by Fearaniar** [comment]
So I'm a little new to all of this, where can I find the log file?

**Comment by gotmachine** [comment]
In your KSP installation folder, next to KSP_x64.exe (assuming you're on windows)

**Comment by Fearaniar** [comment]
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/4227732/KSP.log)

**Comment by Fearaniar** [comment]
Umm... I didn't mean to hit the comment and close. Anyhow, I think that's the file you're looking for?

**Comment by gotmachine** [comment]
The Kerbalism\KerbalismBootstrap.dll seem to be missing.
I suggest deleting both Kerbalism and KerbalismConfig and reinstalling them from a fresh download.

**Comment by Fearaniar** [comment]
Same problem. So I'm downloading from Github itself and copy/pasting from the GameData folder in Kerbalism-master to the GameData in KSP.

**Comment by gotmachine** [comment]
The repository doesn't have the binaries. Downloads are here :
https://github.com/Kerbalism/Kerbalism/releases

**Comment by Fearaniar** [comment]
Just had the same idea, I was getting the zip from the main page from from the Clone or Download button. Trying it out now with the new--hopefully functional--files.

**Comment by Fearaniar** [comment]
Ah... Wonderful! Thank you sir for teaching me a little about Github and for putting up with my ramblings. I'll soon be off to play KSP again!

**Comment by gotmachine** [comment]
Good play-session then, don't kill too many Kerbals :)

**Comment by Fearaniar** [comment]
Well... let's not go on and make any assumptions now! ;)
