### ISSUE TITLE
Lacking module upgrades when using simplex tech tree 

### ISSUE THREAD

**Issue by alaricmiranda** [Kerbalism/Kerbalism#614]
even with a fully unlocked tech tree with the recommended mod . some module upgrades are not unlocked . i can confirm that waste processor  and water recycler are not obtained .checked without the mod and i had it.

**Comment by alaricmiranda** [comment]
If required the other mods im using are Kerbal engineering redux , KIS,kerbal alarm clock and mechjeb

**Comment by SirMortimer** [comment]
Frankly, I won't investigate this for too much since we decided to abandon all upgrades in 4.0 - there are just too many issues related to upgrades. Please have patience, it will be a while.
