### ISSUE TITLE
Russian translation for Kerbalism 3.7

### ISSUE THREAD

**Issue by Unyo13** [Kerbalism/Kerbalism#617]
[ru.zip](https://github.com/Kerbalism/Kerbalism/files/4350296/ru.zip)

**Comment by Unyo13** [comment]
[ru_Config.zip](https://github.com/Kerbalism/Kerbalism/files/4350352/ru_Config.zip)
And Kerbalism Config with translated lines for enriched Uranium.

**Comment by SirMortimer** [comment]
Added to the dev branch, thanks!
