### ISSUE TITLE
Kerbalism doesn't play nice with TestFlight

### ISSUE THREAD

**Issue by c-lipka** [Kerbalism/Kerbalism#625]
When the TestFlight engine reliability mod is installed, Kerbalism's own reliability stuff stops working properly - not sure to what extent, but at the very least it doesn't show the reliability section in the PAW anymore (tested with KSP 1.9.1). Note that this applies to all parts, not just engines, and even when Kerbalism engine failures are turned off.

Some suggestions for how to deal with this issue:

(a) Fix it, so that the more in-depth TestFlight reliability model can be used for engines, while Kerbalism's much broader reliability model can be used for all the other stuff.

(b) Leave it, and officially declare TestFlight incompatible with Kerbalism in CKAN and on the Mod Compatibility wiki page.

(c) Leave it, and just mention this limitation on the Mod Compatibility wiki page.

(d) Extend Kerbalism's reliability model, so that people won't itch to mix & match reliability models in the first place.

(e) Ignore the issue entirely, because who would try to mix & match reliability models anyway.

**Comment by SirMortimer** [comment]
Kerbalism disabled the reliability feature when TestFlight is installed, this was hard coded before 4.0. In the future, this type of hard coded validation will no longer be done.
