### ISSUE TITLE
Ground experiments does not work with "Science = false"

### ISSUE THREAD

**Issue by basilicofresco** [Kerbalism/Kerbalism#628]
Hi! I noticed that with Breaking Ground expansion if I set "Science = false" in Settings.cfg then the transmission of ground experiments does not work. The signal is strong, Kerbol is shining over the solar panels, but sadly science transmitted remains 0%.

I tried with a clean installation with just KSP 1.9.1.2788 + Breaking Ground 1.4.1 + Kerbalism 3.7 and the problem is still present in career and science mode. It's worth to mention that if change the settings to "Science = true", then the transmission occours as soon I restart the game.

Can you confirm it? Is there a workaround?

![temp1](https://user-images.githubusercontent.com/31368421/81064204-8f36c480-8ed9-11ea-8c96-504d18347e1d.png)

I attached the savegame of the clean installation: [bf.zip](https://github.com/Kerbalism/Kerbalism/files/4580610/bf.zip)

**Comment by gotmachine** [comment]
Will be fixed in next release
