### ISSUE TITLE
waste compressor as waste incinerator

### ISSUE THREAD

**Issue by WojtekTrz** [Kerbalism/Kerbalism#631]
Waste compressor is described as waste incinerator. I think problem is here:
Please update the profile default.cfg

MODULE
		{
			name = ProcessController
			resource = _WasteCompressor
			title = Waste incinerator
			capacity = 2
		}

**Comment by gotmachine** [comment]
Are you suing the latest version (3.7) ?
This seems already fixed to me.

**Comment by WojtekTrz** [comment]
You are right. Sorry! That is in 3.4 which I use.
