### ISSUE TITLE
Researchbodies

### ISSUE THREAD

**Issue by EasyAce** [Kerbalism/Kerbalism#633]
The issue is described well enough, with a workaround, in the FAQ - but Research Bodies are not added to the compability list.

I suggest adding it to the wiki/compability list as uncompatible or compatible with some adjustments. (mine works fine as long as I delete the cgf file.)

**Comment by SirMortimer** [comment]
You are supposed to get a warning message about ResearchBodies in game pointing you to the FAQ.

**Comment by SirMortimer** [comment]
I've updated the wiki. Let's hope https://github.com/JPLRepo/ResearchBodies/issues/48 will get fixed.
