### ISSUE TITLE
[QUESTION] Does it work with Principa ?

### ISSUE THREAD

**Issue by Tutul-** [Kerbalism/Kerbalism#637]
I don't ask for explicit support as it may be a lot of works and your support is already amazing :-D
I'm not sure I'll try Principa either but if I do, I want to now if Kerbalism may work with it. As sphere of influence are override and body aren't exactly where they use to (with orbit variation too).

Thanks for your amazing work btw ^^

**Comment by SirMortimer** [comment]
While gravity with principia does not depend on the Sphere of Influence (SoI), science experiments still do. Principia doesn't remove the SoIs, it just renders them irrelevant for gravity. All other stock mechanics still work as without principia.

So yes, it works with principia.

**Comment by Tutul-** [comment]
That really nice to hear. I may try some BDSM during lockdown then :-D

Le lun. 18 mai 2020 à 18:14, SirMortimer <notifications@github.com> a
écrit :
