### ISSUE TITLE
Parts unassembled when in orbit or after a long time warp.

### ISSUE THREAD

**Issue by NachoAyala** [Kerbalism/Kerbalism#647]
Hello guys:

I love KSP and I love Kerbalism. Probably the best MOD ever, multiplies the reward of archieving things by 10. But I haven't been able to enjoy it completelly. The parts of any ship I launch to space are twisted and dissaligned after some time in orbit or after some longs time warps. (Would you need a screenshot?) It is a visual glitch, but also a gameplay issue, since the center of mass is moved, and long injections can't be done propperly. I have KSP bought legally, plus all the DLCs and everything is updated, game and mods, to 1.9.1. Is there any sollution? Thanks for creating and keeping this lovely mod.

**Comment by gotmachine** [comment]
In my experience, this sometimes happens in stock without any mod.

This said, Kerbalism can cause a bit of extra CPU pressure on scene switches, and that can increase the frequency of such physics issues, in particular if you have changed the "Max physics delta-time per frame" KSP settings. 

Always let that setting to the default 0.04 value :
![image](https://user-images.githubusercontent.com/24925209/84543884-85845600-acfc-11ea-8874-6e2850a16da0.png)

**Comment by NachoAyala** [comment]
Thanks! I will try that! :D Some people on the Kerbal Facebook page suggested that the problem is not Kerbalism related, but I think I remember that it has been always solved uninstalling Kerbalism. Dunno, will try.
