### ISSUE TITLE
Issues with patch to Near future electrical

### ISSUE THREAD

**Issue by alaricmiranda** [Kerbalism/Kerbalism#652]
Kerbalism  chnages the NFE working , Noticed this with the low end reactor and tested multiple times . on restarting the game a vessel with the reactor needs to be loaded . if not they do not initialize and dont generate power . if a new vessel is launched with a reactor but it hasnt been configured to dump the required materials properly it seems to disable the ones on the other vessels too .even if not in range . fixing the reactor on current vessel and getting it working fixes it on all .
Edit:even changing the dump to something that wont work on a working reactor causes rest to stop .changing it back again fixes the problem .please note only tested this with same model reactor on all vessels .

**Comment by woeller** [comment]
The same problem also occurs with USI reactors

**Comment by gotmachine** [comment]
Yep dump settings are a bit buggy. See #500
