### ISSUE TITLE
Comet sample experiment not working

### ISSUE THREAD

**Issue by chwelves** [Kerbalism/Kerbalism#654]
On EVA, taking a sample from a comet doesn't do anything. A System.nullreferenceexception always appears at the console log whenever i try to click so.
Here's a screenshot clicking the "take sample" while on EVA at Henberry 1 comet.

![20200815145843_1](https://user-images.githubusercontent.com/69492455/90308403-ddfced00-df11-11ea-8f27-05b0bb5a9a29.jpg)
![20200815145923_1](https://user-images.githubusercontent.com/69492455/90308409-e35a3780-df11-11ea-8028-47e90b0d8d00.jpg)

But testing the sample experiment on asteroid work fine though

[KSP.zip](https://github.com/Kerbalism/Kerbalism/files/5078309/KSP.zip)
[persistent.zip](https://github.com/Kerbalism/Kerbalism/files/5078349/persistent.zip)
[ModuleManager.zip](https://github.com/Kerbalism/Kerbalism/files/5078352/ModuleManager.zip)

**Comment by OnlyLightMatters** [comment]
I can confirm the issue.
