### ISSUE TITLE
[3.10] Engine reliability appears broken

### ISSUE THREAD

**Issue by BTAxis** [Kerbalism/Kerbalism#656]
Since moving from Kerbalism 3.9 to 3.10, I've noticed that engine reliability doesn't work right anymore. On some ships, the amount of ignitions never decreases while on others it does. Possibly this is related to the engine quality, though I can't say so with certainty. On ALL ships, burn time doesn't decrease while the engine is active, though it does decrease briefly when the engine is ignited, usually by just 1 second.

I have tried reverting back to 3.9, and reliability worked as expected again.

I play on KSP 1.9.1. I do also run a good number of other mods, so I can't rule out interference from another mod, but I've switched Kerbalism versions a couple of times and the behavior described above stands.

**Comment by DarthPointer** [comment]
This is all about Kerbalsm 3.10. See #655.

**Comment by SirMortimer** [comment]
Fixed.
