### ISSUE TITLE
NullReferenceException in KERBALISM.ProcessController.Update () every 30 ms

### ISSUE THREAD

**Issue by maehluml** [Kerbalism/Kerbalism#659]
Getting these every 30 ms when loading a crewed craft.
`[EXC 23:34:54.394] NullReferenceException: Object reference not set to an instance of an object
	KERBALISM.ProcessController.Update () (at <44d2b28eb09144efbf56dab50bc4321b>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 23:34:54.423] NullReferenceException: Object reference not set to an instance of an object
	KERBALISM.ProcessController.Update () (at <44d2b28eb09144efbf56dab50bc4321b>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[EXC 23:34:54.452] NullReferenceException: Object reference not set to an instance of an object
	KERBALISM.ProcessController.Update () (at <44d2b28eb09144efbf56dab50bc4321b>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

GameData folder:

000_AT_Utils
000_ClickThroughBlocker
001_ToolbarControl
AdjustableModPanel
AngleCanMods
AstronomersVisualPack
B9PartSwitch
BetterTimeWarp
BonVoyage
CommNetAntennasExtension
CommunityCategoryKit
CommunityResourcePack
ContractConfigurator
ContractPacks
DeployableEngines
DistantObject
DynamicBatteryStorage
EditorExtensionsRedux
EnvironmentalVisualEnhancements
EVARefueling
ExtraplanetaryLaunchpads
Hangar
HotSpot
JSI
KAS
KerbalChangeLog
KerbalEngineer
KerbalInventorySystemNoFun
Kerbalism
KerbalismConfig
KerbalJointReinforcement
Kethane
KGEx
KIS
KspCraftOrganizer
ManeuverNodeSplitter
MechJeb2
ModRocketSys
ModuleManager.4.1.4.dll
ModuleManager.ConfigCache
ModuleManager.ConfigSHA
ModuleManager.Physics
ModuleManager.TechTree
NavyFish
NearFutureConstruction
NearFutureElectrical
NearFutureExploration
NearFutureLaunchVehicles
NearFutureProps
NearFuturePropulsion
NearFutureSolar
NearFutureSpacecraft
NehemiahInc
OrbitalColony
PlanetaryBaseInc
RealChute
RemoteTechRedev
ReStock
ReStockPlus
SCANsat
scatterer
ScienceAlert
SHED
Sigma
SmartParts
SolarScience
SpaceTuxLibrary
Squad
SquadExpansion
StationPartsExpansionRedux
SurfaceLights
TacFuelBalancer
TextureReplacer
Trajectories
TriggerTech
UniversalStorage2
VentralDrill
ZeroMiniAVC

**Comment by SirMortimer** [comment]
Do you have the full KSP.log file for that issue? Can't really tell much without the complete file

**Comment by gotmachine** [comment]
Can't help without more info.
