### ISSUE TITLE
3.1.1 & Dev-7575: part with ModuleDeployableSolarPanel AND ModuleDataTransmitter planner issue

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#672]
On parts where I can toggle on the PAW in VAB/SPH the button for "Solar panel output" and "Simulate transmitter in planner" I have this issue:

1. toggling "Solar panel output" works flawless when "Simulate transmitter in planner" is on
2. toggling "Solar panel output" on does not show "produced" in planner when "Simulate transmitter in planner" is off

It could be that the planner decides to show no production when there is no consumption.
But this is very confusing, the planner should show the EC input also when no consumption is simulated.

**Comment by gotmachine** [comment]
The planner is in a very WIP state as of 7575.
