### ISSUE TITLE
Unloaded Relays appear to be offline

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#674]
Lander on Minmus relaying signal through relay orbiter. The orbiter is offline to Kerbalism, but online to KSP (green lines in map view, but Kerbalism says offline). Resulting in zero bandwidth for the lander.

Switching to the orbiter instantly sets it to online, and data transmission from the lander resumes.

**Comment by gotmachine** [comment]
I can't reproduce it right now. Will keep an eye on that, but if you are able to reproduce it consistently, a save would help...

**Comment by gotmachine** [comment]
Issues for 4.0 now belong in the 4.0 repo
