### ISSUE TITLE
Universal Storage II Material Bay "Toggle Door" Issue

### ISSUE THREAD

**Issue by kimcoin92** [Kerbalism/Kerbalism#679]
When i play with USii only, it can to rip off the bay door and experiment without door inside fairing. but Kerbalism can't. I tried to fix myself but failed
check the cfg, maybe relate with "Greeble"

**Comment by kimcoin92** [comment]
Finally fixed problem, but i hope to add it for next patch.

@PART[USMatBayWedge]:NEEDS[UniversalStorage2,FeatureScience]:AFTER[zzzKerbalismDefault]
{
    @MODULE[Experiment]
    {
        anim_deploy = BayDoorOpen
    }
	
	MODULE
	{
	name = USModuleGreeble
	AllowGreebleToggle = true
	GreebleToggleName = Toggle Door
	GreebleTransform = Greebles
	}
}

**Comment by gotmachine** [comment]
see #668
