### ISSUE TITLE
Impossible to play in Career Mode

### ISSUE THREAD

**Issue by Shinribo** [Kerbalism/Kerbalism#681]
I started to play Career mode but bc the start command pot is not airtight, jeb dies when i try to leave the atmosphere (jebs spacesuit has no oxygen either) and i can only reach the 2.5m command pot (which is airtight) when i go to space and do science

**Comment by Shinribo** [comment]
![KSP_Mod Liste](https://user-images.githubusercontent.com/73356576/97030530-2c0c1d80-155f-11eb-9a10-3bcc7587ac90.png)
These are my Installed Mods

**Comment by lordcirth** [comment]
I see that you have Community Tech Tree but not many other mods. It's been a while since I played without Unkerballed Start. What path did you take through the tree? Did you unlock Goo and Mat Bay? Mat Bay gives a ton of science, and you can do it in space without a Kerbal.

**Comment by Shinribo** [comment]
I never used unmanned reseach vessels, so thanks for the idea and it could be a feature if kerbals wear their suit in unpressurized modules
