### ISSUE TITLE
Kerbalism save game load has failed

### ISSUE THREAD

**Issue by N3w0nee** [Kerbalism/Kerbalism#682]
![image](https://user-images.githubusercontent.com/35236187/97107756-80331100-16c9-11eb-8c26-8e81b475e195.png)
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/5434761/KSP.log)

I think the issue is when we join the next day to my dmp server after a save or smth?
Any idea?

**Comment by AnonymousJedi** [comment]
have you tried to reinstall kerbalism and kerbalismConfig?

**Comment by N3w0nee** [comment]
Will try but shouldn't be a problem since in singleplayer it works fine in every case, just happens when joining a saved game on a private dark multiplayer server

**Comment by gotmachine** [comment]
Kerbalism don't and can't work in a DMP / LMP game.
