### ISSUE TITLE
Switching to vessel erases crew and lab experiments

### ISSUE THREAD

**Issue by jimmymcgoochie** [Kerbalism/Kerbalism#686]
Vessels with crew experiments (in hitchhiker and SSPXr crew cabins) and lab experiments in the stock MPL are losing these experiment configurations when the vessel is switched to, either using the 'Go to' buttons in the Kerbalism craft list or by switching to them via tracking station or map view.

To replicate:

Launch a craft with crew and/or lab experiments and crew on board;
Switch to KSC view;
Switch back to the craft;
Vessel loads but crew and lab experiments are missing- data and samples gathered for those experiments are still there.

This has been an ongoing issue for me for a while.

KSP v1.9.1 with both DLCs, Kerbalism 3.11, Windows 10. Mod list and .ckan file, KSP and Player logs and a save file where this issue can be replicated can be found here: https://www.dropbox.com/sh/uteee55o1anm43l/AAAX-AjNcQeCYLOOxEYOjc-Ca?dl=0

**Comment by gotmachine** [comment]
Given the amount of `[Part]: PartModule indexing mismatch` errors in your log I think you have added/removed a mod mid-game, which doesn't really play nice with our modules. This won't happen anymore in Kerbalism 4.0 but there is no fix for the current Kerbalism versions.
