### ISSUE TITLE
Is there a way to change the default config for craft reports?

### ISSUE THREAD

**Issue by Jakeyjuju** [Kerbalism/Kerbalism#687]
Every time I launch a craft, I have to go to the config settings and disable reporting and stopping timewarp if the craft runs out of power or has a component failure. Is there a way to disable the error reports stopping timewarp?

**Comment by Cruesoe** [comment]
Yes. This can be done in two places. In the general Kerbalism settings you can alter the default for each new craft.
For existing inflight craft you can change the settings in the planner, look for the CFG tab. This can be done in flight with the vessel loaded or from the KSC screen if you prefer.

**Comment by gotmachine** [comment]
this ^
