### ISSUE TITLE
NFE Capacitors to extend shadow time

### ISSUE THREAD

**Issue by eberkain** [Kerbalism/Kerbalism#700]
A feature request. 

If I manually control a craft I could use a capacitor to extend the batteries during shadow.  Would it be possible to automate this process for the background simulation? The parts appear to use a different resource called "Stored Charge". Not sure if this would even be possible with how Kerbalism sim works.

**Comment by gotmachine** [comment]
As far as I remember the difference between a NFE capacitor and stock battery is :
- Charge / discharge is something that you "trigger", the capacitors aren't passive components
- You can't stop the discharge once started.

The second part is doable, but the first isn't viable at high timewarp rates. It's not a Kerbalism specific problem, it's just that implementing a "start discharging the capacitor if there isn't enough EC" behavior can't work, at least not without a huge specific hack. 

As a general rule, everything that is "event based" is highly problematic. Same reason why we are planning to remove some automation triggers, see also #638

This said, at some point in the future I plan do revisit the whole NFE (and other NF mods) support, including capacitors. But it is unlikely that any kind of automation will be added. And anyway, NFE capacitors are intended for NFP electric engines. If you want your vessel to survive the night, just pack more batteries.
