### ISSUE TITLE
Unmanned Slots in Sandbox

### ISSUE THREAD

**Issue by eberkain** [Kerbalism/Kerbalism#703]
Probes only have a single slot for unmanned experiments in sandbox, in science/career there is a node in the tech tree that unlocks a second slot.  

Could there be other node upgrades that are also not applied in sandbox mode? 

Thank you for supporting science collection in sandbox.

**Comment by UsernamesAreAlwaysTaken** [comment]
You need to select the option to apply all upgrades to parts in sandbox. AFAIK, this can only be done when creating the save.
