### ISSUE TITLE
A bug/error I found.

### ISSUE THREAD

**Issue by GooUckd** [Kerbalism/Kerbalism#711]
I was just about to play Kerbalism with some mods.. Found a crashing error.

![screenshot12](https://user-images.githubusercontent.com/62660100/103426180-464a2380-4bc0-11eb-9db2-d71d01ea8ed8.png)

[KSP.log](https://github.com/Kerbalism/Kerbalism/files/5758321/KSP.log)
(I'm not sure if that's the right log file... The KSP.log looked like the right one-)

**Comment by GooUckd** [comment]
OK, that IS the right file.

**Comment by gotmachine** [comment]
Your are missing the Kerbalism config pack (you only installed the core plugin).
You need both, see install instruction on the main page
https://github.com/Kerbalism/Kerbalism#download-and-installation
