### ISSUE TITLE
no humidity and SPU

### ISSUE THREAD

**Issue by tonimark** [Kerbalism/Kerbalism#712]
what happened to humidity and humidity controller?! I also remembered a time when there was an SPU module in squad service containers that allowed to decontaminate your kerbals from radiation

**Comment by lordcirth** [comment]
The humidity mechanic was removed, as it didn't add anything new. There is still a tech that adds radiation treatment.

**Comment by tonimark** [comment]
what is this tech?

**Comment by tonimark** [comment]
> The humidity mechanic was removed, as it didn't add anything new. There is still a tech that adds radiation treatment.

what is this tech?
also, humidity would kill kerbals after some concentration

**Comment by lordcirth** [comment]
> > The humidity mechanic was removed, as it didn't add anything new. There is still a tech that adds radiation treatment.
> 
> what is this tech?

https://github.com/Kerbalism/Kerbalism/blob/df311ab026cc67bdd1b8e25652b775c15e225840/GameData/KerbalismConfig/System/Sickbay.cfg#L9 :
techRequired = advScienceTech

Which is a 550 cost node.

> also, humidity would kill kerbals after some concentration
Yes, but humidity was mechanically identical to carbon dioxide scrubbing, so as a gameplay mechanic it was redundant.
