### ISSUE TITLE
Wrong solar power atmospheric opacity evaluation

### ISSUE THREAD

**Issue by gotmachine** [Kerbalism/Kerbalism#713]
Summary of this discussion on the RO discord : https://discord.com/channels/319857228905447436/531994741378646016/799095005791649822

> I'm still testing but it seems like Mars has a similar solar power degradation out of peak hours as Earth. Which seems wrong considering how much thinner the Martian atmosphere is?

![image](https://user-images.githubusercontent.com/24925209/104645291-2a11b080-56af-11eb-8bb8-35ab5f5b2ecd.png)

The code we have for that is an obscure formula that is as old as Kerbalism : https://github.com/Kerbalism/Kerbalism/blob/bc774264852ae65619d9a10626afd40c21d63574/src/Kerbalism/Sim.cs#L650-L661

The code seems to be a straightforward implementation of the formula in that WP article : https://en.wikipedia.org/wiki/Air_mass_(astronomy)#Nonrefracting_spherical_atmosphere
Looks alright to me at first look.
However, the way we use the stock `CelestialBody.GetSolarPowerFactor(double density)` method :
```
return body.GetSolarPowerFactor(density) * Ya / path;
```
doesn't really match the way it is used in the stock equivalent `CelestialBody.GetSolarAtmosphericEffects()`:
```
public virtual void GetSolarAtmosphericEffects(double sunDot, double density, out double solarAirMass, out double solarFluxMultiplier)
{
    double num = radiusAtmoFactor * sunDot;
    if (num < 0.0)
    {
        solarAirMass = Math.Sqrt(2.0 * radiusAtmoFactor + 1.0);
    }
    else
    {
        solarAirMass = Math.Sqrt(num * num + 2.0 * radiusAtmoFactor + 1.0) - num;
    }
    solarFluxMultiplier = GetSolarPowerFactor(density * solarAirMass);
}
```
Looks like to me that we should be doing something more like :
```
return body.GetSolarPowerFactor(density * Ya / path);
```

Really not sure about this, though, opening this issue so this isn't forgotten and in case someone that has some better understanding than me on the topic has something to say.

**Comment by warriorsabe** [comment]
I think I see your issue - that formula seems to assume a constant density of air. The diagram in that wikipedia page shows an atmosphere height that is within rounding of the scale height, which seems to support that. 

Assuming I'm correct about that, I think integrating through the atmosphere would likely be too computationally expensive, so I think you should approximate the scale height and use that for the atmosphere height above the current point instead. I'd use the pressure at the current altitude and the pressure halfway between there and the atmosphere limit for the anchorig keys so that its hopefully more accurate than just the local scale height, and doesn't accidentally catch the top-atmo cutoff range.

**Comment by gotmachine** [comment]
Mmmh, I think you're right.

The easy way out of that is to just use the stock `GetSolarAtmosphericEffects()` method that use a that per body `radiusAtmoFactor` thing. I think that like many other "legacy" code in Kerbalism, this was an attempt at making physics things work a bit more accurately than in stock, and to have more consistent support for Kopernicus planets that incorrectly specify the billions of parameters (like this one) that KSP require when defining a planet atmosphere. But like the other attempts, it is causing more issues than it is solving.

If we want to solve this, I guess an alternative would be to compute that integral for getting the "constantDensityAirColumnHeightAtSeaLevel" once per planet, and do some poor man scaling of those constants based on the pressure at current altitude vs the SL pressure. Won't be 100% accurate, but will likely be much better.

Still not sure how that stock `GetSolarPowerFactor()` method is meant to be used though : 
```
public double GetSolarPowerFactor(double density)
{
    double num = 1.225;
    if (Planetarium.fetch != null && Planetarium.fetch.Home.atmosphereDepth > 0.0)
    {
        num = Planetarium.fetch.Home.atmDensityASL;
    }
    double num2 = (1.0 - PhysicsGlobals.SolarInsolationAtHome) * num;
    return num2 / (num2 + density * PhysicsGlobals.SolarInsolationAtHome);
}
```
with
```
solarInsolationAtHome = 0.15 // Portion of solar flux lost when transitting through an atmosphere ending at the homeworld's sea level density, with the sun assumed at zenith and the observer on the equator
```
and `Planetarium.fetch.Home.atmDensityASL =1.225` (so `num` will likely always be 1.225)

**Comment by warriorsabe** [comment]
I think using the existing formula and just doing the scale height approximation should work almost as accurately as integrating in-situ without much more cost than the current setup. 

Just replace the Ya with a scale height calculation: 
In pseudocode, Ya = (atmo limit - current height) / (-2 * natural log (density here / density at((atmo limit + current height) / 2)))

**Comment by warriorsabe** [comment]
Oh, also, Kopernicus planets cannot specify the sunlight lost by the atmosphere for stock calculations. The 0.15 value is attached to the star itself. Support for really any custom system would require the airmass calculation.

**Comment by gotmachine** [comment]
> The 0.15 value is attached to the star itself.
It is game wide, not even per star.

Also, `radiusAtmoFactor` is actually estimated by KSP, not a configurable value : `radiusAtmoFactor = Radius / atmosphereDepth * (Math.Log(1E-06));`

`Ya = (atmo limit - current height) / (-2 * natural log (density here / density at((atmo limit + current height) / 2)))`
Shouldn't that be : 
`Ya = (atmo limit - current height) / (-2 * natural log (density here / density at((atmo limit - current height) / 2)))` ?

**Comment by warriorsabe** [comment]
Ah, the value exists in star configs, so it seemed a star value.

And it should be plus - that number is the altitude of the point halfway between where you are now and the limit. As opposed to the other, similar, value which is the distance to that point.

Taking that formula and generalizing it, what it is is 
- ((distance from point one to point two) / natural log (value at low point / value at high point))
I just put in values for the specific altitudes I was talking about using

**Comment by gotmachine** [comment]
Like this ?
```
double density = body.GetDensity(static_pressure, body.GetTemperature(altitude));
double Ra = body.Radius + altitude;
double maxDepth = body.atmosphereDepth - altitude;
double midDepth = maxDepth * 0.5;
double midDepthAltitude = midDepth + altitude;
double midDepthDensity = body.GetDensity(body.GetPressure(midDepthAltitude), body.GetTemperature(midDepthAltitude));
double Ya = midDepth / (-2.0 * Math.Log(density / midDepthDensity));
double q = Ra * Math.Max(0.0, Vector3d.Dot(up, sun_dir));
double path = Math.Sqrt(q * q + 2.0 * Ra * Ya + Ya * Ya) - q;
return body.GetSolarPowerFactor(density) * Ya / path;
```

**Comment by warriorsabe** [comment]
Yeah, mostly. The 2 multiplied with the natural log was actually for the finding the halfway point; since you already did that in the variable definition you don't need it. You do still need the negative though

**Comment by gotmachine** [comment]
Ok, so, for reference, this gives relatively accurate results :
```
public static double AtmosphereFactor(CelestialBody body, Vector3d position, Vector3d sun_dir)
{
	// get up vector & altitude
	Vector3d up = position - body.position;
	double altitude = up.magnitude;
	up /= altitude;
	altitude -= body.Radius;
	altitude = Math.Abs(altitude); //< deal with underwater & fp precision issues

	double static_pressure = body.GetPressure(altitude);
	if (static_pressure > 0.0)
	{
		double density = body.GetDensity(static_pressure, body.GetTemperature(altitude));

		// nonrefracting radially symmetrical atmosphere model [Schoenberg 1929]
		double Ra = body.Radius + altitude;
		double maxDepth = body.atmosphereDepth - altitude;
		double midDepth = maxDepth * 0.15;
		double midDepthAltitude = midDepth + altitude;
		double midDepthDensity = body.GetDensity(body.GetPressure(midDepthAltitude), body.GetTemperature(midDepthAltitude));
		double Ya = midDepth / Math.Log(density / midDepthDensity);
		double q = Ra * Math.Max(0.0, Vector3d.Dot(up, sun_dir));
		double path = Math.Sqrt(q * q + 2.0 * Ra * Ya + Ya * Ya) - q;
		return body.GetSolarPowerFactor(density * (path / Ya));
	}
	return 1.0;
}
```
However, testing show that just calling the stock :
```
body.GetSolarAtmosphericEffects(Vector3d.Dot(up, sun_dir), density, out double stockAirMass, out double stockFluxFactor);
return stockFluxFactor;
```
give similar results (tested for Kerbin, Duna, RSS Earth and RSS Mars), and is more lightweight in terms of performance, so i see little justification for having our own implementation.
As discussed, another option would be to precompute a per body array of Air mass values for a bunch of altitude slices, which might be even faster and be may be worthwile in the context of the Kerbalism 4 substepping simulation.
In the meantime, I will likely just use the stock method.
