### ISSUE TITLE
error on save and on new game

### ISSUE THREAD

**Issue by AlluvialBulldog** [Kerbalism/Kerbalism#718]
MacOS
<img width="598" alt="kerbalism error message" src="https://user-images.githubusercontent.com/40374326/109746658-bfa3c980-7ba3-11eb-9452-53ff88ef71d9.png">
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/6073349/KSP.log)

**Comment by AlluvialBulldog** [comment]
Additional info: did a minimal mod install and no errors were generated. Looking like a mod compatibility issue.

**Comment by gotmachine** [comment]
You are missing the KerbalismConfig folder in GameData
