### ISSUE TITLE
Tranquillizing Vortex (TV) does not seem to do anything

### ISSUE THREAD

**Issue by king-of-nowhere** [Kerbalism/Kerbalism#720]
i made some tests. 4 kerbal crew, some of them were inside a hitchiker container, some were not. anyway, with 3 TV active, 128 days in orbit, 1% stress. Same ship, same 128 days in orbit, 9 TV active, still 1% stress. Same ship, same orbit, all TV shut down, still 1% stress.
i assume it's a bug; it it's intended to work this way, then i have no idea what the tv is supposed to do.

**Comment by gotmachine** [comment]
The TV effect on stress is very low. It isn't strong enough to remove stress, only to slow down the accumulation, so it only really matter over long durations. For reference, it is balanced to remove stress at the same rate as the base accumulation rate when you have maxed out comforts/living space, but depending on the per-kerbal variance (33%), you might still see some stress accumulation even in that case.

Also, make sure that you actually assign Kerbals to the TV slots (this works in the same way as the Radiation Detox Unit)
