### ISSUE TITLE
SSPX-Redux SCATTER-1 massive nitrogen leak after EVA

### ISSUE THREAD

**Issue by TorbjornLindgren** [Kerbalism/Kerbalism#725]
I first discovered this in a more modded 1.11.1, but have now replicated it with 1.11.2 (latest) and just the Kerbalism, Kerbalism - Default Config and Stockalike Station Parts Expansion Redux by Nertea, and said no when on all optional mods.

When I built a craft which includes the SCATTER-1 Service Airlock (sspx-airlock-125-1) it's initially fine but once I do an EVA it starts to leak nitrogen, I'm not sure if it starts when I exit or when I enter. I exit via a capsule EVA port, there's no Kerbals in the SCATTER-1 Service Airlock.

This ISN'T just the normal repressurization, it keeps on leaking.
I made a small craft (Mk2+SCATTER-1) and added two 7200 nitrogen tanks.
In the VAB it said I had 15393.90 units of Nitrogen and that it would last 120y 19d with the two 2 Kerbals I had onboard (obviously without any EVAs). It lasted roughly 8.5 hours after did a very quick EVA in in orbit with just one of the two Kerbals.

None of the other SSPX-Redux parts I tested has this leak behavior, including the larger but otherwise somewhat similar PPD-EVAC-U-8 Service Airlock (sspx-airlock-25-1). I've compared all text files I could fine that used the sspx-airlock-125-1 code and they seem "close enough" to the larger 25 model which doesn't leak so it's probably not in the text config files though I could have missed something.

Cross-mod bugs are always hard to know where to report them but since I assume SSPX doesn't normally have nitrogen or leaks I'll report it here first. If you feel that it's likely not a Kerbalism issue at the core I will report it to SSPX-Redux instead and see if it's something he want to look at.

EDIT: More data - switching to Space Center and timewarping and it stops using Nitrogen usage after 1000-1200 units, a bit higher than the total nitrogen volume in the capsule plus scatter-1 (perhaps due to time before I can switch away). Switching to the Space Center and then back to the craft doesn't help. if I do that it drains down to 0. So, it stops correctly when the craft is in background processing but not if it's the active craft.

Providing zip with CKAN mod list, the KSP log and craft file.
[SCATTER-1-Leak.zip](https://github.com/Kerbalism/Kerbalism/files/6216148/SCATTER-1-Leak.zip)

**Comment by TorbjornLindgren** [comment]
Adding KSPBugreport file. KSP 1.11.2 and Kerbalism 3.13.
I deorbited the old craft, exited, started again with KSPBugreport installed and launched the same craft.
Did an EVA, then timewarped until more than half the Nitrogen had been used which is many, MANY times more than the correct amount.
[KSPBugReport_2021-03-30_024834.zip](https://github.com/Kerbalism/Kerbalism/files/6225525/KSPBugReport_2021-03-30_024834.zip)

**Comment by gotmachine** [comment]
Yep, whole pressure system has issues. Until the rewritten system is released, I don't intend to fix it (see https://github.com/Kerbalism/Kerbalism/issues/733)
