### ISSUE TITLE
Nitrogen option on Drill-O-Matic Junior Mining Excavator

### ISSUE THREAD

**Issue by wolffy-au** [Kerbalism/Kerbalism#731]
I was asking on Discord where I have to go to mine Nitrogen, but the reponse was that it shouldn't be possible. I'll log this ticket here in case it really is a bug - otherwise, please let me know what resource I need in abundance to mine Nitrogen.

Be advised - this is a reference to this functionality in the help docs.
https://github.com/Kerbalism/Kerbalism/wiki/PlayGuide-~-Resources#harvesters

![image](https://user-images.githubusercontent.com/25105266/114202820-ed4a1280-999a-11eb-8829-5f611284ebba.png)

**Comment by lordcirth** [comment]
Normally in Kerbalism, Nitrogen is extracted from the atmosphere using a configuration of the atmospheric sampler.

**Comment by wolffy-au** [comment]
Yes - I was aware of that function of the atmosphere science part.

If you can't technically "excavate nitrogen", I'm thinking the option should be removed from the drill part?

**Comment by wolffy-au** [comment]
With assistance from WarriorSabe, I've confirmed that it is working as intended on Mun. Would be great if it could be included in the resources list, as that was the bit that confused me - the config files dictate it only appears on certain planets/moons and as far as I can tell, there is no way to tell which ones they are without looking at the config file GameData\KerbalismConfig\ResourceConfigs\Nitrogen.cfg

Here is a screenshot of the drill working and the current resource list.
![image](https://user-images.githubusercontent.com/25105266/114248185-58670980-99da-11eb-953d-72dcbe1344dd.png)

**Comment by wolffy-au** [comment]
I can see Nitrogen in the tracking station though
![image](https://user-images.githubusercontent.com/25105266/114264135-81b08580-9a2c-11eb-99d2-6bd830083c5d.png)
