### ISSUE TITLE
JAMMED experiment broken at high timewarp

### ISSUE THREAD

**Issue by c-lipka** [Kerbalism/Kerbalism#732]
When Kerbalism disables its day/night tracking at timewarps beyond 100x (while at Tracking Station or some other vessel) and switches to average sunlight mode, the JAMMED experiment breaks down because it can only run in shadow, but Kerbalism tells it that it's permanently in the sun (albeit at attenuated solar input).

This is particularly annoying because JAMMED is one of the longer-running crewed experiments, taking 290d worth of night time (and thus >1y 154d mission time) to complete. From the Tracking Station, that's equivalent to >1.5 real-life days of uninterrupted 100x timewarp.
"Riding along" with the vessel in question is also not a satisfying workaround, because you'll frequently need to drop out of warp and re-align the vessel to ride out solar storms, and also because it makes it more difficult to keep track of upcoming maneuvers on other vessels.

**Comment by gotmachine** [comment]
Yep, that's a known issue. 

Experiment restriction checks are boolean based, which is an issue with "fast" moving conditions at high timewarp speeds, not only for sunlight/shadow but also for biomes, radiation, altitude, etc...

As you mentioned, we already have a workaround for sunlight exposition, currently used for solar panel output evaluation, but it wasn't used for experiments. 

This needed a bit of refactoring, which is now done, will be in next release :
![image](https://user-images.githubusercontent.com/24925209/120500643-4d6c9c00-c3c1-11eb-8335-6ccef4abf11b.png)

**Comment by c-lipka** [comment]
Looks promising, looking forward to it. That'll save me a lot of slow warping ;)
