### ISSUE TITLE
Kerbalism-CKAN compatability issue

### ISSUE THREAD

**Issue by SolarSupremacy** [Kerbalism/Kerbalism#736]
I'm not sure if the root problem is with Kerbalism or CKAN but other mods work fine so I assume the issue is here.

"Kerbalism 3.13 depends on Kerbalism-Config, which is not compatible with the currently installed game version"

"Kerbalism-Config-Default 3.13 depends on Kerbalism, which is not compatible with the currently installed game version"

Kerbalism-Config doesn't seem to be a mod on CKAN but the current mods are updated to 1.11.9 which exceeds the current game version. There's no apparent reason to my as to why I cannot install Kerbalism through CKAN.

**Comment by tivec** [comment]
This is most probably a metadata issue with CKAN, and should also probably be filed to their tracker.

If you go into the "compatible versions" and check 1.11 like this, it should work fine:
![image](https://user-images.githubusercontent.com/717574/118269815-733c0a80-b4bf-11eb-8c04-78b7580c2115.png)

Please note I have checked 1.8-1.10 as well, do not do this unless you know what you are doing.

**Comment by SolarSupremacy** [comment]
I've always had mine checked for the current version and two versions behind (so in this case, 1.11 to 1.9). I tried enabling other compatible versions to see if that would fix it but nay (I even added '1' as a version, covering everything from 1.0).

I'll report it to CKAN. Thanks!
