### ISSUE TITLE
Automation Breaks Sickbay RDU

### ISSUE THREAD

**Issue by c-lipka** [Kerbalism/Kerbalism#738]
I have experienced a problem with the Radiation Detoxication Unit (RDU) on one of my vessels, in which the RDU has gotten into a borked state, in which it does not appear to consume either EC nor Oxygen, nor produce CarbonDioxide, nor actually cure the assigned patient, despite explicitly enabled, a radiation-exposed Kerbal assigned to be cured, and both EC and Oxygen readily available.

Digging for the borked part in the save file, I found that the part's `Sickbay` `MODULE` was set to `isEnabled = True`, `patients = [Kerbal Name]` and `running = True`, but the `_SickbayRDU` pseudo-`RESOURCE` was set to `flowState = False`.

So it seems that while the module itself is turned on and ready to go, something has invalidated the "tank" for its pseudo-resource, and thus it won't run.

I'm not very familiar with the architecture nor code of Kerbalism,  but I _think_ I found how this could have happened:

In `ProtoSickbayDevice` (`Automation/Devices/Sickbay.cs`) - the class that I presume is used when turning a sickbay on or off via automation while the vessel is _unloaded_ - the methods changing the `running` field of the module also change the `flowState` field of the pseudo-resource accordingly.

In both `Sickbay` (`Modules/Sickbay.cs`) - the class that I presume is used when turning a sickbay on or off via the part action menu - and `SickbayDevice` (`Automation/Devices/Sickbay.cs`) - the class that I presume is used when turning a sickbay on or off via automation while the vessel is _loaded_ - the methods changing the `running` field of the module leave the `flowState` field of the pseudo-resource unchanged.

Thus, if a Sickbay is ever turned off via automation while _unloaded_, it cannot be turned on again effectively while _loaded_, until turned on again via automation while _unloaded_.

To make matters worse, a Sickbay (at least the RDU flavor) doesn't show up in the automation window of unloaded vessels, so manually re-enabling it while unloaded is not an option - the only way to "unbork" a Sickbay under such circumstances is to take control of the vessel to load it, make sure the RDU is turned off for good, set up a script that will re-enable the Sickbay, return to the tracking station (or some other vessel) to unload the vessel, wait for the script conditions to trigger (praying that the script did actually trigger as intended, with only indirect feedback to know for sure), and finally go back to the vessel again to remove the script (and ideally any other scripts that would mess with the RDU).

**Comment by gotmachine** [comment]
I don't have much time to test, but after following the code, I think removing the flowstate flip done in `ProtoSickbayDevice` is the right way to fix this.
