### ISSUE TITLE
Setting `StormEjectionSpeed` missing in default config

### ISSUE THREAD

**Issue by c-lipka** [Kerbalism/Kerbalism#739]
For the `StormEjectionSpeed` setting, defaulting to `0.33`. there is no corresponding entry in `Settings.cfg` to serve as an example how to override the parameter.

_Addendum_: In the Wiki, the setting is erroneously listed as defaulting to `1000000`, while the source code implies the default to be `0.33`; accordingly, the unit of measurement `m/s` stated in the Wiki is also presumably wrong. Instead, the parameter unit seems to be light speed.

**Comment by c-lipka** [comment]
Note that there is indeed a internal value of same name, which is derived from the actual config setting by multiplying with the speed of light in m/s, so that internal value is indeed in m/s.

**Comment by gotmachine** [comment]
Fixed the wiki entry for `StormEjectionSpeed`

Note that the Kerbalism wiki can be edited by anyone with a github account, feel free to correct these kind of mistakes without asking.
