### ISSUE TITLE
Request: support active radiators in auto

### ISSUE THREAD

**Issue by Gordon-Dry** [Kerbalism/Kerbalism#74]
If it would also be possible to add two new auto readouts for "critical part temp" which checks the highest percentage of part/skin temp on the vessel and makes this value available for triggering parts by auto, like radiators, that would be great.

Could come handy for near-sun probes or when using reactors to deploy additional radiators when needed.

**Comment by Gordon-Dry** [comment]
As it seems radiators are already in the planner, I guess I didn't see them only before I did my commits to the Reliability.cfg
Or I had a "bad" part before I opened this issue.

So I changed the title.

**Comment by SirMortimer** [comment]
part temperature is only available on loaded vessels, which is exactly the reason why nothing related to heat is currently being done in kerbalism. it just doesn't work in backgorund. can't be done.
