### ISSUE TITLE
SENTINEL Infrared Telescope by Squad can not run with Kerbalism RTGs

### ISSUE THREAD

**Issue by tivec** [Kerbalism/Kerbalism#740]
I launched a satellite that was 100% RTG powered, with the SENTINEL Infrared Telescope attached for a contract. When I click "Start Object Tracking" in the PAW for the telescope, this message pops up:

![KSP_x64_ho4kxFvEVu](https://user-images.githubusercontent.com/717574/119651427-4b389980-be25-11eb-84ea-ebfac608eb3a.png)

Patching the SENTINEL telescope (any part with `SentinelModule`) to include a standard `ModuleGenerator` that is always on and produces electricity, it allows the telescope to be switched on. This introduces the issue where time warping produces weird results and the player is asked to unload the vessel instead.

Workarounds:
- Run a patch to apply a `ModuleGenerator` and living with the time warp issues.
- Use a solar panel on the craft, since this seems to work even if it is a modded solar panel deriving from the Squad modules.

Whether or not it works or not remains to be seen, I get no message stating it is working when I then click "Start Object Tracking", and the prompt does not change, so it is possible something else is also interfering with the module. At least with the patch I added, I don't get the failure message due to a missing generator.

**Comment by gotmachine** [comment]
Using the workaround with a dummy `ModuleGenerator`, you can configure it to generate nothing, which will still fulfill the requirement while avoiding the time warp issue.

The real solution is to code a derived module that is properly aware of Kerbalism's resource sim and comms, which I just added in 35d0df5
