### ISSUE TITLE
Dmagic Orbital Science config has badly named field

### ISSUE THREAD

**Issue by tofof** [Kerbalism/Kerbalism#743]
https://github.com/Kerbalism/Kerbalism/blob/03d9aea216c6fea87acc6f5afcc31afb5a497804/GameData/KerbalismConfig/Support/DMagicOrbitalScience_Science.cfg#L455

It should read `BodyAllowed` not `BodyRequired`

Because of this error, the drill doesn't list its atmospheric requirement properly in the science browser.

**Comment by gotmachine** [comment]
Fixed in 3.14
