### ISSUE TITLE
No credit for science in "flying low" situation

### ISSUE THREAD

**Issue by dgk816** [Kerbalism/Kerbalism#752]
Hello,

I'm not getting science credit while flying low.  This is happening with telemetry, temperature scan, pressure scan and crew reports.   This has happened over shores, grasslands, water, tropical, mountains and desert biomes, the only ones I've flown over.   I can see the experiments are running and data is being transmitted but I get 0 credit when they finish.  Please see the attached screen shot.
KSP 1.10.1.2939
Kerbalism 3.14

Thank you
![kerb_noscience](https://user-images.githubusercontent.com/79928809/129481949-01fcd77c-de49-4f59-8177-96655a8325f6.png)

**Comment by siimav** [comment]
That's all correct. ROKerbalism no longer provides any flying-low science.

**Comment by dgk816** [comment]
Sorry, Im also playing with Realism Overhaul so I moved this issue to the KSP-RO/ROKerbalism issue page

**Comment by dgk816** [comment]
Thank you so much, I also close the issue at KSP-RO/ROKerbalism .
