### ISSUE TITLE
Borked Lab patches

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [Kerbalism/Kerbalism#762]
Ok.

You may or may not remember me at this point, but I wrote a few lines of patches primarily for science.

Getting back and digging in - I just noticed that the Laboratory patching is borked (I assume someone modified it after my departure).

What do I mean by borked? You have several parts in that patching system that does specific things each pass, and if one step is messed up, a lot of unfunny things happen. Courtesy of myself for writing such an "easy to understand" and "fun" system.

Now, to the problem itself:

Your have this:
@PART[*]:HAS[@MODULE[ModuleScienceLab]]:NEEDS[FeatureScience]
{
	!MODULE[ModuleScienceLab] {}
	!MODULE[ModuleScienceConverter] {}

	MODULE
	{
		name = Laboratory
		researcher = Scientist
		analysis_rate = 0.005 // 5 kbps
		ec_rate = 1.0
	}
}

Which nukes all stock lab modules on everything it finds and replaces it with our own module. Does nothing else.

Then you have this:

@PART[Large_Crewed_Lab]:HAS[@MODULE[ModuleScienceLab]]:NEEDS[FeatureScience]:FIRST
{
	MODULE
	{
		name = Configure
		title = Laboratory Experiments
	}
}

Which adds the functionality to the lab - all the epxeriments, the ability to swap them, etc.

That's awesome, but it's only awesome for the stock Lab. All other labs in the game are stuck with the kerbalism module and nothing else. The Configure (Lab Experiments) module and the experiments themselves never get added to anything else besides the stock Lab.

Now, I'm confused. I assume this was done to reduce the amount of complaints regarding broken mods, such as WBI for example. 
But I don't think this was the way to do it.

Now I can probably do something about it, but at this point I sort of have to ask HOW do you want the fix? Do I leave all other modded labs untouched by Kerbalism, or do I hand-pick which labs get the patches? Third option was to revert to old state, where everything gets patched, but I assume the complaints got too much.

**Comment by kleinschmidt** [comment]
I just hit this with SSPX labs too.  Any reason not to just revert https://github.com/Kerbalism/Kerbalism/commit/5a8840238a7ec08ac65659de97e05f749bffb3a7 ?  I searched for `ModuleScienceLab` in my (lightly modded) GameData and the only places it pops up are the stock lab, the SSPX labs, and some contracts.

**Comment by gotmachine** [comment]
Fixed in https://github.com/Kerbalism/Kerbalism/pull/830
