### ISSUE TITLE
No science gained from recovered samples

### ISSUE THREAD

**Issue by nocreativityforusername** [Kerbalism/Kerbalism#764]
I'm playing a RO/RP1 career game and I notice that I didn't gain any science point from bio capsule and filming camera after I recovered the vessel. It seem that the game does not reconizes there is a sample in the craft when I recovered it. 

First I resintall everything, but didn't work. Then I suspect maybe is KCT mess up the recovery, so I uninstall it. The problem still exist. Finally the problem is gone after I uninstall kerbalism. From here, I tried different version of kerbalism from CKAN and github but nothing worked.

Anyone can help?

**Comment by gotmachine** [comment]
Sounds like something that would have been noticed by the RP1 team. Closing as "probably obsolete" :P
