### ISSUE TITLE
Transmit rate stuck at 2.5 mb/s for all antennas with very high EC consumption rates

### ISSUE THREAD

**Issue by EmperorBlackadder** [Kerbalism/Kerbalism#772]
All my antennas (except Communutron 8 which doesn't work) have a 2.5 mb/s transmit rate, with more than 20 EC/s during transmit and an idle consumption rate of 0.7/s. I don't use remote tech or ResearchBodies, though there is a Reposoft folder in my Game data folder which doesn't contain any cfg files.

This makes the early game practically unplayable since I can't even carry enough hydrogen for the fuel cells to get to the Mun even while idling unless I make a craft with dozens of batteries. Any help would be appreciated.

**Comment by gotmachine** [comment]
Upload your KSP.log and ModuleManager.configcache files. Or use https://github.com/KSPModdingLibs/KSPBugReport

**Comment by EmperorBlackadder** [comment]
These ones right?
[ModuleManager.log](https://github.com/Kerbalism/Kerbalism/files/7557189/ModuleManager.log
[KSP.log](https://github.com/Kerbalism/Kerbalism/files/7557191/KSP.log)
)

**Comment by gotmachine** [comment]
Nope. ModuleManager.configcache, which is GameData

**Comment by gotmachine** [comment]
But your issue is that you have a `RemoteTech` folder in `GameData`

**Comment by EmperorBlackadder** [comment]
Couldn't upload a config cache file so I copy pasted it to a txt file. Here you go [Module Manager Config Cache.txt](https://github.com/Kerbalism/Kerbalism/files/7557400/Module.Manager.Config.Cache.txt)

**Comment by EmperorBlackadder** [comment]
Are you sure? Cus that's a legacy folder from CKAN, it doesn't actually have anything inside it

**Comment by gotmachine** [comment]
Yep. You should never keep folders of uninstalled mods, as this cause ModuleManager to register those mods as still installed.

**Comment by EmperorBlackadder** [comment]
I see, I'll check to see if that works. Thanks a lot!

**Comment by EmperorBlackadder** [comment]
Worked like a charm, again thank you very much!
