### ISSUE TITLE
No way to eject from aircraft

### ISSUE THREAD

**Issue by Greysa** [Kerbalism/Kerbalism#783]
I may not be far enough into the tech tree, but from what I can see, with no way to EVA in Kerbin atmo, there is no way to use the parachute for ejection purposes. Maybe add a button to the cockpit that can do it instead?

**Comment by jacobcargen** [comment]
Pilots can always use the EVA parachute in career, but you may need to level up other kerbals in order to use the parachute. I think you're talking about the parachute rather than eva?
