### ISSUE TITLE
Incorrect recovery value for all manned pods

### ISSUE THREAD

**Issue by Gosye** [Kerbalism/Kerbalism#801]
Recovering command pods yields almost no funds regardless of whether you have any additional modules like scrubber, in VAB command pod MK1 value in tooltip is 600.33, actual cost 630, recovery on KSC with 100% rate is 9 funds, in some cases it yields negative funds like  KV-1 "Onion" recovery is -705 funds.

**Comment by gotmachine** [comment]
This is a KSP bug. Installing https://github.com/KSPModdingLibs/KSPCommunityFixes should fix it.
