### ISSUE TITLE
Kerbalism Time scale not changing

### ISSUE THREAD

**Issue by NightShift10125** [Kerbalism/Kerbalism#805]
I discorved that the duration time that you get for things like food and water don't update when changing from kerbal time to earth time.
I am unaware what is causing the bug, is there a way to manually change the time value Kerbalism gives?

To show what I mean the 'Onion' Reentry Module has five days worth of food on kerbal time and less than two on Earth time;
![image](https://user-images.githubusercontent.com/42304378/158079023-3cdb77e6-089f-47c9-9698-1ddcbbd58169.png)
![image](https://user-images.githubusercontent.com/42304378/158079041-d935a4d3-7f38-4d4b-b3a6-a33e562532f3.png)

**Comment by gotmachine** [comment]
Kerbin time / Earth time just change how time is displayed.
It isn't supposed to affect any gameplay aspect.

If you want to rebalance the various consumption/production rates, this has to be done through config editing in a lot of places. Kerbalism doesn't have a global "time multiplier" option.

**Comment by NightShift10125** [comment]
I think I was unclear.
The game is working as intended, except for the fact Kerbalism is showing the duration of supplies in Kerbin time when should be showing the duration of supplies in Earth time (ie; 5 Kerbin days when it should be showing 2 Earth days).
How do I troubleshoot this?

**Comment by warriorsabe** [comment]
I can say from usage in planet packs, it auto-adjusts the size of day and year units to the rotational/orbital periods of the home planet. With tidally locked homeworlds this can be problematic, as 1 day = 1 year and anything reaching that period is heavily rounded off (as it shows years and no hours). Perhaps a setting to override the time mode would be useful
