### ISSUE TITLE
FR: Current Vessel Experiment Overview

### ISSUE THREAD

**Issue by jaxx050** [Kerbalism/Kerbalism#806]
Essentially, much how ScienceAlert ReAlerted provides a one-stop-shop for currently available experiment management so as not have to go rooting around your spacecraft with right click to individually click on, Kerbalism can add to the Science section of the toolbar button by adding a roughly similar idea. The button can add an additional icon or maybe a line color change to the experiment results that can currently be manipulated, to turn on/off experiment study from a centralized location.

**Comment by gotmachine** [comment]
This would be useless and/or is already implemented.

You can just enable Kerbalism experiments once and for all (you can even do so in the VAB), and they will collect the science automatically whenever a new situation becomes available.

Also, you already have access to all experiments from a centralized location in the "auto" tab of the Kerbalism vessel management UI :
![image](https://user-images.githubusercontent.com/24925209/159178377-48e036b9-7b1f-4d56-81f9-d604f5424f56.png)
