### ISSUE TITLE
TechGuide/Profile doesn't mention the rate that processes run at

### ISSUE THREAD

**Issue by jessicest** [Kerbalism/Kerbalism#810]
At https://github.com/Kerbalism/Kerbalism/wiki/TechGuide-~-Profile#process it describes input and output as: "in the format **input = resource@rate**"

But it doesn't talk about what that rate may be.

Comparing the in-game display against values in this file, it seems to be once per half-second -- is that right?

(rationale: water electrolysis in a Chemical Plant costs 1.013/s in the planner in the VAB, but it's quoted at 0.5065967413 in this file, which is approximately half of the per-second rate.)

I'm happy to add a note to the docs if my understanding is correct.

**Comment by gotmachine** [comment]
The process definition define a base rate, which is then multiplied by the `capacity` of the `ProcessController` module (see https://github.com/Kerbalism/Kerbalism/wiki/TechGuide-~-PartModules-~-ProcessController)

**Comment by jessicest** [comment]
Thanks! I've added the following sentence to the Process section of the docs:

Rates for processes are per-second, multiplied by the capacity of the ProcessController that runs them.

(I wanted to link out to the ProcessController page directly but couldn't figure out the hyperlink syntax 🙃)
