### ISSUE TITLE
Automation for NF eletrical parts or Smart Parts

### ISSUE THREAD

**Issue by edusaraiva** [Kerbalism/Kerbalism#818]
Hi I'm playing with smart parts and NF eletrical parts... any chance to put this parts in the automation from kerbalism?
My idea is to use capacitors to reduce the amount of batteries from my ship.... My idea was to use the function from kerbalism automation... like when is battery bellow 20% discharge capacitor... when in sunlight recharge capacitor and if full battery deactivate capacitor.... any chance to have this? if not how can I add smart parts to the automation... that would also work...

tks

**Comment by gotmachine** [comment]
This isn't desirable. See https://github.com/Kerbalism/Kerbalism/issues/638#issuecomment-633297900
