### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Minfrog314** [Kerbalism/Kerbalism#819]
I just got a bunch of mods off of CKAN, and after starting a sandbox game I get this:
![image](https://user-images.githubusercontent.com/43827119/176814354-4e549332-0283-48dc-bbaa-4c92206eefd4.png)
Here is KSP.log (it was absurdly long, so I truncated it to 20M, even still that is absurdly long)
[KSP_trunk.log](https://github.com/Kerbalism/Kerbalism/files/9024729/KSP_trunk.log)
And here is my modlist
[modlist.txt](https://github.com/Kerbalism/Kerbalism/files/9024732/modlist.txt)
I'm very new to KSP modding (I probably shouldn't have started with so many but whatever), so any help would be appreciated!

**Comment by gotmachine** [comment]
This is a known issue, it is fixed in the latest dev build, but there are other annoying bugs in that one. I'm in the process of doing a Kerbalism release where this issue is gone.
