### ISSUE TITLE
Solar panels do not produce electricity while landed properly.  

### ISSUE THREAD

**Issue by byt3c** [Kerbalism/Kerbalism#827]
It happens when craft is landed and unloaded during warp.  Maybe there could be simple lookup table for rough angle exposure sets (vectorwhile landed calculated on vessel unload and while in off grid sim just apply those based on surface position and sun angle ?

the same might be actually applied to craft in flight where last exposure is taken, but might be easily put into angle table so that it might process it quicker and more realistically ?
https://github.com/Kerbalism/Kerbalism/blob/master/src/Kerbalism/Modules/SolarPanelFixer.cs#L409

// cosine / occlusion factor isn't updated when in analyticalSunlight / unloaded states :
			// - evaluting sun_dir / vessel orientation gives random results resulting in inaccurate behavior / random EC rates
			// - using the last calculated factor is a satisfactory simulation of a sun relative vessel attitude keeping behavior
			//   without all the complexity of actually doing it

does this means that during unloaded state vehicle orientation for root part is random? or there is a way to actually get that in reliable way ?

I hope I could help a bit.

**Comment by gotmachine** [comment]
You could in fact generalize this statement to "Solar panels do produce electricity properly".

See https://github.com/Kerbalism/Kerbalism4/issues/25 and https://github.com/Kerbalism/Kerbalism4/issues/24

In the context of Kerbalism 3.x, this would require a lot of ground-up work, as Kerbalism 3 doesn't compute occlusion reliably anyway. Kerbalism 4 has experimental/preliminary work to address all of this, but as of writing, neither Kerbalism 3 or 4 are actively developed/maintained.
