### ISSUE TITLE
Conversion from hours to days in Kerbalism UI will not work for non-standard days

### ISSUE THREAD

**Issue by andrechalom** [Kerbalism/Kerbalism#838]
Okay, this is my first Kerbaled mission in 2 years (real life), so I might be missing something. But the problem is: I'm loading a rocket with a standard one seat Mk1 Command Pod, filled with 1.4 food (I'll be focusing on food, but water and oxygen have the same problem). Just after launch, the Kerbalism UI confirms I have 1.4 food, and a rate of consumption of -0.044h, which should allow me to fly for 1.4 / 0.044 =~32h = 5d. All of this is expected. However, after I time warp for one single day, it's almost gone, as shown in the image below. Am I missing something? Is Jeb snacking all the way through his meals?

![image](https://user-images.githubusercontent.com/1994997/205446298-3d072bfd-7c27-48d5-9c69-f5fa6091a1d6.png)

Running KSP 1.12.4.3187, Kerbalism 3.16 with default config + MechJeb. All other mods disabled as I ran this test.

**Comment by andrechalom** [comment]
Ok, I've figured out the issue! SOME OTHER MOD that was present only at this save startup changed the day duration to be 24h (WHY??)

So I guess the bug report turns out to be: conversion from hours to days in the Kerbalism UI should consider how many hours are actually present in a day.

**Comment by warriorsabe** [comment]
> So I guess the bug report turns out to be: conversion from hours to days in the Kerbalism UI should consider how many hours are actually present in a day.

The thing is, it does, kinda. It directly reads the home planet's rotation and orbit, completely bypassing the stock clock system (it really should just read the clock to avoid such confusion but no one seems to be maintaining this mod anymore)

I'd first check your ksp settings, there's one for a 24 hour clock that may have gotten flipped. If not, I'd check to see if a mod called Kronometer is installed, that's probably the most common thing used to modify the clock

**Comment by UsernamesAreAlwaysTaken** [comment]
> > So I guess the bug report turns out to be: conversion from hours to days in the Kerbalism UI should consider how many hours are actually present in a day.
> 
> The thing is, it does, kinda. It directly reads the home planet's rotation and orbit, completely bypassing the stock clock system (it really should just read the clock to avoid such confusion but no one seems to be maintaining this mod anymore)
> 
> I'd first check your ksp settings, there's one for a 24 hour clock that may have gotten flipped. If not, I'd check to see if a mod called Kronometer is installed, that's probably the most common thing used to modify the clock

Correct. You need Kronometer to fix the clock. Kerbalism planner will work properly afterwards. There is a version floating around.

**Comment by andrechalom** [comment]
Yup, it was the KSP setting. I had no idea I had set it that way (which probably occured years ago). Thanks for the help!
