### ISSUE TITLE
Vessel cannot transmit science if has type "DeployedScienceController" (Science in the vessel rename dialog)

### ISSUE THREAD

**Issue by whale2-spread** [Kerbalism/Kerbalism#845]
Using 
Kerbal Space Program - 1.12.4.3187 (OSXPlayer) en-us
Kerbalism 3.16.0.0

If the vessel type changed to "Ship" or "Base", transmission works ok.

**Comment by gotmachine** [comment]
This is more or less by design, this vessel type shouldn't be used for anything else than Breaking Ground surface stuff.

**Comment by gotmachine** [comment]
Actually, this was an easily fixed oversight following the comms refactor
