### ISSUE TITLE
Near no science in rss/ro/rp1 with Kerbalism?

### ISSUE THREAD

**Issue by Ineedhelo** [Kerbalism/Kerbalism#855]
Near no science in rss/ro/rp1 with Kerbalism?

I am playing rp1 for the first time, and have gotten decently far. After I started nearing my first orbit, science collection started slowing down, and I just assumed that it was part of the game. Now, after I have launched multiple satellites with cosmic ray science and micrometeorite detection, and kept the satellite in space with power for 90 days, the experiments finished. I was defeated to see that both of those experiments transmitted added to be 0.8 science points. I had 2.2 before, and 3 after it was completed. I am confused because the experiments say they should be worth up to 11 science points? My kerbalism settings are on default.

**Comment by gotmachine** [comment]
Any issue pertaining to the RP1 configs should be addressed to the RP1 team.
