### ISSUE TITLE
[Request] Smart Parts Support

### ISSUE THREAD

**Issue by Mitokandria** [Kerbalism/Kerbalism#857]
One of the few things missing is the ability to activate action groups with Kerbalism's automation. It would really add a lot of versatility to be able to activate the parts from Smart Parts.

Example:
Problem? High quality parts need to be stowed during high radiation. 

[Kerbalism]
=Radiation Low=
Chronometer Action Group Trigger (1): On
=Radiation High=
Chronometer Action Group Trigger (2): On

[Chronome[ter AG Trigger (1)]
Seconds: 1
Activate Action Group: 1

[Chronometer AG Trigger (2)[
Seconds: 1
Activate Action Group: 2

[Action Group 1]
Cargo Bay: Open

[Action Group 2]
Cargo Bay: Closed

**Comment by gotmachine** [comment]
While I agree this would be a useful feature, the conceptual issue is that action groups and Smart Parts are only available while the vessel is loaded, but Kerbalism continously simulate stuff like radiation for all vessels in the background. So such a feature would stop working as soon as you leave the vessel, making it pretty much useless.
