### ISSUE TITLE
WasteProcessor cannot vent Ammonia (see PR 858)

### ISSUE THREAD

**Issue by avafyi** [Kerbalism/Kerbalism#859]
Currently WasteProcessor systems cannot vent excess Ammonia, so they stop if there is no Ammonia storage. Fixed with PR #858

**Comment by gotmachine** [comment]
I don't see the use case for this.
Dumping the ammonia output means wasting electric charge for no reason. Waste produced by Kerbals in excess of storage capacity is dumped anyway...
