### ISSUE TITLE
Loading has failed due to an unhandled error

### ISSUE THREAD

**Issue by richardcocks** [Kerbalism/Kerbalism#860]
Failure to load KSP after installing Kerbalism with science only config:

```
Loading has failed due to an unhandled error

Failure in subsystem : Part compilation
Part: Greenhouse (KerbalismScienceOnly/Parts/Greenhouse/kerbalism-greenhouse/kerbalism-greenhouse)

System.NullReferenceException: Object reference not set to an instance of an object
  at PartResourceDefinitionList.Contains (System.String name) [0x00000] in <4b449f2841f84227adfaad3149c8fdba>:0 
  at KERBALISM.Lib.GetDefinition (System.String name) [0x0000b] in <0f2cb93152734cf5bc1a865e44cdc55d>:0 
  at KERBALISM.Lib.GetResourceDisplayName (System.String name) [0x00000] in <0f2cb93152734cf5bc1a865e44cdc55d>:0 
  at KERBALISM.Greenhouse.Specs () [0x00006] in <0f2cb93152734cf5bc1a865e44cdc55d>:0 
  at KERBALISM.Greenhouse.GetInfo () [0x00008] in <0f2cb93152734cf5bc1a865e44cdc55d>:0 
  at PartLoader.CompilePartInfo (AvailablePart newPartInfo, Part part) [0x0017c] in <4b449f2841f84227adfaad3149c8fdba>:0 
  at (wrapper dynamic-method) PartLoader+<CompileParts>d__56.PartLoader+<CompileParts>d__56.MoveNext_Patch0(PartLoader/<CompileParts>d__56)
  at KSPCommunityFixes.Performance.KSPCFFastLoader+<FrameUnlockedCoroutine>d__62.MoveNext () [0x0006c] in <1ab895c297764334bc8ca0487ca3a837>:0 

```

Full mod list:

- B9 Part Switch (B9PartSwitch v2.20.0)
- BetterBurnTime (BetterBurnTime 1.10)
- Breaking Ground (BreakingGround-DLC 1.7.1)
- CapCom - Mission Control On The Go (CapCom 2.11)
- Celestial Body Science Editor (CelestialBodyScienceEditor 12.0)
- ClickThrough Blocker (ClickThroughBlocker 1:2.1.10.21)
- Community Resource Pack (CommunityResourcePack v112.0.1)
- Community Tech Tree (CommunityTechTree 1:3.4.4)
- Contract Configurator (ContractConfigurator v2.5.0.1)
- Contract Parser (ContractParser 9.0)
- Contracts Window + (ContractsWindowPlus 9.4)
- Deployable Engines Plugin (DeployableEngines 1.3.1)
- Engine Ignitor (standalone) (EngineIgnitorReignited 1.3.7.6)
- Harmony 2 (Harmony2 2.2.1.0)
- Heat Control (HeatControl 0.6.1)
- Kerbal Changelog (KerbalChangelog v1.4.2)
- Kerbal Joint Reinforcement Continued (KerbalJointReinforcementContinued v3.7.1.0)
- Kerbalism (Kerbalism 3.17)
- Kerbalism - Science-Only Config (Kerbalism-Config-ScienceOnly 3.14)
- Kopernicus Planetary System Modifier (Kopernicus 2:release-1.12.1-166)
- KSP Community Fixes (KSPCommunityFixes 1.27.0)
- Making History (MakingHistory-DLC 1.12.1)
- ModularFlightIntegrator (ModularFlightIntegrator 1.2.10.0)
- Module Manager (ModuleManager 4.2.2)
- Near Future IVA Props (NearFutureProps 1:0.7.1)
- Parallax (Parallax 2.0.6)
- Parallax - Stock Planet Textures (Parallax-StockTextures 2.0.0)
- Parallax - Stock Scatter Textures (Parallax-StockScatterTextures 2.0.1)
- PlanetShine (PlanetShine 0.2.6.6)
- PlanetShine - Default configuration (PlanetShine-Config-Default 0.2.6.6)
- Probes Before Crew [PBC] (ProbesBeforeCrew 2.93)
- Procedural Fairings (ProceduralFairings 1:v6.3.0)
- Procedural Fairings - For Everything! (ProceduralFairings-ForEverything v0.3.0)
- Progress Parser (ProgressParser 11.0)
- SCANsat (SCANsat v20.4)
- Scatterer (Scatterer 3:v0.0838)
- Scatterer Default Config (Scatterer-config 3:v0.0838)
- Scatterer Sunflare (Scatterer-sunflare 3:v0.0838)
- SpaceTux Library (SpaceTuxLibrary 0.0.8.5)
- Stock Waterfall Effects (StockWaterfallEffects 0.7.0)
- System Heat (SystemHeat 0.6.0)
- Toolbar (Toolbar 1:1.8.1)
- Toolbar Controller (ToolbarController 1:0.1.9.9)
- Waterfall Core (Waterfall 0.9.0)
- WaypointManager (WaypointManager 2.8.3.5)
- Zero MiniAVC (ZeroMiniAVC 1:1.1.3.2)

**Comment by richardcocks** [comment]
I've just noticed that Kerbalism Science only Config is only on 3.14 compared to 3.17, so this is a duplicate of https://github.com/Kerbalism/KerbalismScienceOnly/issues/4 .

**Comment by hypodronic** [comment]
If you want to try out my Science Only 3.17 patch let me know if you have any problems. If a few people can confirm it's okay, I'll do a PR.
https://github.com/hypodronic/KerbalismScienceOnly
