### ISSUE TITLE
Oxygen doesn't exist in RP-1

### ISSUE THREAD

**Issue by Forgerhart** [Kerbalism/Kerbalism#865]
I made a brand new RP-1 express install through kerbalism. I researched crew survivability that allows me to add oxygen into service modules, but when I try it simply says 'no tech for oxygen'. I tried searching the internet but to no avail. I reinstalled the whole RP-1 express install, but still no technology for oxygen apparently. Oxygen doesn't exist in capsules as well.  What do I do? I can't progress whatsoever
![image](https://github.com/Kerbalism/Kerbalism/assets/63512691/bbb9b164-d0ae-4c61-9c56-0bd031512bf4)

**Comment by gotmachine** [comment]
Kerbalism doesn't manage resource containers and tech levels, I suggest you ask in the ro/rp1 discord.

**Comment by Capkirk123** [comment]
This is 100% an RP-1/RO issue, you may close this.
