### ISSUE TITLE
[RO] Configurable fuel cells do not remember settings

### ISSUE THREAD

**Issue by Capkirk123** [Kerbalism/Kerbalism#867]
Resolved-ish, see comment below 

Ok, the issue is as follows:
RO (well, ROKerbalism) has configurable fuel cells. All the configs are set up like any process, and they are all identical other than name and mass (more modern fuel cells are less massive, efficiency stays the same).

### Symptoms displayed include:
**In the VAB:** 
When placing N configurable fuel cells on a vessel, the kerbalism menu only displays the resource production and consumption of N-1 fuel cells (e.g. placing 6 1 kW fuel cells will only show power production and resource consumption of 5 kW, and placing 1 fuel cell will show no power production or resource consumption).

If any of these fuel cells are then picked up again, they will stop displaying power production completely. Although they will still show they are active in their PAW, they must be individually turned off and on again to properly display their production and consumption (all configurable fuel cells on the vessel must have their PAW opened and status reset, regardless of symmetry).

**In the flight scene:**
Configurable fuel cells will immediately stop working when the vessel loads into the flight scene, regardless of their setting in the VAB. They will show whatever settings they had in the VAB in their PAW, but once again, must be individually turned off and on again to actually begin working.

Although the fuel cells will remain functioning while the player is focused, and will continue to function when the vessel is unloaded, they will once again break whenever the vessel is loaded (whether by switching to it with the Tracking Station, switching to it with the Kerbalism menu, or rendezvousing with it), and once again all fuel cells must be individually turned off and on again to restore functionality.

These symptoms only effect configurable fuel cells. Parts with integral, preset fuel cells work completely fine. Parts with configurable processes that aren't the fuel cell (e.g. the chemical plant) work perfectly fine.

I strongly suspect creating multiple identical processes that differ only in title is the culprit here. For whatever reason, Kerbalism is unable to recognize them properly and therefore cannot remember their settings. Unfortunately, I have no more time to troubleshoot tonight. I will experiment with removing these identical processes tomorrow.

**Comment by Capkirk123** [comment]
Yup, it was the identical configs creating the issue. If multiple configs are created using the same process, kerbalism cannot properly identify the configs, resulting in it forgetting their settings. Creating new processes with unique names for each config resolves the issue.

**Comment by gotmachine** [comment]
I think we sorted that issue over discord. The configuration used is indeed not supported, but can easily be worked around by defining multiple processes instead.
