### ISSUE TITLE
NaN/XYZ science value

### ISSUE THREAD

**Issue by nicesub** [Kerbalism/Kerbalism#875]
Hi,

I am facing this issue where if I time warp above x1000 long running experiments like seismic observation that take 14 days will show NaN value and will stop running. Also noticed that the craft running this experiment losses connection to the network as far is the Kerbalism mod concerned but when I go to map or check the status in top left corner I can clearly see that the craft has connection to the network.

To fix this I have to change the scene by swithcing to other craft or space center or switching between buildings. Then Kerbalism will refresh the status of the crafts and connections and NaN will disapear only to come back when I timewarp.
Also it seems so far to only affect crafts on the ground I do not thinkl I have seen same bug on crafts in orbit but I am kinda early in the game so I do not have much of experiments that will take ages in orbit.

**Comment by NathanKell** [comment]
This might be related to the solar panel work I did. Try turning sun sampling to true in your (kerbalism config's) settings.cfg and see if the issue goes away.

**Comment by kaputzz** [comment]
Should we apply that fix? 
I still didn't encounter this NaN issue..

UseSamplingSunFactor = false 

Should I still set the property above to true?

**Comment by NathanKell** [comment]
Kerbalism 3.19 has been released and it should have fixed this issue. Please let me know if you encounter it again.
