### ISSUE TITLE
EVA Experiments not working in KSC Sub-Biomes

### ISSUE THREAD

**Issue by mariohead** [Kerbalism/Kerbalism#899]
When a Kerbal is EVA within one of the KSC’s many sub-biomes (the Runway, SPH Tanks, SPH Water Tower, and SPH were tested for this issue), Surface Samples and EVA Reports could not be completed. When using in combination with Science [x], it seems that the game registers that the Kerbal is within the Sub-Biome, but Kerbalism registers being landed at Kerbin’s Shores.

**Comment by gotmachine** [comment]
This is by design.

**Comment by mariohead** [comment]
How are we meant to get surface samples/EVA reports, then? Is there a part unlocked later on?
